// Auto-generated by TagTranspiler (GenerateObject.py)
// Source XML: coll.xml

export module Map.Tag.Type:Coll.Object;

import :Coll.Structure;
import std;

namespace
{
    using namespace Map::Tag::Type::Coll::Structure;
}

export namespace Map::Tag::Type::Coll::Object
{
    struct Coll_Regions_Permutations_BspsObject : public Coll_Regions_Permutations_BspsEntry
    {
        std::vector<Coll_Regions_Permutations_Bsps_Bsp3dNodesEntry> Bsp3dNodes;
        std::vector<Coll_Regions_Permutations_Bsps_Bsp3dSupernodesEntry> Bsp3dSupernodes;
        std::vector<Coll_Regions_Permutations_Bsps_PlanesEntry> Planes;
        std::vector<Coll_Regions_Permutations_Bsps_LeavesEntry> Leaves;
        std::vector<Coll_Regions_Permutations_Bsps_Bsp2dReferencesEntry> Bsp2dReferences;
        std::vector<Coll_Regions_Permutations_Bsps_Bsp2dNodesEntry> Bsp2dNodes;
        std::vector<Coll_Regions_Permutations_Bsps_SurfacesEntry> Surfaces;
        std::vector<Coll_Regions_Permutations_Bsps_EdgesEntry> Edges;
        std::vector<Coll_Regions_Permutations_Bsps_VerticesEntry> Vertices;
    };

    struct Coll_Regions_Permutations_MoppCodesObject : public Coll_Regions_Permutations_MoppCodesEntry
    {
        std::vector<Coll_Regions_Permutations_MoppCodes_MoppDataEntry> MoppData;
    };

    struct Coll_Regions_PermutationsObject : public Coll_Regions_PermutationsEntry
    {
        std::vector<Coll_Regions_Permutations_BspsObject> Bsps;
        std::vector<Coll_Regions_Permutations_BspPhysicsEntry> BspPhysics;
        std::vector<Coll_Regions_Permutations_MoppCodesObject> MoppCodes;
    };

    struct Coll_RegionsObject : public Coll_RegionsEntry
    {
        std::vector<Coll_Regions_PermutationsObject> Permutations;
    };

    struct CollObject
    {
        std::string  TagName;
        CollData Data;

        std::vector<Coll_MaterialsEntry> Materials;
        std::vector<Coll_RegionsObject> Regions;
        std::vector<Coll_PathfindingSpheresEntry> PathfindingSpheres;
        std::vector<Coll_NodesEntry> Nodes;
    };
}
