// Auto-generated by TagTranspiler (GenerateTemplate.py)
// Source XML: anim.xml
// Component range: 0x1A8..0x1B8 (absolute datum offsets).

export module Template.Object.Type:Anim.Offset;

import std;

export namespace Template::Object::Type::Anim::Offset
{
    constexpr std::size_t k_Unknown1a9                                  = 0x1A9;  // uint8.
    constexpr std::size_t k_Unknown1ae                                  = 0x1AE;  // uint16.
    constexpr std::size_t k_Unknown1b0                                  = 0x1B0;  // uint16.
    constexpr std::size_t k_Unknown1b2                                  = 0x1B2;  // uint16.
    constexpr std::size_t k_Unknown1b4                                  = 0x1B4;  // uint32.
}