// Auto-generated by TagTranspiler (GenerateObject.py)
// Source XML: bipd.xml

export module Map.Tag.System:Bipd.Descriptor;

import Map.Tag.Type;
import Map.Reader.Type;
import Map.Reader.System;
import std;

namespace
{
    using namespace Map::Tag::Type::Bipd::Structure;
    using namespace Map::Tag::Type::Bipd::Object;
    namespace MapMagic = Map::Reader::Type::Magic;
}

export namespace Map::Reader::System
{
    template <>
    struct GroupDescriptor<BipdObject>
    {
        using DataType = BipdData;
        static constexpr std::uint32_t Magic = MapMagic::Tag::k_Bipd;

        template <typename TReader>
        static void ReadBlocks(
            std::ifstream& file,
            const TReader& reader,
            BipdObject& obj)
        {
            obj.EarlyMoverOrientedBoundingBox = reader.template ReadBlock<Bipd_EarlyMoverOrientedBoundingBoxEntry>(file, obj.Data.EarlyMoverOrientedBoundingBox);
            obj.AiProperties = reader.template ReadBlock<Bipd_AiPropertiesEntry>(file, obj.Data.AiProperties);
            {
                auto disk_Functions_0 = reader.template ReadBlock<Bipd_FunctionsEntry>(file, obj.Data.Functions);
                obj.Functions.reserve(disk_Functions_0.size());
                for (auto& diskEntry_0 : disk_Functions_0)
                {
                    Bipd_FunctionsObject entry_Functions_0{static_cast<Bipd_FunctionsEntry>(diskEntry_0)};
                    entry_Functions_0.Interpolation = reader.template ReadBlock<Bipd_Functions_InterpolationEntry>(file, diskEntry_0.Interpolation);
                    obj.Functions.push_back(entry_Functions_0);
                }
            }
            obj.RuntimeInterpolatorFunctions = reader.template ReadBlock<Bipd_RuntimeInterpolatorFunctionsEntry>(file, obj.Data.RuntimeInterpolatorFunctions);
            obj.Attachments = reader.template ReadBlock<Bipd_AttachmentsEntry>(file, obj.Data.Attachments);
            {
                auto disk_HullSurfaces_0 = reader.template ReadBlock<Bipd_HullSurfacesEntry>(file, obj.Data.HullSurfaces);
                obj.HullSurfaces.reserve(disk_HullSurfaces_0.size());
                for (auto& diskEntry_0 : disk_HullSurfaces_0)
                {
                    Bipd_HullSurfacesObject entry_HullSurfaces_0{static_cast<Bipd_HullSurfacesEntry>(diskEntry_0)};
                    entry_HullSurfaces_0.Drag = reader.template ReadBlock<Bipd_HullSurfaces_DragEntry>(file, diskEntry_0.Drag);
                    obj.HullSurfaces.push_back(entry_HullSurfaces_0);
                }
            }
            obj.Jetwash = reader.template ReadBlock<Bipd_JetwashEntry>(file, obj.Data.Jetwash);
            obj.Widgets = reader.template ReadBlock<Bipd_WidgetsEntry>(file, obj.Data.Widgets);
            {
                auto disk_ChangeColors_0 = reader.template ReadBlock<Bipd_ChangeColorsEntry>(file, obj.Data.ChangeColors);
                obj.ChangeColors.reserve(disk_ChangeColors_0.size());
                for (auto& diskEntry_0 : disk_ChangeColors_0)
                {
                    Bipd_ChangeColorsObject entry_ChangeColors_0{static_cast<Bipd_ChangeColorsEntry>(diskEntry_0)};
                    entry_ChangeColors_0.InitialPermutations = reader.template ReadBlock<Bipd_ChangeColors_InitialPermutationsEntry>(file, diskEntry_0.InitialPermutations);
                    entry_ChangeColors_0.Functions = reader.template ReadBlock<Bipd_ChangeColors_FunctionsEntry>(file, diskEntry_0.Functions);
                    obj.ChangeColors.push_back(entry_ChangeColors_0);
                }
            }
            obj.MultiplayerObject = reader.template ReadBlock<Bipd_MultiplayerObjectEntry>(file, obj.Data.MultiplayerObject);
            obj.SpawnEffects = reader.template ReadBlock<Bipd_SpawnEffectsEntry>(file, obj.Data.SpawnEffects);
            obj.CampaignMetagameBucket = reader.template ReadBlock<Bipd_CampaignMetagameBucketEntry>(file, obj.Data.CampaignMetagameBucket);
            obj.ScreenEffects = reader.template ReadBlock<Bipd_ScreenEffectsEntry>(file, obj.Data.ScreenEffects);
            obj.CameraTracks = reader.template ReadBlock<Bipd_CameraTracksEntry>(file, obj.Data.CameraTracks);
            obj.CameraAcceleration = reader.template ReadBlock<Bipd_CameraAccelerationEntry>(file, obj.Data.CameraAcceleration);
            {
                auto disk_MoveStickOverrides_0 = reader.template ReadBlock<Bipd_MoveStickOverridesEntry>(file, obj.Data.MoveStickOverrides);
                obj.MoveStickOverrides.reserve(disk_MoveStickOverrides_0.size());
                for (auto& diskEntry_0 : disk_MoveStickOverrides_0)
                {
                    Bipd_MoveStickOverridesObject entry_MoveStickOverrides_0{static_cast<Bipd_MoveStickOverridesEntry>(diskEntry_0)};
                    entry_MoveStickOverrides_0.InputMappingFunction = reader.template ReadBlock<Bipd_MoveStickOverrides_InputMappingFunctionEntry>(file, diskEntry_0.InputMappingFunction);
                    obj.MoveStickOverrides.push_back(entry_MoveStickOverrides_0);
                }
            }
            {
                auto disk_LookStickOverrides_0 = reader.template ReadBlock<Bipd_LookStickOverridesEntry>(file, obj.Data.LookStickOverrides);
                obj.LookStickOverrides.reserve(disk_LookStickOverrides_0.size());
                for (auto& diskEntry_0 : disk_LookStickOverrides_0)
                {
                    Bipd_LookStickOverridesObject entry_LookStickOverrides_0{static_cast<Bipd_LookStickOverridesEntry>(diskEntry_0)};
                    entry_LookStickOverrides_0.InputMappingFunction = reader.template ReadBlock<Bipd_LookStickOverrides_InputMappingFunctionEntry>(file, diskEntry_0.InputMappingFunction);
                    obj.LookStickOverrides.push_back(entry_LookStickOverrides_0);
                }
            }
            obj.CameraTracks_2 = reader.template ReadBlock<Bipd_CameraTracksEntry_2>(file, obj.Data.CameraTracks_2);
            obj.CameraAcceleration_2 = reader.template ReadBlock<Bipd_CameraAccelerationEntry_2>(file, obj.Data.CameraAcceleration_2);
            {
                auto disk_MoveStickOverrides_0 = reader.template ReadBlock<Bipd_MoveStickOverridesEntry_2>(file, obj.Data.MoveStickOverrides_2);
                obj.MoveStickOverrides_2.reserve(disk_MoveStickOverrides_0.size());
                for (auto& diskEntry_0 : disk_MoveStickOverrides_0)
                {
                    Bipd_MoveStickOverridesObject_2 entry_MoveStickOverrides_0{static_cast<Bipd_MoveStickOverridesEntry_2>(diskEntry_0)};
                    entry_MoveStickOverrides_0.InputMappingFunction = reader.template ReadBlock<Bipd_MoveStickOverrides_2_InputMappingFunctionEntry>(file, diskEntry_0.InputMappingFunction);
                    obj.MoveStickOverrides_2.push_back(entry_MoveStickOverrides_0);
                }
            }
            {
                auto disk_LookStickOverrides_0 = reader.template ReadBlock<Bipd_LookStickOverridesEntry_2>(file, obj.Data.LookStickOverrides_2);
                obj.LookStickOverrides_2.reserve(disk_LookStickOverrides_0.size());
                for (auto& diskEntry_0 : disk_LookStickOverrides_0)
                {
                    Bipd_LookStickOverridesObject_2 entry_LookStickOverrides_0{static_cast<Bipd_LookStickOverridesEntry_2>(diskEntry_0)};
                    entry_LookStickOverrides_0.InputMappingFunction = reader.template ReadBlock<Bipd_LookStickOverrides_2_InputMappingFunctionEntry>(file, diskEntry_0.InputMappingFunction);
                    obj.LookStickOverrides_2.push_back(entry_LookStickOverrides_0);
                }
            }
            obj.HudInterfaces = reader.template ReadBlock<Bipd_HudInterfacesEntry>(file, obj.Data.HudInterfaces);
            obj.PoweredSeats = reader.template ReadBlock<Bipd_PoweredSeatsEntry>(file, obj.Data.PoweredSeats);
            obj.Weapons = reader.template ReadBlock<Bipd_WeaponsEntry>(file, obj.Data.Weapons);
            {
                auto disk_TargetTracking_0 = reader.template ReadBlock<Bipd_TargetTrackingEntry>(file, obj.Data.TargetTracking);
                obj.TargetTracking.reserve(disk_TargetTracking_0.size());
                for (auto& diskEntry_0 : disk_TargetTracking_0)
                {
                    Bipd_TargetTrackingObject entry_TargetTracking_0{static_cast<Bipd_TargetTrackingEntry>(diskEntry_0)};
                    entry_TargetTracking_0.TrackingTypes = reader.template ReadBlock<Bipd_TargetTracking_TrackingTypesEntry>(file, diskEntry_0.TrackingTypes);
                    obj.TargetTracking.push_back(entry_TargetTracking_0);
                }
            }
            {
                auto disk_Seats_0 = reader.template ReadBlock<Bipd_SeatsEntry>(file, obj.Data.Seats);
                obj.Seats.reserve(disk_Seats_0.size());
                for (auto& diskEntry_0 : disk_Seats_0)
                {
                    Bipd_SeatsObject entry_Seats_0{static_cast<Bipd_SeatsEntry>(diskEntry_0)};
                    entry_Seats_0.AdditionalBoardingSeats = reader.template ReadBlock<Bipd_Seats_AdditionalBoardingSeatsEntry>(file, diskEntry_0.AdditionalBoardingSeats);
                    entry_Seats_0.CameraTracks = reader.template ReadBlock<Bipd_Seats_CameraTracksEntry>(file, diskEntry_0.CameraTracks);
                    entry_Seats_0.CameraAcceleration = reader.template ReadBlock<Bipd_Seats_CameraAccelerationEntry>(file, diskEntry_0.CameraAcceleration);
                    {
                        auto disk_MoveStickOverrides_1 = reader.template ReadBlock<Bipd_Seats_MoveStickOverridesEntry>(file, diskEntry_0.MoveStickOverrides);
                        entry_Seats_0.MoveStickOverrides.reserve(disk_MoveStickOverrides_1.size());
                        for (auto& diskEntry_1 : disk_MoveStickOverrides_1)
                        {
                            Bipd_Seats_MoveStickOverridesObject entry_MoveStickOverrides_1{static_cast<Bipd_Seats_MoveStickOverridesEntry>(diskEntry_1)};
                            entry_MoveStickOverrides_1.InputMappingFunction = reader.template ReadBlock<Bipd_Seats_MoveStickOverrides_InputMappingFunctionEntry>(file, diskEntry_1.InputMappingFunction);
                            entry_Seats_0.MoveStickOverrides.push_back(entry_MoveStickOverrides_1);
                        }
                    }
                    {
                        auto disk_LookStickOverrides_1 = reader.template ReadBlock<Bipd_Seats_LookStickOverridesEntry>(file, diskEntry_0.LookStickOverrides);
                        entry_Seats_0.LookStickOverrides.reserve(disk_LookStickOverrides_1.size());
                        for (auto& diskEntry_1 : disk_LookStickOverrides_1)
                        {
                            Bipd_Seats_LookStickOverridesObject entry_LookStickOverrides_1{static_cast<Bipd_Seats_LookStickOverridesEntry>(diskEntry_1)};
                            entry_LookStickOverrides_1.InputMappingFunction = reader.template ReadBlock<Bipd_Seats_LookStickOverrides_InputMappingFunctionEntry>(file, diskEntry_1.InputMappingFunction);
                            entry_Seats_0.LookStickOverrides.push_back(entry_LookStickOverrides_1);
                        }
                    }
                    entry_Seats_0.SeatHudInterfaces = reader.template ReadBlock<Bipd_Seats_SeatHudInterfacesEntry>(file, diskEntry_0.SeatHudInterfaces);
                    obj.Seats.push_back(entry_Seats_0);
                }
            }
            obj.Tricks = reader.template ReadBlock<Bipd_TricksEntry>(file, obj.Data.Tricks);
            obj.CameraHeights = reader.template ReadBlock<Bipd_CameraHeightsEntry>(file, obj.Data.CameraHeights);
            obj.WallProximityFeelers = reader.template ReadBlock<Bipd_WallProximityFeelersEntry>(file, obj.Data.WallProximityFeelers);
            obj.MovementGates = reader.template ReadBlock<Bipd_MovementGatesEntry>(file, obj.Data.MovementGates);
            obj.MovementGatesCrouching = reader.template ReadBlock<Bipd_MovementGatesCrouchingEntry>(file, obj.Data.MovementGatesCrouching);
            obj.DeadSphereShapes = reader.template ReadBlock<Bipd_DeadSphereShapesEntry>(file, obj.Data.DeadSphereShapes);
            obj.PillShapes = reader.template ReadBlock<Bipd_PillShapesEntry>(file, obj.Data.PillShapes);
            obj.SphereShapes = reader.template ReadBlock<Bipd_SphereShapesEntry>(file, obj.Data.SphereShapes);
            obj.ContactPoints = reader.template ReadBlock<Bipd_ContactPointsEntry>(file, obj.Data.ContactPoints);
        }
    };
}
