// Auto-generated by TagTranspiler (GenerateTemplate.py)
// Source XML: vehi.xml
// Component range: 0x9D8..0xDE8 (absolute datum offsets).

export module Tables.Template.Type:Vehi.Offset;

import std;

export namespace Tables::Template::Type::Vehi::Offset
{
    constexpr std::size_t k_Unknown9d8                                  = 0x9D8;  // uint32.
    constexpr std::size_t k_Unknown9de                                  = 0x9DE;  // uint16.
    constexpr std::size_t k_Unknown9e0                                  = 0x9E0;  // uint8.
    constexpr std::size_t k_Unknown9e4                                  = 0x9E4;  // uint32.
    constexpr std::size_t k_Unknown9e8                                  = 0x9E8;  // uint8.
    constexpr std::size_t k_UnknownA9e                                  = 0xA9E;  // uint8.
    constexpr std::size_t k_UnknownA9f                                  = 0xA9F;  // uint8.
    constexpr std::size_t k_UnknownAa0                                  = 0xAA0;  // uint32.
    constexpr std::size_t k_UnknownAa4                                  = 0xAA4;  // uint32.
    constexpr std::size_t k_UnknownAa8                                  = 0xAA8;  // uint32.
    constexpr std::size_t k_UnknownAac                                  = 0xAAC;  // uint8.
    constexpr std::size_t k_UnknownAad                                  = 0xAAD;  // uint8.
    constexpr std::size_t k_UnknownAb0                                  = 0xAB0;  // uint32.
    constexpr std::size_t k_UnknownAb4                                  = 0xAB4;  // uint16.
    constexpr std::size_t k_UnknownAb6                                  = 0xAB6;  // uint16.
    constexpr std::size_t k_UnknownAb8                                  = 0xAB8;  // uint32.
    constexpr std::size_t k_UnknownAbc                                  = 0xABC;  // uint32.
    constexpr std::size_t k_UnknownAc0                                  = 0xAC0;  // uint32.
    constexpr std::size_t k_UnknownAc4                                  = 0xAC4;  // uint32.
    constexpr std::size_t k_UnknownAc8                                  = 0xAC8;  // uint32.
    constexpr std::size_t k_UnknownAcc                                  = 0xACC;  // uint32.
    constexpr std::size_t k_UnknownAd0                                  = 0xAD0;  // uint32.
    constexpr std::size_t k_UnknownAd4                                  = 0xAD4;  // uint32.
    constexpr std::size_t k_UnknownAd8                                  = 0xAD8;  // uint16.
    constexpr std::size_t k_UnknownAda                                  = 0xADA;  // uint8.
    constexpr std::size_t k_UnknownB08                                  = 0xB08;  // uint32.
    constexpr std::size_t k_UnknownB0c                                  = 0xB0C;  // uint32.
    constexpr std::size_t k_UnknownB10                                  = 0xB10;  // uint32.
    constexpr std::size_t k_UnknownB20                                  = 0xB20;  // uint16.
    constexpr std::size_t k_UnknownB22                                  = 0xB22;  // uint16.
    constexpr std::size_t k_UnknownB24                                  = 0xB24;  // uint16.
    constexpr std::size_t k_UnknownB26                                  = 0xB26;  // uint16.
    constexpr std::size_t k_UnknownB28                                  = 0xB28;  // uint32.
    constexpr std::size_t k_UnknownB2c                                  = 0xB2C;  // uint32.
    constexpr std::size_t k_UnknownB30                                  = 0xB30;  // uint32.
    constexpr std::size_t k_UnknownB34                                  = 0xB34;  // uint32.
    constexpr std::size_t k_UnknownB38                                  = 0xB38;  // uint32.
    constexpr std::size_t k_UnknownB3c                                  = 0xB3C;  // uint8.
    constexpr std::size_t k_UnknownB6c                                  = 0xB6C;  // uint16.
    constexpr std::size_t k_UnknownB6e                                  = 0xB6E;  // uint16.
    constexpr std::size_t k_UnknownB70                                  = 0xB70;  // uint16.
    constexpr std::size_t k_UnknownB72                                  = 0xB72;  // uint16.
    constexpr std::size_t k_UnknownB74                                  = 0xB74;  // uint16.
    constexpr std::size_t k_UnknownB76                                  = 0xB76;  // uint16.
    constexpr std::size_t k_UnknownB78                                  = 0xB78;  // uint16.
    constexpr std::size_t k_UnknownB7a                                  = 0xB7A;  // uint16.
    constexpr std::size_t k_UnknownB7c                                  = 0xB7C;  // uint32.
    constexpr std::size_t k_UnknownB80                                  = 0xB80;  // uint16.
    constexpr std::size_t k_UnknownB82                                  = 0xB82;  // uint16.
    constexpr std::size_t k_UnknownB84                                  = 0xB84;  // uint16.
    constexpr std::size_t k_UnknownB86                                  = 0xB86;  // uint16.
    constexpr std::size_t k_UnknownD88                                  = 0xD88;  // uint32.
    constexpr std::size_t k_UnknownD8c                                  = 0xD8C;  // uint16.
    constexpr std::size_t k_UnknownD90                                  = 0xD90;  // uint32.
    constexpr std::size_t k_UnknownD94                                  = 0xD94;  // uint16.
    constexpr std::size_t k_UnknownD96                                  = 0xD96;  // uint16.
    constexpr std::size_t k_UnknownD98                                  = 0xD98;  // uint16.
    constexpr std::size_t k_UnknownD9a                                  = 0xD9A;  // uint16.
    constexpr std::size_t k_UnknownD9c                                  = 0xD9C;  // uint32.
    constexpr std::size_t k_UnknownDa0                                  = 0xDA0;  // uint32.
    constexpr std::size_t k_UnknownDa4                                  = 0xDA4;  // uint32.
    constexpr std::size_t k_UnknownDa8                                  = 0xDA8;  // uint32.
    constexpr std::size_t k_UnknownDac                                  = 0xDAC;  // uint32.
    constexpr std::size_t k_UnknownDb0                                  = 0xDB0;  // uint32.
    constexpr std::size_t k_UnknownDc0                                  = 0xDC0;  // uint64.
    constexpr std::size_t k_UnknownDc8                                  = 0xDC8;  // uint64.
    constexpr std::size_t k_UnknownDd0                                  = 0xDD0;  // uint32.
    constexpr std::size_t k_UnknownDd4                                  = 0xDD4;  // uint32.
    constexpr std::size_t k_UnknownDd8                                  = 0xDD8;  // uint32.
    constexpr std::size_t k_UnknownDdc                                  = 0xDDC;  // uint32.
    constexpr std::size_t k_UnknownDe6                                  = 0xDE6;  // uint16.
}