// Auto-generated by TagTranspiler (GenerateOffset.py)
// Source XML: sddt.xml
// Base size: 0x160.

export module Map.Tag.Type:Sddt.Offset;

import std;

export namespace Map::Tag::Type::Sddt::Offset
{
    constexpr std::size_t k_ManifestId0                                 = 0x0;  // uint32.
    constexpr std::size_t k_ManifestId1                                 = 0x4;  // uint32.
    constexpr std::size_t k_ManifestId2                                 = 0x8;  // uint32.
    constexpr std::size_t k_ManifestId3                                 = 0xC;  // uint32.
    constexpr std::size_t k_BuildIndex                                  = 0x10;  // int32.
    constexpr std::size_t k_StructureImporterVersion                    = 0x14;  // uint32.
    constexpr std::size_t k_ManifestId0_2                               = 0x18;  // uint32.
    constexpr std::size_t k_ManifestId1_2                               = 0x1C;  // uint32.
    constexpr std::size_t k_ManifestId2_2                               = 0x20;  // uint32.
    constexpr std::size_t k_ManifestId3_2                               = 0x24;  // uint32.
    constexpr std::size_t k_BuildIndex_2                                = 0x28;  // int32.
    constexpr std::size_t k_StructureImporterVersion_2                  = 0x2C;  // uint32.
    constexpr std::size_t k_ImporterVersion                             = 0x30;  // uint32.
    namespace SoftCeilingMoppCodes
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x34;
        constexpr std::size_t k_EntrySize = 0x60;

        constexpr std::size_t k_RuntimeCodePointer                          = 0x0;  // uint64.
        constexpr std::size_t k_Size                                        = 0x8;  // int16.
        constexpr std::size_t k_Count                                       = 0xA;  // int16.
        constexpr std::size_t k_Unknown                                     = 0xC;  // undefined.
        constexpr std::size_t k_UserData                                    = 0x10;  // uint64.
        constexpr std::size_t k_Type                                        = 0x18;  // int32.
        constexpr std::size_t k_Unknown_2                                   = 0x1C;  // undefined.
        constexpr std::size_t k_V                                           = 0x20;  // vector3.
        constexpr std::size_t k_WV                                          = 0x2C;  // float32.
        constexpr std::size_t k_RuntimeMoppCodePointer                      = 0x30;  // uint64.
        constexpr std::size_t k_DataSize                                    = 0x38;  // int32.
        constexpr std::size_t k_DataCapacity                                = 0x3C;  // uint32.
        constexpr std::size_t k_BuildType                                   = 0x40;  // int8.
        constexpr std::size_t k_Unknown_3                                   = 0x41;  // int8.
        constexpr std::size_t k_Unknown_4                                   = 0x42;  // int16.
        constexpr std::size_t k_Unknown_5                                   = 0x44;  // undefined.
        constexpr std::size_t k_Unknown_6                                   = 0x48;  // undefined.
        constexpr std::size_t k_Unknown_7                                   = 0x4C;  // undefined.
        namespace MoppData
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x50;
            constexpr std::size_t k_EntrySize = 0x1;

            constexpr std::size_t k_Data                                        = 0x0;  // uint8.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        constexpr std::size_t k_MoppBuildType                               = 0x5C;  // int8.
        constexpr std::size_t k_Unknown_8                                   = 0x5D;  // int8.
        constexpr std::size_t k_Unknown_9                                   = 0x5E;  // int16.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace SoftCeilings
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x40;
        constexpr std::size_t k_EntrySize = 0x14;

        constexpr std::size_t k_Name                                        = 0x0;  // StringID.
        constexpr std::size_t k_Type                                        = 0x4;  // enum16. [Acceleration=0x0, Soft Kill=0x1, Slip Surface=0x2]
        constexpr std::size_t k_Unknown                                     = 0x6;  // int16.
        namespace SoftCeilingTriangles
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x8;
            constexpr std::size_t k_EntrySize = 0x44;

            constexpr std::size_t k_Plane                                       = 0x0;  // plane3.
            constexpr std::size_t k_BoundingSphereCenter                        = 0x10;  // point3.
            constexpr std::size_t k_BoundingSphereRadius                        = 0x1C;  // float32.
            constexpr std::size_t k_Vertex0                                     = 0x20;  // point3.
            constexpr std::size_t k_Vertex1                                     = 0x2C;  // point3.
            constexpr std::size_t k_Vertex2                                     = 0x38;  // point3.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }


        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace WaterMoppCodes
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x4C;
        constexpr std::size_t k_EntrySize = 0x60;

        constexpr std::size_t k_RuntimeCodePointer                          = 0x0;  // uint64.
        constexpr std::size_t k_Size                                        = 0x8;  // int16.
        constexpr std::size_t k_Count                                       = 0xA;  // int16.
        constexpr std::size_t k_Unknown                                     = 0xC;  // undefined.
        constexpr std::size_t k_UserData                                    = 0x10;  // uint64.
        constexpr std::size_t k_Type                                        = 0x18;  // int32.
        constexpr std::size_t k_Unknown_2                                   = 0x1C;  // undefined.
        constexpr std::size_t k_V                                           = 0x20;  // vector3.
        constexpr std::size_t k_WV                                          = 0x2C;  // float32.
        constexpr std::size_t k_RuntimeMoppCodePointer                      = 0x30;  // uint64.
        constexpr std::size_t k_DataSize                                    = 0x38;  // int32.
        constexpr std::size_t k_DataCapacity                                = 0x3C;  // uint32.
        constexpr std::size_t k_BuildType                                   = 0x40;  // int8.
        constexpr std::size_t k_Unknown_3                                   = 0x41;  // int8.
        constexpr std::size_t k_Unknown_4                                   = 0x42;  // int16.
        constexpr std::size_t k_Unknown_5                                   = 0x44;  // undefined.
        constexpr std::size_t k_Unknown_6                                   = 0x48;  // undefined.
        constexpr std::size_t k_Unknown_7                                   = 0x4C;  // undefined.
        namespace MoppData
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x50;
            constexpr std::size_t k_EntrySize = 0x1;

            constexpr std::size_t k_Data                                        = 0x0;  // uint8.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        constexpr std::size_t k_MoppBuildType                               = 0x5C;  // int8.
        constexpr std::size_t k_Unknown_8                                   = 0x5D;  // int8.
        constexpr std::size_t k_Unknown_9                                   = 0x5E;  // int16.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace WaterGroups
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x58;
        constexpr std::size_t k_EntrySize = 0x4;

        constexpr std::size_t k_Name                                        = 0x0;  // StringID.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace WaterInstances
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x64;
        constexpr std::size_t k_EntrySize = 0x54;

        constexpr std::size_t k_GroupIndex                                  = 0x0;  // int16.
        constexpr std::size_t k_Unknown                                     = 0x2;  // int16.
        constexpr std::size_t k_FlowVelocity                                = 0x4;  // vector3.
        constexpr std::size_t k_FogColor                                    = 0x10;  // colorf.
        constexpr std::size_t k_FogMurkiness                                = 0x20;  // float32.
        namespace WaterPlanes
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x24;
            constexpr std::size_t k_EntrySize = 0x10;

            constexpr std::size_t k_Plane                                       = 0x0;  // plane3.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace WaterDebugTriangles
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x30;
            constexpr std::size_t k_EntrySize = 0x24;

            constexpr std::size_t k_Point0                                      = 0x0;  // point3.
            constexpr std::size_t k_Point1                                      = 0xC;  // point3.
            constexpr std::size_t k_Point2                                      = 0x18;  // point3.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        constexpr std::size_t k_BoundsX                                     = 0x3C;  // rangef.
        constexpr std::size_t k_BoundsY                                     = 0x44;  // rangef.
        constexpr std::size_t k_BoundsZ                                     = 0x4C;  // rangef.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace PlanarFog
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x70;
        constexpr std::size_t k_EntrySize = 0x3C;

        constexpr std::size_t k_Name                                        = 0x0;  // StringID.
        constexpr std::size_t k_AppearanceSettings                          = 0x4;  // TagReference.
        namespace Vertices
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x14;
            constexpr std::size_t k_EntrySize = 0xC;

            constexpr std::size_t k_Position                                    = 0x0;  // point3.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace Triangles
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x20;
            constexpr std::size_t k_EntrySize = 0xC;

            namespace Planes
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x0;
                constexpr std::size_t k_EntrySize = 0x10;

                constexpr std::size_t k_Plane                                       = 0x0;  // plane3.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }


            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        constexpr std::size_t k_Depth                                       = 0x2C;  // float32.
        constexpr std::size_t k_Normal                                      = 0x30;  // vector3.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace MoppCodes
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x7C;
        constexpr std::size_t k_EntrySize = 0x60;

        constexpr std::size_t k_RuntimeCodePointer                          = 0x0;  // uint64.
        constexpr std::size_t k_Size                                        = 0x8;  // int16.
        constexpr std::size_t k_Count                                       = 0xA;  // int16.
        constexpr std::size_t k_Unknown                                     = 0xC;  // undefined.
        constexpr std::size_t k_UserData                                    = 0x10;  // uint64.
        constexpr std::size_t k_Type                                        = 0x18;  // int32.
        constexpr std::size_t k_Unknown_2                                   = 0x1C;  // undefined.
        constexpr std::size_t k_V                                           = 0x20;  // vector3.
        constexpr std::size_t k_WV                                          = 0x2C;  // float32.
        constexpr std::size_t k_RuntimeMoppCodePointer                      = 0x30;  // uint64.
        constexpr std::size_t k_DataSize                                    = 0x38;  // int32.
        constexpr std::size_t k_DataCapacity                                = 0x3C;  // uint32.
        constexpr std::size_t k_BuildType                                   = 0x40;  // int8.
        constexpr std::size_t k_Unknown_3                                   = 0x41;  // int8.
        constexpr std::size_t k_Unknown_4                                   = 0x42;  // int16.
        constexpr std::size_t k_Unknown_5                                   = 0x44;  // undefined.
        constexpr std::size_t k_Unknown_6                                   = 0x48;  // undefined.
        constexpr std::size_t k_Unknown_7                                   = 0x4C;  // undefined.
        namespace MoppData
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x50;
            constexpr std::size_t k_EntrySize = 0x1;

            constexpr std::size_t k_Data                                        = 0x0;  // uint8.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        constexpr std::size_t k_MoppBuildType                               = 0x5C;  // int8.
        constexpr std::size_t k_Unknown_8                                   = 0x5D;  // int8.
        constexpr std::size_t k_Unknown_9                                   = 0x5E;  // int16.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_Flags                                       = 0x88;  // flags32. [Processed=0, Available=1, Has Valid Budgets (Really)=2, Manual Resource Creation=3, Keep Raw Geometry=4, Don't Use Compressed Vertex Positions=5]
    namespace Meshes
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x8C;
        constexpr std::size_t k_EntrySize = 0x5C;

        namespace Parts
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x0;
            constexpr std::size_t k_EntrySize = 0x18;

            constexpr std::size_t k_RenderMaterialIndex                         = 0x0;  // int16.
            constexpr std::size_t k_TransparentSortingIndex                     = 0x2;  // int16.
            constexpr std::size_t k_IndexStart                                  = 0x4;  // uint32.
            constexpr std::size_t k_IndexCount                                  = 0x8;  // uint32.
            constexpr std::size_t k_SubpartStart                                = 0xC;  // int16.
            constexpr std::size_t k_SubpartCount                                = 0xE;  // uint16.
            constexpr std::size_t k_PartType                                    = 0x10;  // int8.
            constexpr std::size_t k_SpecializedRender                           = 0x11;  // enum8. [None=0x0, Fail=0x1, Fur=0x2, Fur Stencil=0x3, Decal=0x4, Shield=0x5, Water=0x6, Lightmap Only=0x7, Hologram=0x8]
            constexpr std::size_t k_PartFlags                                   = 0x12;  // flags16. [Is Water Surface=0, Per Vertex Lightmap Part=1, Debug Flag Instance Part=2, Subparts Has Uberlights Info=3, Draw Cull Distance Medium=4, Draw Cull Distance Close=5, Draw Cull Rendering Shields=6, Cannot Single Pass Render=7, Is Transparent=8, Cannot Two Pass=9, Transparent Should Output Depth For DOF=10, Do Not Include In Static Lightmap=11, Do Not Include In PVS Generation=12, Draw Cull Rendering Active Camo=13]
            constexpr std::size_t k_BudgetVertexCount                           = 0x14;  // uint16.
            constexpr std::size_t k_Tessellation                                = 0x16;  // enum16. [None=0x0, Fixed x4 Faces=0x1, Fixed x9 Faces=0x2, Fixed x36 Faces=0x3]

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace Subparts
        {
            // Array data.
            constexpr std::size_t k_Base      = 0xC;
            constexpr std::size_t k_EntrySize = 0x10;

            constexpr std::size_t k_IndexStart                                  = 0x0;  // uint32.
            constexpr std::size_t k_IndexCount                                  = 0x4;  // uint32.
            constexpr std::size_t k_PartIndex                                   = 0x8;  // int16.
            constexpr std::size_t k_BudgetVertexCount                           = 0xA;  // uint16.
            constexpr std::size_t k_AnalyticalLightIndex                        = 0xC;  // uint32.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        constexpr std::size_t k_VertexBufferIndex1                          = 0x18;  // int16.
        constexpr std::size_t k_VertexBufferIndex2                          = 0x1A;  // int16.
        constexpr std::size_t k_VertexBufferIndex3                          = 0x1C;  // int16.
        constexpr std::size_t k_VertexBufferIndex4                          = 0x1E;  // int16.
        constexpr std::size_t k_VertexBufferIndex5                          = 0x20;  // int16.
        constexpr std::size_t k_VertexBufferIndex6                          = 0x22;  // int16.
        constexpr std::size_t k_VertexBufferIndex7                          = 0x24;  // int16.
        constexpr std::size_t k_VertexBufferIndex8                          = 0x26;  // int16.
        constexpr std::size_t k_IndexBufferIndex                            = 0x28;  // int16.
        constexpr std::size_t k_IndexBufferTessellationIndex                = 0x2A;  // int16.
        constexpr std::size_t k_MeshFlags                                   = 0x2C;  // flags16. [Mesh Has Vertex Color=0, Use Region Index For Sorting=1, Use Vertex Buffers For Indices=2, Mesh Has Per-Instance Lighting (Do Not Modify)=3, Mesh Is Unindexed (Do Not Modify)=4, Subpart Were Merged=5, Mesh Has Fur=6, Mesh Has Decal=7, Mesh Doesn't Use Compressed Position=8, Use Uncompressed Vertex Format=9, Bit 10=10, Bit 11=11, Bit 12=12, Bit 13=13, Bit 14=14, Bit 15=15]
        constexpr std::size_t k_RigidNodeIndex                              = 0x2E;  // int8.
        constexpr std::size_t k_VertexType                                  = 0x2F;  // enum8. [World=0x0, Rigid=0x1, Skinned=0x2, Particle Model=0x3, Flat World=0x4, Flat Rigid=0x5, Flat Skinned=0x6, Screen=0x7, Debug=0x8, Transparent=0x9, Particle=0xA, Contrail=0xB, Light Volume=0xC, Chud Simple=0xD, Chud Fancy=0xE, Decorator=0xF, Tiny Position=0x10, Patchy Fog=0x11, Water=0x12, Ripple=0x13, Implicit=0x14, Beam=0x15, World Tessellated=0x16, Rigid Tessellated=0x17, Skinned Tessellated=0x18, Shader Cache=0x19, Structure Instance Imposter=0x1A, Object Imposter=0x1B, Rigid Compressed=0x1C, Skinned Compressed=0x1D, Light Volume Precompiled=0x1E]
        constexpr std::size_t k_PrtType                                     = 0x30;  // enum8. [None=0x0, Ambient=0x1, Linear=0x2, Quadratic=0x3]
        constexpr std::size_t k_LightingPolicy                              = 0x31;  // enum8. [Vertex Color=0x0, Single Probe=0x1, PRT Ambient=0x2]
        constexpr std::size_t k_IndexBufferType                             = 0x32;  // enum8. [Point List=0x0, Line List=0x1, Line Strip=0x2, Triangle List=0x3, Triangle Fan=0x4, Triangle Strip=0x5]
        constexpr std::size_t k_Unknown                                     = 0x33;  // int8.
        namespace InstanceBuckets
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x34;
            constexpr std::size_t k_EntrySize = 0x10;

            constexpr std::size_t k_MeshIndex                                   = 0x0;  // int16.
            constexpr std::size_t k_DefinitionIndex                             = 0x2;  // int16.
            namespace Instances
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x4;
                constexpr std::size_t k_EntrySize = 0x2;

                constexpr std::size_t k_InstanceIndex                               = 0x0;  // int16.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }


            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace WaterIndicesStart
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x40;
            constexpr std::size_t k_EntrySize = 0x2;

            constexpr std::size_t k_Short                                       = 0x0;  // int16.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        constexpr std::size_t k_BoundingRadius                              = 0x4C;  // float32.
        constexpr std::size_t k_BoundingOffset                              = 0x50;  // point3.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace CompressionInfo
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x98;
        constexpr std::size_t k_EntrySize = 0x34;

        constexpr std::size_t k_CompressionFlags                            = 0x0;  // flags16. [Compressed Position=0, Compressed Texcoord=1, Compression Optimized=2]
        constexpr std::size_t k_Unknown                                     = 0x2;  // int16.
        constexpr std::size_t k_PositionBoundsX                             = 0x4;  // rangef.
        constexpr std::size_t k_PositionBoundsY                             = 0xC;  // rangef.
        constexpr std::size_t k_PositionBoundsZ                             = 0x14;  // rangef.
        constexpr std::size_t k_TexcoordBoundsX                             = 0x1C;  // rangef.
        constexpr std::size_t k_TexcoordBoundsY                             = 0x24;  // rangef.
        constexpr std::size_t k_Unknown_2                                   = 0x2C;  // float32.
        constexpr std::size_t k_Unknown_3                                   = 0x30;  // float32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace PartSortingPosition
    {
        // Array data.
        constexpr std::size_t k_Base      = 0xA4;
        constexpr std::size_t k_EntrySize = 0x30;

        constexpr std::size_t k_Plane                                       = 0x0;  // plane3.
        constexpr std::size_t k_Position                                    = 0x10;  // point3.
        constexpr std::size_t k_Radius                                      = 0x1C;  // float32.
        constexpr std::size_t k_NodeIndex1                                  = 0x20;  // int8.
        constexpr std::size_t k_NodeIndex2                                  = 0x21;  // int8.
        constexpr std::size_t k_NodeIndex3                                  = 0x22;  // int8.
        constexpr std::size_t k_NodeIndex4                                  = 0x23;  // int8.
        constexpr std::size_t k_NodeWeight1                                 = 0x24;  // float32.
        constexpr std::size_t k_NodeWeight2                                 = 0x28;  // float32.
        constexpr std::size_t k_NodeWeight3                                 = 0x2C;  // float32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace UserData
    {
        // Array data.
        constexpr std::size_t k_Base      = 0xB0;
        constexpr std::size_t k_EntrySize = 0x18;

        constexpr std::size_t k_DataType                                    = 0x0;  // enum8. [PRT Info=0x0]
        constexpr std::size_t k_DataCount                                   = 0x1;  // int8.
        constexpr std::size_t k_DataSize                                    = 0x2;  // uint16.
        constexpr std::size_t k_UserData                                    = 0x4;  // DataReference.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace PerMeshTemporary
    {
        // Array data.
        constexpr std::size_t k_Base      = 0xBC;
        constexpr std::size_t k_EntrySize = 0x54;

        namespace RawVertices
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x0;
            constexpr std::size_t k_EntrySize = 0x60;

            constexpr std::size_t k_Position                                    = 0x0;  // point3.
            constexpr std::size_t k_Texcoord                                    = 0xC;  // point2.
            constexpr std::size_t k_Normal                                      = 0x14;  // point3.
            constexpr std::size_t k_Binormal                                    = 0x20;  // point3.
            constexpr std::size_t k_Tangent                                     = 0x2C;  // point3.
            constexpr std::size_t k_LightmapTexcoord                            = 0x38;  // point2.
            constexpr std::size_t k_NodeIndex1                                  = 0x40;  // uint8.
            constexpr std::size_t k_NodeIndex2                                  = 0x41;  // uint8.
            constexpr std::size_t k_NodeIndex3                                  = 0x42;  // uint8.
            constexpr std::size_t k_NodeIndex4                                  = 0x43;  // uint8.
            constexpr std::size_t k_NodeWeight1                                 = 0x44;  // float32.
            constexpr std::size_t k_NodeWeight2                                 = 0x48;  // float32.
            constexpr std::size_t k_NodeWeight3                                 = 0x4C;  // float32.
            constexpr std::size_t k_NodeWeight4                                 = 0x50;  // float32.
            constexpr std::size_t k_VertexColor                                 = 0x54;  // point3.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace RawIndices
        {
            // Array data.
            constexpr std::size_t k_Base      = 0xC;
            constexpr std::size_t k_EntrySize = 0x2;

            constexpr std::size_t k_Short                                       = 0x0;  // int16.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace RawIndices32
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x18;
            constexpr std::size_t k_EntrySize = 0x4;

            constexpr std::size_t k_Int                                         = 0x0;  // int32.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace RawWaterData
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x24;
            constexpr std::size_t k_EntrySize = 0x18;

            namespace RawWaterIndices
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x0;
                constexpr std::size_t k_EntrySize = 0x2;

                constexpr std::size_t k_Short                                       = 0x0;  // int16.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }

            namespace RawWaterVertices
            {
                // Array data.
                constexpr std::size_t k_Base      = 0xC;
                constexpr std::size_t k_EntrySize = 0x8;

                constexpr std::size_t k_BaseTexcoord                                = 0x0;  // point2.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }


            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace RawImposterData
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x30;
            constexpr std::size_t k_EntrySize = 0x4C;

            constexpr std::size_t k_Diffuse                                     = 0x0;  // colorf.
            constexpr std::size_t k_Ambient                                     = 0xC;  // colorf.
            constexpr std::size_t k_Specular                                    = 0x18;  // colorf.
            constexpr std::size_t k_Shininess                                   = 0x24;  // float32.
            constexpr std::size_t k_Alpha                                       = 0x28;  // float32.
            constexpr std::size_t k_ChangeColorTintOfDiffuse                    = 0x2C;  // colorf.
            constexpr std::size_t k_ChangeColorTintOfSpecular                   = 0x3C;  // colorf.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace RawInstanceImposterVerts
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x3C;
            constexpr std::size_t k_EntrySize = 0x14;

            constexpr std::size_t k_Position                                    = 0x0;  // vector3.
            constexpr std::size_t k_Color                                       = 0xC;  // uint32.
            constexpr std::size_t k_HdrScaler                                   = 0x10;  // float32.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        constexpr std::size_t k_PerVertexLightingVertexSize                 = 0x48;  // int32.
        constexpr std::size_t k_ParameterizedTextureWidth                   = 0x4C;  // int16.
        constexpr std::size_t k_ParameterizedTextureHeight                  = 0x4E;  // int16.
        constexpr std::size_t k_Flags                                       = 0x50;  // flags32. [Indices Are Triangle Strips=0, Indices Are Triangle Lists=1, Indices Are Quad Lists=2]

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_Unknown                                     = 0xC8;  // undefined.
    constexpr std::size_t k_Unknown_2                                   = 0xCC;  // undefined.
    constexpr std::size_t k_Unknown_3                                   = 0xD0;  // undefined.
    namespace PerMeshNodeMap
    {
        // Array data.
        constexpr std::size_t k_Base      = 0xD4;
        constexpr std::size_t k_EntrySize = 0xC;

        namespace NodeMap
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x0;
            constexpr std::size_t k_EntrySize = 0x1;

            constexpr std::size_t k_NodeIndex                                   = 0x0;  // int8.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }


        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace PerMeshSubpartVisibility
    {
        // Array data.
        constexpr std::size_t k_Base      = 0xE0;
        constexpr std::size_t k_EntrySize = 0xC;

        namespace BoundingSphere
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x0;
            constexpr std::size_t k_EntrySize = 0x30;

            constexpr std::size_t k_Plane                                       = 0x0;  // plane3.
            constexpr std::size_t k_Position                                    = 0x10;  // point3.
            constexpr std::size_t k_Radius                                      = 0x1C;  // float32.
            constexpr std::size_t k_NodeIndex1                                  = 0x20;  // uint8.
            constexpr std::size_t k_NodeIndex2                                  = 0x21;  // uint8.
            constexpr std::size_t k_NodeIndex3                                  = 0x22;  // uint8.
            constexpr std::size_t k_NodeIndex4                                  = 0x23;  // uint8.
            constexpr std::size_t k_NodeWeight1                                 = 0x24;  // float32.
            constexpr std::size_t k_NodeWeight2                                 = 0x28;  // float32.
            constexpr std::size_t k_NodeWeight3                                 = 0x2C;  // float32.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }


        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_BlockHere1                                  = 0xEC;  // uint32.
    constexpr std::size_t k_BlockHere1_2                                = 0xF0;  // uint32.
    constexpr std::size_t k_BlockHere1_3                                = 0xF4;  // uint32.
    constexpr std::size_t k_BlockHere2                                  = 0xF8;  // uint32.
    constexpr std::size_t k_BlockHere2_2                                = 0xFC;  // uint32.
    constexpr std::size_t k_BlockHere2_3                                = 0x100;  // uint32.
    namespace PerInstanceLightmapTexcoords
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x104;
        constexpr std::size_t k_EntrySize = 0x2;

        constexpr std::size_t k_VertexBufferIndex                           = 0x0;  // int16.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace WaterBoundingBox
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x110;
        constexpr std::size_t k_EntrySize = 0x1C;

        constexpr std::size_t k_MeshIndex                                   = 0x0;  // int16.
        constexpr std::size_t k_PartIndex                                   = 0x2;  // int16.
        constexpr std::size_t k_PositionBounds0                             = 0x4;  // point3.
        constexpr std::size_t k_PositionBounds1                             = 0x10;  // point3.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_ZoneAssetDatum                              = 0x11C;  // datum.
    constexpr std::size_t k_UselessPadding                              = 0x120;  // int32.
    namespace ConstantBufferInterop
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x124;
        constexpr std::size_t k_EntrySize = 0xC;

        constexpr std::size_t k_InteropPointer                              = 0x0;  // uint32.
        constexpr std::size_t k_Unknown                                     = 0x4;  // undefined.
        constexpr std::size_t k_UselessPadding                              = 0x8;  // int32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace Unknown
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x130;
        constexpr std::size_t k_EntrySize = 0x144;

        constexpr std::size_t k_Unknown                                     = 0x0;  // undefined.
        constexpr std::size_t k_Unknown_2                                   = 0x4;  // undefined.
        constexpr std::size_t k_Unknown_3                                   = 0x8;  // undefined.
        constexpr std::size_t k_Unknown_4                                   = 0xC;  // undefined.
        constexpr std::size_t k_Unknown_5                                   = 0x10;  // undefined.
        constexpr std::size_t k_Unknown_6                                   = 0x14;  // undefined.
        constexpr std::size_t k_Unknown_7                                   = 0x18;  // undefined.
        constexpr std::size_t k_Unknown_8                                   = 0x1C;  // undefined.
        constexpr std::size_t k_Unknown_9                                   = 0x20;  // undefined.
        constexpr std::size_t k_Unknown_10                                  = 0x24;  // undefined.
        constexpr std::size_t k_Unknown_11                                  = 0x28;  // undefined.
        constexpr std::size_t k_Unknown_12                                  = 0x2C;  // undefined.
        constexpr std::size_t k_Unknown_13                                  = 0x30;  // undefined.
        constexpr std::size_t k_Unknown_14                                  = 0x34;  // undefined.
        constexpr std::size_t k_Unknown_15                                  = 0x38;  // undefined.
        constexpr std::size_t k_Unknown_16                                  = 0x3C;  // undefined.
        constexpr std::size_t k_Unknown_17                                  = 0x40;  // undefined.
        constexpr std::size_t k_Unknown_18                                  = 0x44;  // undefined.
        constexpr std::size_t k_Unknown_19                                  = 0x48;  // undefined.
        constexpr std::size_t k_Unknown_20                                  = 0x4C;  // undefined.
        constexpr std::size_t k_Unknown_21                                  = 0x50;  // undefined.
        constexpr std::size_t k_Unknown_22                                  = 0x54;  // undefined.
        constexpr std::size_t k_Unknown_23                                  = 0x58;  // undefined.
        constexpr std::size_t k_Unknown_24                                  = 0x5C;  // undefined.
        constexpr std::size_t k_Unknown_25                                  = 0x60;  // undefined.
        constexpr std::size_t k_Unknown_26                                  = 0x64;  // undefined.
        constexpr std::size_t k_Unknown_27                                  = 0x68;  // undefined.
        constexpr std::size_t k_Unknown_28                                  = 0x6C;  // undefined.
        constexpr std::size_t k_Unknown_29                                  = 0x70;  // undefined.
        constexpr std::size_t k_Unknown_30                                  = 0x74;  // undefined.
        constexpr std::size_t k_Unknown_31                                  = 0x78;  // undefined.
        constexpr std::size_t k_Unknown_32                                  = 0x7C;  // undefined.
        constexpr std::size_t k_Unknown_33                                  = 0x80;  // undefined.
        constexpr std::size_t k_Unknown_34                                  = 0x84;  // undefined.
        constexpr std::size_t k_Unknown_35                                  = 0x88;  // undefined.
        constexpr std::size_t k_Unknown_36                                  = 0x8C;  // undefined.
        constexpr std::size_t k_Unknown_37                                  = 0x90;  // undefined.
        constexpr std::size_t k_Unknown_38                                  = 0x94;  // undefined.
        constexpr std::size_t k_Unknown_39                                  = 0x98;  // undefined.
        constexpr std::size_t k_Unknown_40                                  = 0x9C;  // undefined.
        constexpr std::size_t k_Unknown_41                                  = 0xA0;  // undefined.
        constexpr std::size_t k_Unknown_42                                  = 0xA4;  // undefined.
        constexpr std::size_t k_Unknown_43                                  = 0xA8;  // undefined.
        constexpr std::size_t k_Unknown_44                                  = 0xAC;  // undefined.
        constexpr std::size_t k_Unknown_45                                  = 0xB0;  // undefined.
        constexpr std::size_t k_Unknown_46                                  = 0xB4;  // undefined.
        constexpr std::size_t k_Unknown_47                                  = 0xB8;  // undefined.
        constexpr std::size_t k_Unknown_48                                  = 0xBC;  // undefined.
        constexpr std::size_t k_Unknown_49                                  = 0xC0;  // undefined.
        constexpr std::size_t k_Unknown_50                                  = 0xC4;  // undefined.
        constexpr std::size_t k_Unknown_51                                  = 0xC8;  // undefined.
        constexpr std::size_t k_Unknown_52                                  = 0xCC;  // undefined.
        constexpr std::size_t k_Unknown_53                                  = 0xD0;  // undefined.
        constexpr std::size_t k_Unknown_54                                  = 0xD4;  // undefined.
        constexpr std::size_t k_Unknown_55                                  = 0xD8;  // undefined.
        constexpr std::size_t k_Unknown_56                                  = 0xDC;  // undefined.
        constexpr std::size_t k_Unknown_57                                  = 0xE0;  // undefined.
        constexpr std::size_t k_Unknown_58                                  = 0xE4;  // undefined.
        constexpr std::size_t k_Unknown_59                                  = 0xE8;  // undefined.
        constexpr std::size_t k_Unknown_60                                  = 0xEC;  // undefined.
        constexpr std::size_t k_Unknown_61                                  = 0xF0;  // undefined.
        constexpr std::size_t k_Unknown_62                                  = 0xF4;  // undefined.
        constexpr std::size_t k_Unknown_63                                  = 0xF8;  // undefined.
        constexpr std::size_t k_Unknown_64                                  = 0xFC;  // undefined.
        constexpr std::size_t k_Unknown_65                                  = 0x100;  // undefined.
        constexpr std::size_t k_Unknown_66                                  = 0x104;  // undefined.
        constexpr std::size_t k_Unknown_67                                  = 0x108;  // undefined.
        constexpr std::size_t k_Unknown_68                                  = 0x10C;  // undefined.
        constexpr std::size_t k_Unknown_69                                  = 0x110;  // undefined.
        constexpr std::size_t k_Unknown_70                                  = 0x114;  // undefined.
        constexpr std::size_t k_Unknown_71                                  = 0x118;  // undefined.
        constexpr std::size_t k_Unknown_72                                  = 0x11C;  // undefined.
        constexpr std::size_t k_Unknown_73                                  = 0x120;  // undefined.
        constexpr std::size_t k_Unknown_74                                  = 0x124;  // undefined.
        constexpr std::size_t k_Unknown_75                                  = 0x128;  // undefined.
        constexpr std::size_t k_Unknown_76                                  = 0x12C;  // undefined.
        constexpr std::size_t k_Unknown_77                                  = 0x130;  // undefined.
        constexpr std::size_t k_Unknown_78                                  = 0x134;  // undefined.
        constexpr std::size_t k_Unknown_79                                  = 0x138;  // undefined.
        constexpr std::size_t k_Unknown_80                                  = 0x13C;  // undefined.
        constexpr std::size_t k_Unknown_81                                  = 0x140;  // int16.
        constexpr std::size_t k_Unknown_82                                  = 0x142;  // int16.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace InstancedGeometryInstances
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x13C;
        constexpr std::size_t k_EntrySize = 0xA0;

        constexpr std::size_t k_Scale                                       = 0x0;  // float32.
        constexpr std::size_t k_Forward                                     = 0x4;  // vector3.
        constexpr std::size_t k_Left                                        = 0x10;  // vector3.
        constexpr std::size_t k_Up                                          = 0x1C;  // vector3.
        constexpr std::size_t k_Position                                    = 0x28;  // point3.
        constexpr std::size_t k_InstanceDefinitionIndex                     = 0x34;  // int16.
        constexpr std::size_t k_Flags                                       = 0x36;  // flags16. [Not In Lightprobes=0, Render Only=1, Does Not Block Aoe Damage=2, Collidable=3, Decal Spacing=4, Rain Blocker=5, Vertical Rain Sheet=6, Outside Map=7, Seam Colliding=8, (Mostly) Planar=9, Remove From Shadow Geometry=10, Cinema Only=11, Exclude From Cinema=12, Disallow Object Lighting Samples=13, Bit 14=14, Bit 15=15]
        constexpr std::size_t k_MeshIndex                                   = 0x38;  // int16.
        constexpr std::size_t k_CompressionIndex                            = 0x3A;  // int16.
        constexpr std::size_t k_SeamBitVector0                              = 0x3C;  // int32.
        constexpr std::size_t k_SeamBitVector1                              = 0x40;  // int32.
        constexpr std::size_t k_SeamBitVector2                              = 0x44;  // int32.
        constexpr std::size_t k_SeamBitVector3                              = 0x48;  // int32.
        constexpr std::size_t k_BoundsX                                     = 0x4C;  // rangef.
        constexpr std::size_t k_BoundsY                                     = 0x54;  // rangef.
        constexpr std::size_t k_BoundsZ                                     = 0x5C;  // rangef.
        constexpr std::size_t k_WorldBoundingSphereCenter                   = 0x64;  // point3.
        constexpr std::size_t k_WorldBoundingSphereRadius                   = 0x70;  // float32.
        constexpr std::size_t k_ImposterTransitionCompleteDistance          = 0x74;  // float32.
        constexpr std::size_t k_ImposterBrightness                          = 0x78;  // float32.
        constexpr std::size_t k_PathfindingPolicy                           = 0x7C;  // enum8. [Cut-Out=0x0, Static=0x1, None=0x2]
        constexpr std::size_t k_LightmappingPolicy                          = 0x7D;  // enum8. [Per-Pixel Shared=0x0, Per-Vertex=0x1, Single-Probe=0x2, Exclude=0x3, Per-Pixel Ao=0x4, Per-Vertex Ao=0x5]
        constexpr std::size_t k_ImposterPolicy                              = 0x7E;  // enum8. [Polygon Default=0x0, Polygon High=0x1, Cards Medium=0x2, Cards High=0x3, None=0x4, Rainbow Box (Runtime Only)=0x5]
        constexpr std::size_t k_Unknown                                     = 0x7F;  // int8.
        constexpr std::size_t k_LightmapResolutionScale                     = 0x80;  // float32.
        constexpr std::size_t k_Unknown_2                                   = 0x84;  // undefined.
        constexpr std::size_t k_Unknown_3                                   = 0x88;  // undefined.
        constexpr std::size_t k_Unknown_4                                   = 0x8C;  // undefined.
        constexpr std::size_t k_Unknown_5                                   = 0x90;  // undefined.
        constexpr std::size_t k_Unknown_6                                   = 0x94;  // undefined.
        constexpr std::size_t k_Unknown_7                                   = 0x98;  // undefined.
        constexpr std::size_t k_Name                                        = 0x9C;  // StringID.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace Materials
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x148;
        constexpr std::size_t k_EntrySize = 0x2C;

        constexpr std::size_t k_RenderMethod                                = 0x0;  // TagReference.
        constexpr std::size_t k_ImportedMaterialIndex                       = 0x10;  // int32.
        constexpr std::size_t k_LightmapResolutionScale                     = 0x14;  // float32.
        constexpr std::size_t k_LightmapAdditiveTransparencyColor           = 0x18;  // int32.
        constexpr std::size_t k_LightmapTranslucencyTintColor               = 0x1C;  // int32.
        constexpr std::size_t k_LightmapAnalyticalLightAbsorb               = 0x20;  // float32.
        constexpr std::size_t k_LightmapNormalLightAbsorb                   = 0x24;  // float32.
        constexpr std::size_t k_LightmapFlags                               = 0x28;  // flags8. [Ignore Default Resolution Scale=0, Transparency Override=1, Lighting From Both Sides=2, Version 1=3]
        constexpr std::size_t k_BreakableSurfaceIndex                       = 0x29;  // int8.
        constexpr std::size_t k_LightmapChartGroupIndex                     = 0x2A;  // int16.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace RainBlockerMoppCodes
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x154;
        constexpr std::size_t k_EntrySize = 0x60;

        constexpr std::size_t k_RuntimeCodePointer                          = 0x0;  // uint64.
        constexpr std::size_t k_Size                                        = 0x8;  // int16.
        constexpr std::size_t k_Count                                       = 0xA;  // int16.
        constexpr std::size_t k_Unknown                                     = 0xC;  // undefined.
        constexpr std::size_t k_UserData                                    = 0x10;  // uint64.
        constexpr std::size_t k_Type                                        = 0x18;  // int32.
        constexpr std::size_t k_Unknown_2                                   = 0x1C;  // undefined.
        constexpr std::size_t k_V                                           = 0x20;  // vector3.
        constexpr std::size_t k_WV                                          = 0x2C;  // float32.
        constexpr std::size_t k_RuntimeMoppCodePointer                      = 0x30;  // uint64.
        constexpr std::size_t k_DataSize                                    = 0x38;  // int32.
        constexpr std::size_t k_DataCapacity                                = 0x3C;  // uint32.
        constexpr std::size_t k_BuildType                                   = 0x40;  // int8.
        constexpr std::size_t k_Unknown_3                                   = 0x41;  // int8.
        constexpr std::size_t k_Unknown_4                                   = 0x42;  // int16.
        constexpr std::size_t k_Unknown_5                                   = 0x44;  // undefined.
        constexpr std::size_t k_Unknown_6                                   = 0x48;  // undefined.
        constexpr std::size_t k_Unknown_7                                   = 0x4C;  // undefined.
        namespace MoppData
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x50;
            constexpr std::size_t k_EntrySize = 0x1;

            constexpr std::size_t k_Data                                        = 0x0;  // uint8.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        constexpr std::size_t k_MoppBuildType                               = 0x5C;  // int8.
        constexpr std::size_t k_Unknown_8                                   = 0x5D;  // int8.
        constexpr std::size_t k_Unknown_9                                   = 0x5E;  // int16.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

}
