// Auto-generated by TagTranspiler (GenerateStructure.py)
// Source XML: phmo.xml
// Root struct size: 0x19c

export module Map.Tag.Type:Phmo.Structure;

import Map.Reader.Type;
import std;

namespace
{
    namespace MapStructure = Map::Reader::Type::Structure;
}

#pragma pack(push, 1)

export namespace Map::Tag::Type::Phmo::Structure
{
    // Entry size: 0x18
    struct Phmo_DampedSpringMotorsEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        float        MaximumForce;  // 0x4  float32. | 0 defaults to k_real_max
        float        MinimumForce;  // 0x8  float32. | 0 defaults to maximum force. In general you should leave this alone unless working on ragdolls or something like them
        float        SpringK;  // 0xC  float32.
        float        Damping;  // 0x10  float32. | 0 means default daming of 1.0f
        float        InitialPosition;  // 0x14  float32.
    };
    static_assert(sizeof(Phmo_DampedSpringMotorsEntry) == 0x18, "Phmo_DampedSpringMotorsEntry size mismatch");

    // Entry size: 0x20
    struct Phmo_PositionMotorsEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        float        MaximumForce;  // 0x4  float32.
        float        MinimumForce;  // 0x8  float32. | 0 defaults to maximum force. In general you should leave this alone unless working on ragdolls or something like them
        float        Tau;  // 0xC  float32. | from 0-1. relative stiffness
        float        Damping;  // 0x10  float32. | from 0-1
        float        ProportionRecoverVelocity;  // 0x14  float32. | fraction of recover velocity used. 0 defaults to 1
        float        ConstantRecoverVelocity;  // 0x18  float32. | velocity used to recover when errors happen. in degrees per second
        float        InitialPosition;  // 0x1C  float32.
    };
    static_assert(sizeof(Phmo_PositionMotorsEntry) == 0x20, "Phmo_PositionMotorsEntry size mismatch");

    // Entry size: 0x6C
    struct Phmo_PhantomTypesEntry
    {
        std::uint32_t Flags;  // 0x0  flags32. [Generates Effects=0, Use Acceleration As Force=1, Negates Gravity=2, Ignores Players=3, Ignores Non-Players=4, Ignores Bipeds=5, Ignores Vehicles=6, Ignores Weapons=7, Ignores Equipment=8, Ignores Terminals=9, Ignores Projectiles=10, Ignores Scenery=11, Ignores Machines=12, Ignores Controls=13, Ignores Sound Scenery=14, Ignores Crates=15, ...(32 total)]
        float        BrittleTimer;  // 0x4  float32. | objects in this phantom volume will be set to brittle collision damage for this amount of time.
        std::uint8_t MinimumSize;  // 0x8  enum8. [Default=0x0, Tiny=0x1, Small=0x2, Medium=0x3, Large=0x4, Huge=0x5, Extra Huge=0x6]
        std::uint8_t MaximumSize;  // 0x9  enum8. [Default=0x0, Tiny=0x1, Small=0x2, Medium=0x3, Large=0x4, Huge=0x5, Extra Huge=0x6]
        std::int16_t Unknown;  // 0xA  int16.
        std::uint32_t MarkerName;  // 0xC  stringid. | you don't need this if you're just generating effects. If empty it defaults to the up of the object
        std::uint32_t AlignmentMarkerName;  // 0x10  stringid. | you don't need this if you're just generating effects. If empty it defaults to "marker name"
        std::uint8_t  _pad_0x14[0x4];  // undefined.
        std::uint8_t  _pad_0x18[0x4];  // undefined.
        float        HookesLawE;  // 0x1C  float32. | 0 if you don't want this to behave like spring. 1 is a good starting point if you do.
        float        LinearDeadRadius;  // 0x20  float32. | radius from linear motion origin in which acceleration is dead.
        float        CenterAcceleration;  // 0x24  float32. | motion towards marker position
        float        CenterMaximumVelocity;  // 0x28  float32. | motion towards marker position
        float        AxisAcceleration;  // 0x2C  float32. | motion towards marker axis, such that object is on the axis
        float        AxisMaximumVelocity;  // 0x30  float32. | motion towards marker axis, such that object is on the axis
        float        DirectionAcceleration;  // 0x34  float32. | motion along marker direction
        float        DirectionMaximumVelocity;  // 0x38  float32. | motion along marker direction
        float        OrbitAcceleration;  // 0x3C  float32. | negative values spin the opposite direction from positive ones
        float        OrbitMaximumVelocity;  // 0x40  float32.
        std::uint8_t  _pad_0x44[0x4];  // undefined.
        std::uint8_t  _pad_0x48[0x4];  // undefined.
        std::uint8_t  _pad_0x4C[0x4];  // undefined.
        std::uint8_t  _pad_0x50[0x4];  // undefined.
        std::uint8_t  _pad_0x54[0x4];  // undefined.
        float        AlignmentHookesLawE;  // 0x58  float32. | 0 if you don't want this to behave like spring. 1 is a good starting point if you do.
        float        AlignmentAcceleration;  // 0x5C  float32. | align objects in the phantom with the marker
        float        AlignmentMaximumVelocity;  // 0x60  float32. | align objects in the phantom with the marker
        std::uint8_t  _pad_0x64[0x4];  // undefined.
        std::uint8_t  _pad_0x68[0x4];  // undefined.
    };
    static_assert(sizeof(Phmo_PhantomTypesEntry) == 0x6C, "Phmo_PhantomTypesEntry size mismatch");

    // Entry size: 0x2
    struct Phmo_PoweredChains_NodesEntry
    {
        std::int16_t NodeIndex;  // 0x0  int16.
    };
    static_assert(sizeof(Phmo_PoweredChains_NodesEntry) == 0x2, "Phmo_PoweredChains_NodesEntry size mismatch");

    // Entry size: 0x10
    struct Phmo_PoweredChains_ConstraintsEntry
    {
        std::uint16_t ConstraintType;  // 0x0  enum16. [Hinge=0x0, Limited Hinge=0x1, Ragdoll=0x2, Stiff Spring=0x3, Ball And Socket=0x4, Prismatic=0x5, Powered Chain=0x6]
        std::int16_t ConstraintIndex;  // 0x2  int16.
        std::uint16_t MotorType;  // 0x4  enum16. [None=0x0, Damped Spring=0x1, Stongest Force=0x2]
        std::int16_t MotorIndex;  // 0x6  int16.
        std::uint16_t MotorType_2;  // 0x8  enum16. [None=0x0, Damped Spring=0x1, Stongest Force=0x2]
        std::int16_t MotorIndex_2;  // 0xA  int16.
        std::uint16_t MotorType_3;  // 0xC  enum16. [None=0x0, Damped Spring=0x1, Stongest Force=0x2]
        std::int16_t MotorIndex_3;  // 0xE  int16.
    };
    static_assert(sizeof(Phmo_PoweredChains_ConstraintsEntry) == 0x10, "Phmo_PoweredChains_ConstraintsEntry size mismatch");

    // Entry size: 0x18
    struct Phmo_PoweredChainsEntry
    {
        // -> Phmo_PoweredChains_NodesEntry[]
        MapStructure::Tag::Block   Nodes;  // 0x0  tagblock.
        // -> Phmo_PoweredChains_ConstraintsEntry[]
        MapStructure::Tag::Block   Constraints;  // 0xC  tagblock.
    };
    static_assert(sizeof(Phmo_PoweredChainsEntry) == 0x18, "Phmo_PoweredChainsEntry size mismatch");

    // Entry size: 0xC
    struct Phmo_NodeEdges_Constraints_RagdollMotorsEntry
    {
        std::uint16_t MotorType;  // 0x0  enum16. [None=0x0, Damped Spring=0x1, Stongest Force=0x2]
        std::int16_t MotorIndex;  // 0x2  int16.
        std::uint16_t MotorType_2;  // 0x4  enum16. [None=0x0, Damped Spring=0x1, Stongest Force=0x2]
        std::int16_t MotorIndex_2;  // 0x6  int16.
        std::uint16_t MotorType_3;  // 0x8  enum16. [None=0x0, Damped Spring=0x1, Stongest Force=0x2]
        std::int16_t MotorIndex_3;  // 0xA  int16.
    };
    static_assert(sizeof(Phmo_NodeEdges_Constraints_RagdollMotorsEntry) == 0xC, "Phmo_NodeEdges_Constraints_RagdollMotorsEntry size mismatch");

    // Entry size: 0x4
    struct Phmo_NodeEdges_Constraints_LimitedHingeMotorsEntry
    {
        std::uint16_t MotorType;  // 0x0  enum16. [None=0x0, Damped Spring=0x1, Stongest Force=0x2]
        std::int16_t MotorIndex;  // 0x2  int16.
    };
    static_assert(sizeof(Phmo_NodeEdges_Constraints_LimitedHingeMotorsEntry) == 0x4, "Phmo_NodeEdges_Constraints_LimitedHingeMotorsEntry size mismatch");

    // Entry size: 0x24
    struct Phmo_NodeEdges_ConstraintsEntry
    {
        std::uint16_t Type;  // 0x0  enum16. [Hinge=0x0, Limited Hinge=0x1, Ragdoll=0x2, Stiff Spring=0x3, Ball And Socket=0x4, Prismatic=0x5, Powered Chain=0x6]
        std::int16_t Index;  // 0x2  int16.
        std::uint32_t Flags;  // 0x4  flags32. [Is Physical Child=0, Is Rigid=1, Disable Effects=2, Not Created Automatically=3, Bit 4=4, Bit 5=5, Bit 6=6, Bit 7=7, Bit 8=8, Bit 9=9, Bit 10=10, Bit 11=11, Bit 12=12, Bit 13=13, Bit 14=14, Bit 15=15, ...(32 total)]
        float        Friction;  // 0x8  float32. | 0 is the default (takes what it was set in max) anything else overrides that value
        // -> Phmo_NodeEdges_Constraints_RagdollMotorsEntry[]
        MapStructure::Tag::Block   RagdollMotors;  // 0xC  tagblock.
        // -> Phmo_NodeEdges_Constraints_LimitedHingeMotorsEntry[]
        MapStructure::Tag::Block   LimitedHingeMotors;  // 0x18  tagblock.
    };
    static_assert(sizeof(Phmo_NodeEdges_ConstraintsEntry) == 0x24, "Phmo_NodeEdges_ConstraintsEntry size mismatch");

    // Entry size: 0x1C
    struct Phmo_NodeEdgesEntry
    {
        std::int16_t NodeAGlobalMaterialIndex;  // 0x0  int16.
        std::int16_t NodeBGlobalMaterialIndex;  // 0x2  int16.
        std::int16_t NodeAIndex;  // 0x4  int16.
        std::int16_t NodeBIndex;  // 0x6  int16.
        // -> Phmo_NodeEdges_ConstraintsEntry[]
        MapStructure::Tag::Block   Constraints;  // 0x8  tagblock.
        std::uint32_t NodeAGlobalMaterialName;  // 0x14  stringid. | if you don't fill this out we will pluck the material from the first primitive, of the first rigid body attached to node a
        std::uint32_t NodeBGlobalMaterialName;  // 0x18  stringid. | if you don't fill this out we will pluck the material from the first primitive, of the first rigid body attached to node b, if node b is none we use whatever material a has
    };
    static_assert(sizeof(Phmo_NodeEdgesEntry) == 0x1C, "Phmo_NodeEdgesEntry size mismatch");

    // Entry size: 0xD0
    struct Phmo_RigidBodiesEntry
    {
        std::int16_t NodeIndex;  // 0x0  int16.
        std::int16_t RegionIndex;  // 0x2  int16.
        std::int16_t PermutationIndex;  // 0x4  int16.
        std::int16_t Unknown;  // 0x6  int16.
        MapStructure::Primitive::Vec3 BoundingSphereOffset;  // 0x8  point3.
        float        BoundingSphereRadius;  // 0x14  float32.
        std::uint16_t Flags;  // 0x18  flags16. [Has No Phantom Power Version=0, Infinite Inertia Tensor=1, Can Use MOPPs=2, Havok Rigid Body=3, Explicit Mass=4, Absolute Center Of Mass=5, Force Keyframed=6, Bit 7=7, Bit 8=8, Bit 9=9, Bit 10=10, Bit 11=11, Bit 12=12, Bit 13=13, Bit 14=14, Bit 15=15]
        std::int16_t NoPhantomPowerAlternativeRigidBodyIndex;  // 0x1A  int16.
        std::uint8_t MotionType;  // 0x1C  enum8. [Sphere=0x0, Stabilized Sphere=0x1, Box=0x2, Stabilized Box=0x3, Keyframed=0x4, Fixed=0x5]
        std::uint8_t ProxyCollisionGroup;  // 0x1D  enum8. [None=0x0, Small Crate=0x1, Crate=0x2, Huge Crate=0x3, Item=0x4, Projectile=0x5, Biped=0x6, Machine=0x7, Early Mover Machine=0x8, Only Collide With Environment=0x9, Tech Art Custom=0xA, Small Expensive Plant=0xB, Ignore Environment=0xC, Huge Vehicle=0xD, Ragdoll=0xE, Super Collidable Ragdoll=0xF, ...(21 total)] | does not affect anything, change the groups in the individual shapes instead.
        std::uint16_t Size;  // 0x1E  enum16. [Default=0x0, Tiny=0x1, Small=0x2, Medium=0x3, Large=0x4, Huge=0x5, Extra Huge=0x6]
        float        InertiaTensorScale;  // 0x20  float32. | 0.0 defaults to 1.0
        MapStructure::Primitive::Vec3 InertiaTensorScale_2;  // 0x24  point3. | 0.0 defaults to 1.0
        float        LinearDamping;  // 0x30  float32. | this goes from 0-10 (10 is really, really high)
        float        AngularDamping;  // 0x34  float32. | this goes from 0-10 (10 is really, really high)
        MapStructure::Primitive::Vec3 CenterOfMassOffset;  // 0x38  vector3.
        float        WaterPhysicsX0;  // 0x44  float32. | x0 value of the water physics Axis-Aligned Bounding Box
        float        WaterPhysicsX1;  // 0x48  float32. | x1 value of the water physics Axis-Aligned Bounding Box
        float        WaterPhysicsY0;  // 0x4C  float32. | y0 value of the water physics Axis-Aligned Bounding Box
        float        WaterPhysicsY1;  // 0x50  float32. | y1 value of the water physics Axis-Aligned Bounding Box
        float        WaterPhysicsZ0;  // 0x54  float32. | z0 value of the water physics Axis-Aligned Bounding Box
        float        WaterPhysicsZ1;  // 0x58  float32. | z1 value of the water physics Axis-Aligned Bounding Box
        std::uint8_t  _pad_0x5C[0x4];  // undefined.
        MapStructure::Primitive::Vec3 CenterOfMass;  // 0x60  vector3.
        float        WCenterOfMass;  // 0x6C  float32.
        MapStructure::Primitive::Vec3 InertiaTensorX;  // 0x70  vector3.
        float        WInertiaTensorX;  // 0x7C  float32.
        MapStructure::Primitive::Vec3 InertiaTensorY;  // 0x80  vector3.
        float        WInertiaTensorY;  // 0x8C  float32.
        MapStructure::Primitive::Vec3 InertiaTensorZ;  // 0x90  vector3.
        float        WInertiaTensorZ;  // 0x9C  float32.
        std::uint32_t CollisionGroupMask;  // 0xA0  flags32. [Everything=0, Environment Default=1, Environment Only=2, Small Crate=3, Crate=4, Huge Crate=5, Item=6, Projectile=7, Machine=8, Early Mover Machine=9, Creature=10, Biped=11, Dead Biped=12, Super Collidable Ragdoll=13, Ragdoll=14, Vehicle=15, ...(27 total)]
        std::uint8_t  _pad_0xA4[0x4];  // undefined.
        std::uint16_t ShapeType;  // 0xA8  enum16. [Sphere=0x0, Pill=0x1, Box=0x2, Triangle=0x3, Polyhedron=0x4, Multi Sphere=0x5, Phantom=0x6, Unused 1=0x7, Unused 2=0x8, Unused 3=0x9, Unused 4=0xA, Unused 5=0xB, Unused 6=0xC, Unused 7=0xD, List=0xE, MOPP=0xF] | this and the shape index below becomes a pointer to the given shape in memory at runtime. don't poke me
        std::int16_t ShapeIndex;  // 0xAA  int16.
        std::uint32_t RuntimeShapePointerPad;  // 0xAC  uint32.
        float        Mass;  // 0xB0  float32.
        float        BoundingSpherePad;  // 0xB4  float32. | the bounding sphere for this rigid body will be outset by this much
        std::uint8_t CollisionQualityOverrideType;  // 0xB8  enum8. [None=0x0, Debris Simple Toi=0x1, Moving=0x2, Critical=0x3, Bullet=0x4, Character=0x5, Fixed=0x6]
        std::int8_t  Unknown_4;  // 0xB9  int8.
        std::uint16_t RuntimeFlags;  // 0xBA  flags16. [Bit 0=0, Bit 1=1, Bit 2=2, Bit 3=3, Bit 4=4, Bit 5=5, Bit 6=6, Bit 7=7, Bit 8=8, Bit 9=9, Bit 10=10, Bit 11=11, Bit 12=12, Bit 13=13, Bit 14=14, Bit 15=15]
        float        MassBodyOverride;  // 0xBC  float32. | If you want to override what the calculated mass distribution or artist set mass is, this is where you do it. Also, this will show up as n/100 in the game debugger. Awesome.
        std::uint8_t  _pad_0xC0[0x4];  // undefined.
        std::uint8_t  _pad_0xC4[0x4];  // undefined.
        std::uint8_t  _pad_0xC8[0x4];  // undefined.
        std::uint8_t  _pad_0xCC[0x4];  // undefined.
    };
    static_assert(sizeof(Phmo_RigidBodiesEntry) == 0xD0, "Phmo_RigidBodiesEntry size mismatch");

    // Entry size: 0x10
    struct Phmo_MaterialsEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        std::uint8_t Flags;  // 0x4  flags8. [Supresses Effects=0, Force Enable Collision With Player=1]
        std::int8_t  Unknown;  // 0x5  int8.
        std::int16_t Unknown_2;  // 0x6  int16.
        std::uint32_t GlobalMaterialName;  // 0x8  stringid.
        std::int16_t PhantomTypeIndex;  // 0xC  int16.
        std::uint8_t ProxyCollisionGroup;  // 0xE  enum8. [None=0x0, Small Crate=0x1, Crate=0x2, Huge Crate=0x3, Item=0x4, Projectile=0x5, Biped=0x6, Machine=0x7, Early Mover Machine=0x8, Only Collide With Environment=0x9, Tech Art Custom=0xA, Small Expensive Plant=0xB, Ignore Environment=0xC, Huge Vehicle=0xD, Ragdoll=0xE, Super Collidable Ragdoll=0xF, ...(21 total)] | does not affect anything, change the groups in the individual shapes instead.
        std::uint8_t CollisionGroup;  // 0xF  enum8. [No Override=0xFF, Everything=0x0, Environment Default=0x1, Environment Only=0x2, Small Crate=0x3, Crate=0x4, Huge Crate=0x5, Item=0x6, Projectile=0x7, Machine=0x8, Early Mover Machine=0x9, Creature=0xA, Biped=0xB, Dead Biped=0xC, Super Collidable Ragdoll=0xD, Ragdoll=0xE, ...(28 total)] | This value overrides the default group, model, and rigid body.
    };
    static_assert(sizeof(Phmo_MaterialsEntry) == 0x10, "Phmo_MaterialsEntry size mismatch");

    // Entry size: 0xB0
    struct Phmo_SpheresEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        std::int8_t  MaterialIndex;  // 0x4  int8.
        std::uint8_t MaterialFlags;  // 0x5  flags8. [Supresses Effects=0, Force Enable Collision With Player=1]
        std::int16_t GlobalMaterialIndex;  // 0x6  int16.
        float        RelativeMassScale;  // 0x8  float32.
        float        Friction;  // 0xC  float32.
        float        Restitution;  // 0x10  float32.
        float        Volume;  // 0x14  float32.
        float        Mass;  // 0x18  float32.
        std::int16_t MassDistributionIndex;  // 0x1C  int16.
        std::int8_t  PhantomTypeIndex;  // 0x1E  int8.
        std::uint8_t CollisionGroup;  // 0x1F  enum8. [No Override=0xFF, Everything=0x0, Environment Default=0x1, Environment Only=0x2, Small Crate=0x3, Crate=0x4, Huge Crate=0x5, Item=0x6, Projectile=0x7, Machine=0x8, Early Mover Machine=0x9, Creature=0xA, Biped=0xB, Dead Biped=0xC, Super Collidable Ragdoll=0xD, Ragdoll=0xE, ...(28 total)] | This value overrides the default group, model, and rigid body.
        std::uint64_t RuntimeCodePointer;  // 0x20  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::int16_t Size;  // 0x28  int16.
        std::int16_t Count;  // 0x2A  int16.
        std::uint8_t  _pad_0x2C[0x4];  // undefined.
        std::uint64_t UserData;  // 0x30  uint64. | The offset from the start of the block to the start of this shape (index * block element size). This becomes a pointer to this shape in memory at runtime. don't poke me
        std::int32_t Type;  // 0x38  int32.
        std::uint8_t  _pad_0x3C[0x4];  // undefined.
        float        Radius;  // 0x40  float32.
        std::uint8_t  _pad_0x44[0x4];  // undefined.
        std::uint8_t  _pad_0x48[0x4];  // undefined.
        std::uint8_t  _pad_0x4C[0x4];  // undefined.
        std::uint8_t  _pad_0x50[0x4];  // undefined.
        std::uint8_t  _pad_0x54[0x4];  // undefined.
        std::uint8_t  _pad_0x58[0x4];  // undefined.
        std::uint8_t  _pad_0x5C[0x4];  // undefined.
        std::uint64_t RuntimeCodePointer_2;  // 0x60  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::int16_t Size_2;  // 0x68  int16.
        std::int16_t Count_2;  // 0x6A  int16.
        std::uint8_t  _pad_0x6C[0x4];  // undefined.
        std::uint64_t UserData_2;  // 0x70  uint64. | The offset from the start of the block to the start of this shape (index * block element size). This becomes a pointer to this shape in memory at runtime. don't poke me
        std::int32_t Type_2;  // 0x78  int32.
        std::uint8_t  _pad_0x7C[0x4];  // undefined.
        float        Radius_2;  // 0x80  float32.
        std::uint8_t  _pad_0x84[0x4];  // undefined.
        std::uint64_t RuntimeCodePointer_3;  // 0x88  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::uint16_t ShapeType;  // 0x90  enum16. [Sphere=0x0, Pill=0x1, Box=0x2, Triangle=0x3, Polyhedron=0x4, Multi Sphere=0x5, Phantom=0x6, Unused 1=0x7, Unused 2=0x8, Unused 3=0x9, Unused 4=0xA, Unused 5=0xB, Unused 6=0xC, Unused 7=0xD, List=0xE, MOPP=0xF] | this and the shape index below becomes a pointer to the given shape in memory at runtime. don't poke me
        std::int16_t ShapeIndex;  // 0x92  int16.
        std::uint32_t RuntimeShapePointerPad;  // 0x94  uint32.
        std::int32_t ChildShapeSize;  // 0x98  int32.
        std::uint8_t  _pad_0x9C[0x4];  // undefined.
        MapStructure::Primitive::Vec3 Translation;  // 0xA0  vector3.
        float        WTranslation;  // 0xAC  float32.
    };
    static_assert(sizeof(Phmo_SpheresEntry) == 0xB0, "Phmo_SpheresEntry size mismatch");

    // Entry size: 0xD0
    struct Phmo_MultiSpheresEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        std::int8_t  MaterialIndex;  // 0x4  int8.
        std::uint8_t MaterialFlags;  // 0x5  flags8. [Supresses Effects=0, Force Enable Collision With Player=1]
        std::int16_t GlobalMaterialIndex;  // 0x6  int16.
        float        RelativeMassScale;  // 0x8  float32.
        float        Friction;  // 0xC  float32.
        float        Restitution;  // 0x10  float32.
        float        Volume;  // 0x14  float32.
        float        Mass;  // 0x18  float32.
        std::int16_t MassDistributionIndex;  // 0x1C  int16.
        std::int8_t  PhantomTypeIndex;  // 0x1E  int8.
        std::uint8_t CollisionGroup;  // 0x1F  enum8. [No Override=0xFF, Everything=0x0, Environment Default=0x1, Environment Only=0x2, Small Crate=0x3, Crate=0x4, Huge Crate=0x5, Item=0x6, Projectile=0x7, Machine=0x8, Early Mover Machine=0x9, Creature=0xA, Biped=0xB, Dead Biped=0xC, Super Collidable Ragdoll=0xD, Ragdoll=0xE, ...(28 total)] | This value overrides the default group, model, and rigid body.
        std::uint64_t RuntimeCodePointer;  // 0x20  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::int16_t Size;  // 0x28  int16.
        std::int16_t Count;  // 0x2A  int16.
        std::uint8_t  _pad_0x2C[0x4];  // undefined.
        std::uint64_t UserData;  // 0x30  uint64. | The offset from the start of the block to the start of this shape (index * block element size). This becomes a pointer to this shape in memory at runtime. don't poke me
        std::int32_t Type;  // 0x38  int32.
        std::uint8_t  _pad_0x3C[0x4];  // undefined.
        std::int32_t NumberOfSpheres;  // 0x40  int32.
        std::uint8_t  _pad_0x44[0x4];  // undefined.
        std::uint8_t  _pad_0x48[0x4];  // undefined.
        std::uint8_t  _pad_0x4C[0x4];  // undefined.
        MapStructure::Primitive::Vec3 Sphere0;  // 0x50  vector3.
        float        WSphere0;  // 0x5C  float32.
        MapStructure::Primitive::Vec3 Sphere1;  // 0x60  vector3.
        float        WSphere1;  // 0x6C  float32.
        MapStructure::Primitive::Vec3 Sphere2;  // 0x70  vector3.
        float        WSphere2;  // 0x7C  float32.
        MapStructure::Primitive::Vec3 Sphere3;  // 0x80  vector3.
        float        WSphere3;  // 0x8C  float32.
        MapStructure::Primitive::Vec3 Sphere4;  // 0x90  vector3.
        float        WSphere4;  // 0x9C  float32.
        MapStructure::Primitive::Vec3 Sphere5;  // 0xA0  vector3.
        float        WSphere5;  // 0xAC  float32.
        MapStructure::Primitive::Vec3 Sphere6;  // 0xB0  vector3.
        float        WSphere6;  // 0xBC  float32.
        MapStructure::Primitive::Vec3 Sphere7;  // 0xC0  vector3.
        float        WSphere7;  // 0xCC  float32.
    };
    static_assert(sizeof(Phmo_MultiSpheresEntry) == 0xD0, "Phmo_MultiSpheresEntry size mismatch");

    // Entry size: 0x70
    struct Phmo_PillsEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        std::int8_t  MaterialIndex;  // 0x4  int8.
        std::uint8_t MaterialFlags;  // 0x5  flags8. [Supresses Effects=0, Force Enable Collision With Player=1]
        std::int16_t GlobalMaterialIndex;  // 0x6  int16.
        float        RelativeMassScale;  // 0x8  float32.
        float        Friction;  // 0xC  float32.
        float        Restitution;  // 0x10  float32.
        float        Volume;  // 0x14  float32.
        float        Mass;  // 0x18  float32.
        std::int16_t MassDistributionIndex;  // 0x1C  int16.
        std::int8_t  PhantomTypeIndex;  // 0x1E  int8.
        std::uint8_t CollisionGroup;  // 0x1F  enum8. [No Override=0xFF, Everything=0x0, Environment Default=0x1, Environment Only=0x2, Small Crate=0x3, Crate=0x4, Huge Crate=0x5, Item=0x6, Projectile=0x7, Machine=0x8, Early Mover Machine=0x9, Creature=0xA, Biped=0xB, Dead Biped=0xC, Super Collidable Ragdoll=0xD, Ragdoll=0xE, ...(28 total)] | This value overrides the default group, model, and rigid body.
        std::uint64_t RuntimeCodePointer;  // 0x20  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::int16_t Size;  // 0x28  int16.
        std::int16_t Count;  // 0x2A  int16.
        std::uint8_t  _pad_0x2C[0x4];  // undefined.
        std::uint64_t UserData;  // 0x30  uint64. | The offset from the start of the block to the start of this shape (index * block element size). This becomes a pointer to this shape in memory at runtime. don't poke me
        std::int32_t Type;  // 0x38  int32.
        std::uint8_t  _pad_0x3C[0x4];  // undefined.
        float        Radius;  // 0x40  float32.
        std::uint8_t  _pad_0x44[0x4];  // undefined.
        std::uint8_t  _pad_0x48[0x4];  // undefined.
        std::uint8_t  _pad_0x4C[0x4];  // undefined.
        MapStructure::Primitive::Vec3 Bottom;  // 0x50  vector3.
        float        WBottom;  // 0x5C  float32.
        MapStructure::Primitive::Vec3 Top;  // 0x60  vector3.
        float        WTop;  // 0x6C  float32.
    };
    static_assert(sizeof(Phmo_PillsEntry) == 0x70, "Phmo_PillsEntry size mismatch");

    // Entry size: 0xE0
    struct Phmo_BoxesEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        std::int8_t  MaterialIndex;  // 0x4  int8.
        std::uint8_t MaterialFlags;  // 0x5  flags8. [Supresses Effects=0, Force Enable Collision With Player=1]
        std::int16_t GlobalMaterialIndex;  // 0x6  int16.
        float        RelativeMassScale;  // 0x8  float32.
        float        Friction;  // 0xC  float32.
        float        Restitution;  // 0x10  float32.
        float        Volume;  // 0x14  float32.
        float        Mass;  // 0x18  float32.
        std::int16_t MassDistributionIndex;  // 0x1C  int16.
        std::int8_t  PhantomTypeIndex;  // 0x1E  int8.
        std::uint8_t CollisionGroup;  // 0x1F  enum8. [No Override=0xFF, Everything=0x0, Environment Default=0x1, Environment Only=0x2, Small Crate=0x3, Crate=0x4, Huge Crate=0x5, Item=0x6, Projectile=0x7, Machine=0x8, Early Mover Machine=0x9, Creature=0xA, Biped=0xB, Dead Biped=0xC, Super Collidable Ragdoll=0xD, Ragdoll=0xE, ...(28 total)] | This value overrides the default group, model, and rigid body.
        std::uint64_t RuntimeCodePointer;  // 0x20  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::int16_t Size;  // 0x28  int16.
        std::int16_t Count;  // 0x2A  int16.
        std::uint8_t  _pad_0x2C[0x4];  // undefined.
        std::uint64_t UserData;  // 0x30  uint64. | The offset from the start of the block to the start of this shape (index * block element size). This becomes a pointer to this shape in memory at runtime. don't poke me
        std::int32_t Type;  // 0x38  int32.
        std::uint8_t  _pad_0x3C[0x4];  // undefined.
        float        Radius;  // 0x40  float32.
        std::uint8_t  _pad_0x44[0x4];  // undefined.
        std::uint8_t  _pad_0x48[0x4];  // undefined.
        std::uint8_t  _pad_0x4C[0x4];  // undefined.
        MapStructure::Primitive::Vec3 HalfExtents;  // 0x50  vector3.
        float        WHalfExtents;  // 0x5C  float32.
        std::uint64_t RuntimeCodePointer_2;  // 0x60  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::int16_t Size_2;  // 0x68  int16.
        std::int16_t Count_2;  // 0x6A  int16.
        std::uint8_t  _pad_0x6C[0x4];  // undefined.
        std::uint64_t UserData_2;  // 0x70  uint64. | The offset from the start of the block to the start of this shape (index * block element size). This becomes a pointer to this shape in memory at runtime. don't poke me
        std::int32_t Type_2;  // 0x78  int32.
        std::uint8_t  _pad_0x7C[0x4];  // undefined.
        float        Radius_2;  // 0x80  float32.
        std::uint8_t  _pad_0x84[0x4];  // undefined.
        std::uint64_t RuntimeCodePointer_3;  // 0x88  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::uint16_t ShapeType;  // 0x90  enum16. [Sphere=0x0, Pill=0x1, Box=0x2, Triangle=0x3, Polyhedron=0x4, Multi Sphere=0x5, Phantom=0x6, Unused 1=0x7, Unused 2=0x8, Unused 3=0x9, Unused 4=0xA, Unused 5=0xB, Unused 6=0xC, Unused 7=0xD, List=0xE, MOPP=0xF] | this and the shape index below becomes a pointer to the given shape in memory at runtime. don't poke me
        std::int16_t ShapeIndex;  // 0x92  int16.
        std::uint32_t RuntimeShapePointerPad;  // 0x94  uint32.
        std::int32_t ChildShapeSize;  // 0x98  int32.
        std::uint8_t  _pad_0x9C[0x4];  // undefined.
        MapStructure::Primitive::Vec3 RotationI;  // 0xA0  vector3.
        float        WRotationI;  // 0xAC  float32.
        MapStructure::Primitive::Vec3 RotationJ;  // 0xB0  vector3.
        float        WRotationJ;  // 0xBC  float32.
        MapStructure::Primitive::Vec3 RotationK;  // 0xC0  vector3.
        float        WRotationK;  // 0xCC  float32.
        MapStructure::Primitive::Vec3 Translation;  // 0xD0  vector3.
        float        WTranslation;  // 0xDC  float32.
    };
    static_assert(sizeof(Phmo_BoxesEntry) == 0xE0, "Phmo_BoxesEntry size mismatch");

    // Entry size: 0x90
    struct Phmo_TrianglesEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        std::int8_t  MaterialIndex;  // 0x4  int8.
        std::uint8_t MaterialFlags;  // 0x5  flags8. [Supresses Effects=0, Force Enable Collision With Player=1]
        std::int16_t GlobalMaterialIndex;  // 0x6  int16.
        float        RelativeMassScale;  // 0x8  float32.
        float        Friction;  // 0xC  float32.
        float        Restitution;  // 0x10  float32.
        float        Volume;  // 0x14  float32.
        float        Mass;  // 0x18  float32.
        std::int16_t MassDistributionIndex;  // 0x1C  int16.
        std::int8_t  PhantomTypeIndex;  // 0x1E  int8.
        std::uint8_t CollisionGroup;  // 0x1F  enum8. [No Override=0xFF, Everything=0x0, Environment Default=0x1, Environment Only=0x2, Small Crate=0x3, Crate=0x4, Huge Crate=0x5, Item=0x6, Projectile=0x7, Machine=0x8, Early Mover Machine=0x9, Creature=0xA, Biped=0xB, Dead Biped=0xC, Super Collidable Ragdoll=0xD, Ragdoll=0xE, ...(28 total)] | This value overrides the default group, model, and rigid body.
        std::uint64_t RuntimeCodePointer;  // 0x20  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::int16_t Size;  // 0x28  int16.
        std::int16_t Count;  // 0x2A  int16.
        std::uint8_t  _pad_0x2C[0x4];  // undefined.
        std::uint64_t UserData;  // 0x30  uint64. | The offset from the start of the block to the start of this shape (index * block element size). This becomes a pointer to this shape in memory at runtime. don't poke me
        std::int32_t Type;  // 0x38  int32.
        std::uint8_t  _pad_0x3C[0x4];  // undefined.
        float        Radius;  // 0x40  float32.
        std::int16_t WeldingInfo;  // 0x44  int16.
        std::int8_t  WeldingType;  // 0x46  int8.
        std::int8_t  IsExtruded;  // 0x47  int8.
        std::uint8_t  _pad_0x48[0x4];  // undefined.
        std::uint8_t  _pad_0x4C[0x4];  // undefined.
        MapStructure::Primitive::Vec3 PointA;  // 0x50  vector3.
        float        WPointA;  // 0x5C  float32.
        MapStructure::Primitive::Vec3 PointB;  // 0x60  vector3.
        float        WPointB;  // 0x6C  float32.
        MapStructure::Primitive::Vec3 PointC;  // 0x70  vector3.
        float        WPointC;  // 0x7C  float32.
        MapStructure::Primitive::Vec3 Extrusion;  // 0x80  vector3.
        float        WExtrusion;  // 0x8C  float32.
    };
    static_assert(sizeof(Phmo_TrianglesEntry) == 0x90, "Phmo_TrianglesEntry size mismatch");

    // Entry size: 0xB0
    struct Phmo_PolyhedraEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        std::int8_t  MaterialIndex;  // 0x4  int8.
        std::uint8_t MaterialFlags;  // 0x5  flags8. [Supresses Effects=0, Force Enable Collision With Player=1]
        std::int16_t GlobalMaterialIndex;  // 0x6  int16.
        float        RelativeMassScale;  // 0x8  float32.
        float        Friction;  // 0xC  float32.
        float        Restitution;  // 0x10  float32.
        float        Volume;  // 0x14  float32.
        float        Mass;  // 0x18  float32.
        std::int16_t MassDistributionIndex;  // 0x1C  int16.
        std::int8_t  PhantomTypeIndex;  // 0x1E  int8.
        std::uint8_t CollisionGroup;  // 0x1F  enum8. [No Override=0xFF, Everything=0x0, Environment Default=0x1, Environment Only=0x2, Small Crate=0x3, Crate=0x4, Huge Crate=0x5, Item=0x6, Projectile=0x7, Machine=0x8, Early Mover Machine=0x9, Creature=0xA, Biped=0xB, Dead Biped=0xC, Super Collidable Ragdoll=0xD, Ragdoll=0xE, ...(28 total)] | This value overrides the default group, model, and rigid body.
        std::uint64_t RuntimeCodePointer;  // 0x20  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::int16_t Size;  // 0x28  int16.
        std::int16_t Count;  // 0x2A  int16.
        std::uint8_t  _pad_0x2C[0x4];  // undefined.
        std::uint64_t UserData;  // 0x30  uint64. | The offset from the start of the block to the start of this shape (index * block element size). This becomes a pointer to this shape in memory at runtime. don't poke me
        std::int32_t Type;  // 0x38  int32.
        std::uint8_t  _pad_0x3C[0x4];  // undefined.
        float        Radius;  // 0x40  float32.
        std::uint8_t  _pad_0x44[0x4];  // undefined.
        std::uint8_t  _pad_0x48[0x4];  // undefined.
        std::uint8_t  _pad_0x4C[0x4];  // undefined.
        MapStructure::Primitive::Vec3 AxisAlignedBoundingBoxHalfExtents;  // 0x50  vector3.
        float        WAxisAlignedBoundingBoxHalfExtents;  // 0x5C  float32.
        MapStructure::Primitive::Vec3 AxisAlignedBoundingBoxCenter;  // 0x60  vector3.
        float        WAxisAlignedBoundingBoxCenter;  // 0x6C  float32.
        std::uint64_t RuntimeFourVectorsPointer;  // 0x70  uint64. | becomes a pointer to where the four vectors for this list start in memory at runtime. don't poke me
        std::int32_t FourVectorsSize;  // 0x78  int32.
        std::uint32_t FourVectorsCapacity;  // 0x7C  uint32.
        std::int32_t NumberOfVertices;  // 0x80  int32.
        std::int8_t  UseSpuBuffer;  // 0x84  int8.
        std::int8_t  Unknown_6;  // 0x85  int8.
        std::int16_t Unknown_7;  // 0x86  int16.
        std::uint8_t  _pad_0x88[0x4];  // undefined.
        std::uint8_t  _pad_0x8C[0x4];  // undefined.
        std::uint64_t RuntimePlaneEquationsPointer;  // 0x90  uint64. | becomes a pointer to where the plane equations for this list start in memory at runtime. don't poke me
        std::int32_t PlaneEquationsSize;  // 0x98  int32.
        std::uint32_t PlaneEquationsCapacity;  // 0x9C  uint32.
        std::int32_t Connectivity;  // 0xA0  int32.
        std::uint8_t  _pad_0xA4[0x4];  // undefined.
        std::uint8_t  _pad_0xA8[0x4];  // undefined.
        std::uint8_t  _pad_0xAC[0x4];  // undefined.
    };
    static_assert(sizeof(Phmo_PolyhedraEntry) == 0xB0, "Phmo_PolyhedraEntry size mismatch");

    // Entry size: 0x30
    struct Phmo_PolyhedronFourVectorsEntry
    {
        MapStructure::Primitive::Vec3 FourVectorsX;  // 0x0  vector3.
        float        WFourVectorsX;  // 0xC  float32.
        MapStructure::Primitive::Vec3 FourVectorsY;  // 0x10  vector3.
        float        WFourVectorsY;  // 0x1C  float32.
        MapStructure::Primitive::Vec3 FourVectorsZ;  // 0x20  vector3.
        float        WFourVectorsZ;  // 0x2C  float32.
    };
    static_assert(sizeof(Phmo_PolyhedronFourVectorsEntry) == 0x30, "Phmo_PolyhedronFourVectorsEntry size mismatch");

    // Entry size: 0x10
    struct Phmo_PolyhedronPlaneEquationsEntry
    {
        MapStructure::Primitive::Vec3 PlaneEquations;  // 0x0  vector3.
        float        WPlaneEquations;  // 0xC  float32.
    };
    static_assert(sizeof(Phmo_PolyhedronPlaneEquationsEntry) == 0x10, "Phmo_PolyhedronPlaneEquationsEntry size mismatch");

    // Entry size: 0x40
    struct Phmo_MassDistributionsEntry
    {
        MapStructure::Primitive::Vec3 CenterOfMass;  // 0x0  vector3.
        float        WCenterOfMass;  // 0xC  float32.
        MapStructure::Primitive::Vec3 InertiaTensorI;  // 0x10  vector3.
        float        WInertiaTensorI;  // 0x1C  float32.
        MapStructure::Primitive::Vec3 InertiaTensorJ;  // 0x20  vector3.
        float        WInertiaTensorJ;  // 0x2C  float32.
        MapStructure::Primitive::Vec3 InertiaTensorK;  // 0x30  vector3.
        float        WInertiaTensorK;  // 0x3C  float32.
    };
    static_assert(sizeof(Phmo_MassDistributionsEntry) == 0x40, "Phmo_MassDistributionsEntry size mismatch");

    // Entry size: 0x90
    struct Phmo_ListsEntry
    {
        std::uint64_t RuntimeCodePointer;  // 0x0  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::int16_t Size;  // 0x8  int16.
        std::int16_t Count;  // 0xA  int16.
        std::uint8_t  _pad_0xC[0x4];  // undefined.
        std::uint64_t UserData;  // 0x10  uint64. | The offset from the start of the block to the start of this shape (index * block element size). This becomes a pointer to this shape in memory at runtime. don't poke me
        std::int32_t Type;  // 0x18  int32.
        std::uint8_t  _pad_0x1C[0x4];  // undefined.
        std::uint64_t RuntimeCodePointer_2;  // 0x20  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::int8_t  DisableWelding;  // 0x28  int8.
        std::int8_t  CollectionType;  // 0x29  int8.
        std::int16_t Unknown_3;  // 0x2A  int16.
        std::uint8_t  _pad_0x2C[0x4];  // undefined.
        std::uint64_t RuntimeListPointer;  // 0x30  uint64. | becomes a pointer to where the child shapes for this list start in memory at runtime. don't poke me
        std::int32_t ChildShapesSize;  // 0x38  int32.
        std::uint32_t ChildShapesCapacity;  // 0x3C  uint32.
        std::uint8_t  _pad_0x40[0x4];  // undefined.
        std::uint8_t  _pad_0x44[0x4];  // undefined.
        std::uint8_t  _pad_0x48[0x4];  // undefined.
        std::uint8_t  _pad_0x4C[0x4];  // undefined.
        MapStructure::Primitive::Vec3 AxisAlignedBoundingBoxHalfExtents;  // 0x50  vector3.
        float        WAxisAlignedBoundingBoxHalfExtents;  // 0x5C  float32.
        MapStructure::Primitive::Vec3 AxisAlignedBoundingBoxCenter;  // 0x60  vector3.
        float        WAxisAlignedBoundingBoxCenter;  // 0x6C  float32.
        std::int32_t EnabledChildren0;  // 0x70  int32.
        std::int32_t EnabledChildren1;  // 0x74  int32.
        std::int32_t EnabledChildren2;  // 0x78  int32.
        std::int32_t EnabledChildren3;  // 0x7C  int32.
        std::int32_t EnabledChildren4;  // 0x80  int32.
        std::int32_t EnabledChildren5;  // 0x84  int32.
        std::int32_t EnabledChildren6;  // 0x88  int32.
        std::int32_t EnabledChildren7;  // 0x8C  int32.
    };
    static_assert(sizeof(Phmo_ListsEntry) == 0x90, "Phmo_ListsEntry size mismatch");

    // Entry size: 0x20
    struct Phmo_ListShapesEntry
    {
        std::uint16_t ShapeType;  // 0x0  enum16. [Sphere=0x0, Pill=0x1, Box=0x2, Triangle=0x3, Polyhedron=0x4, Multi Sphere=0x5, Phantom=0x6, Unused 1=0x7, Unused 2=0x8, Unused 3=0x9, Unused 4=0xA, Unused 5=0xB, Unused 6=0xC, Unused 7=0xD, List=0xE, MOPP=0xF] | this and the shape index below becomes a pointer to the given shape in memory at runtime. don't poke me
        std::int16_t ShapeIndex;  // 0x2  int16.
        std::uint32_t RuntimeShapePointerPad;  // 0x4  uint32.
        std::uint8_t  _pad_0x8[0x4];  // undefined.
        std::uint8_t  _pad_0xC[0x4];  // undefined.
        std::int32_t NumberOfChildShapes;  // 0x10  int32.
        std::uint8_t  _pad_0x14[0x4];  // undefined.
        std::uint8_t  _pad_0x18[0x4];  // undefined.
        std::uint8_t  _pad_0x1C[0x4];  // undefined.
    };
    static_assert(sizeof(Phmo_ListShapesEntry) == 0x20, "Phmo_ListShapesEntry size mismatch");

    // Entry size: 0x80
    struct Phmo_MoppsEntry
    {
        std::uint64_t RuntimeCodePointer;  // 0x0  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::int16_t Size;  // 0x8  int16.
        std::int16_t Count;  // 0xA  int16.
        std::uint8_t  _pad_0xC[0x4];  // undefined.
        std::uint64_t UserData;  // 0x10  uint64. | The offset from the start of the block to the start of this shape (index * block element size). This becomes a pointer to this shape in memory at runtime. don't poke me
        std::int32_t Type;  // 0x18  int32.
        std::uint8_t  _pad_0x1C[0x4];  // undefined.
        std::uint8_t  _pad_0x20[0x4];  // undefined.
        std::uint8_t  _pad_0x24[0x4];  // undefined.
        std::uint64_t RuntimeMoppCodePointer;  // 0x28  uint64. | becomes a pointer to the start of the MOPP code data in memory at runtime. don't poke me
        std::uint64_t RuntimeMoppCodePointer2;  // 0x30  uint64. | becomes a pointer inside the MOPP code data in memory at runtime. don't poke me
        std::int32_t MoppDataSize;  // 0x38  int32.
        std::uint8_t  _pad_0x3C[0x4];  // undefined.
        MapStructure::Primitive::Vec3 CodeInfoCopy;  // 0x40  vector3.
        float        WCodeInfoCopy;  // 0x4C  float32.
        std::uint64_t RuntimeChildShapeVtablePointer;  // 0x50  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::uint16_t ShapeType;  // 0x58  enum16. [Sphere=0x0, Pill=0x1, Box=0x2, Triangle=0x3, Polyhedron=0x4, Multi Sphere=0x5, Phantom=0x6, Unused 1=0x7, Unused 2=0x8, Unused 3=0x9, Unused 4=0xA, Unused 5=0xB, Unused 6=0xC, Unused 7=0xD, List=0xE, MOPP=0xF] | this and the shape index below becomes a pointer to the given shape in memory at runtime. don't poke me
        std::int16_t ShapeIndex;  // 0x5A  int16.
        std::uint32_t RuntimeShapePointerPad;  // 0x5C  uint32.
        std::uint8_t  _pad_0x60[0x4];  // undefined.
        std::uint8_t  _pad_0x64[0x4];  // undefined.
        std::int32_t ChildSize;  // 0x68  int32.
        std::uint8_t  _pad_0x6C[0x4];  // undefined.
        float        Scale;  // 0x70  float32.
        std::uint8_t  _pad_0x74[0x4];  // undefined.
        std::uint8_t  _pad_0x78[0x4];  // undefined.
        std::uint8_t  _pad_0x7C[0x4];  // undefined.
    };
    static_assert(sizeof(Phmo_MoppsEntry) == 0x80, "Phmo_MoppsEntry size mismatch");

    // Entry size: 0x78
    struct Phmo_HingeConstraintsEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        std::int16_t NodeAIndex;  // 0x4  int16.
        std::int16_t NodeBIndex;  // 0x6  int16.
        float        AScale;  // 0x8  float32.
        MapStructure::Primitive::Vec3 AForward;  // 0xC  vector3.
        MapStructure::Primitive::Vec3 ALeft;  // 0x18  vector3.
        MapStructure::Primitive::Vec3 AUp;  // 0x24  vector3.
        MapStructure::Primitive::Vec3 APosition;  // 0x30  point3.
        float        BScale;  // 0x3C  float32.
        MapStructure::Primitive::Vec3 BForward;  // 0x40  vector3.
        MapStructure::Primitive::Vec3 BLeft;  // 0x4C  vector3.
        MapStructure::Primitive::Vec3 BUp;  // 0x58  vector3.
        MapStructure::Primitive::Vec3 BPosition;  // 0x64  point3.
        std::int16_t EdgeIndex;  // 0x70  int16.
        std::int16_t Unknown;  // 0x72  int16.
        std::uint8_t  _pad_0x74[0x4];  // undefined.
    };
    static_assert(sizeof(Phmo_HingeConstraintsEntry) == 0x78, "Phmo_HingeConstraintsEntry size mismatch");

    // Entry size: 0x94
    struct Phmo_RagdollConstraintsEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        std::int16_t NodeAIndex;  // 0x4  int16.
        std::int16_t NodeBIndex;  // 0x6  int16.
        float        AScale;  // 0x8  float32.
        MapStructure::Primitive::Vec3 AForward;  // 0xC  vector3.
        MapStructure::Primitive::Vec3 ALeft;  // 0x18  vector3.
        MapStructure::Primitive::Vec3 AUp;  // 0x24  vector3.
        MapStructure::Primitive::Vec3 APosition;  // 0x30  point3.
        float        BScale;  // 0x3C  float32.
        MapStructure::Primitive::Vec3 BForward;  // 0x40  vector3.
        MapStructure::Primitive::Vec3 BLeft;  // 0x4C  vector3.
        MapStructure::Primitive::Vec3 BUp;  // 0x58  vector3.
        MapStructure::Primitive::Vec3 BPosition;  // 0x64  point3.
        std::int16_t EdgeIndex;  // 0x70  int16.
        std::int16_t Unknown;  // 0x72  int16.
        std::uint8_t  _pad_0x74[0x4];  // undefined.
        MapStructure::Primitive::RangeF Twist;  // 0x78  rangef.
        MapStructure::Primitive::RangeF Cone;  // 0x80  rangef.
        MapStructure::Primitive::RangeF Plane;  // 0x88  rangef.
        float        MaximumFrictionTorque;  // 0x90  float32.
    };
    static_assert(sizeof(Phmo_RagdollConstraintsEntry) == 0x94, "Phmo_RagdollConstraintsEntry size mismatch");

    // Entry size: 0x2
    struct Phmo_Regions_Permutations_RigidBodiesEntry
    {
        std::int16_t RigidBodyIndex;  // 0x0  int16.
    };
    static_assert(sizeof(Phmo_Regions_Permutations_RigidBodiesEntry) == 0x2, "Phmo_Regions_Permutations_RigidBodiesEntry size mismatch");

    // Entry size: 0x10
    struct Phmo_Regions_PermutationsEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        // -> Phmo_Regions_Permutations_RigidBodiesEntry[]
        MapStructure::Tag::Block   RigidBodies;  // 0x4  tagblock.
    };
    static_assert(sizeof(Phmo_Regions_PermutationsEntry) == 0x10, "Phmo_Regions_PermutationsEntry size mismatch");

    // Entry size: 0x10
    struct Phmo_RegionsEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        // -> Phmo_Regions_PermutationsEntry[]
        MapStructure::Tag::Block   Permutations;  // 0x4  tagblock.
    };
    static_assert(sizeof(Phmo_RegionsEntry) == 0x10, "Phmo_RegionsEntry size mismatch");

    // Entry size: 0xC
    struct Phmo_NodesEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        std::uint16_t Flags;  // 0x4  flags16. [Does Not Animate=0]
        std::int16_t ParentIndex;  // 0x6  int16.
        std::int16_t SiblingIndex;  // 0x8  int16.
        std::int16_t ChildIndex;  // 0xA  int16.
    };
    static_assert(sizeof(Phmo_NodesEntry) == 0xC, "Phmo_NodesEntry size mismatch");

    // Entry size: 0x10
    struct Phmo_PointToPathCurves_PointsEntry
    {
        MapStructure::Primitive::Vec3 Position;  // 0x0  point3.
        float        TValue;  // 0xC  float32.
    };
    static_assert(sizeof(Phmo_PointToPathCurves_PointsEntry) == 0x10, "Phmo_PointToPathCurves_PointsEntry size mismatch");

    // Entry size: 0x14
    struct Phmo_PointToPathCurvesEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        std::int16_t NodeIndex;  // 0x4  int16.
        std::int16_t Unknown;  // 0x6  int16.
        // -> Phmo_PointToPathCurves_PointsEntry[]
        MapStructure::Tag::Block   Points;  // 0x8  tagblock.
    };
    static_assert(sizeof(Phmo_PointToPathCurvesEntry) == 0x14, "Phmo_PointToPathCurvesEntry size mismatch");

    // Entry size: 0x84
    struct Phmo_LimitedHingeConstraintsEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        std::int16_t NodeAIndex;  // 0x4  int16.
        std::int16_t NodeBIndex;  // 0x6  int16.
        float        AScale;  // 0x8  float32.
        MapStructure::Primitive::Vec3 AForward;  // 0xC  vector3.
        MapStructure::Primitive::Vec3 ALeft;  // 0x18  vector3.
        MapStructure::Primitive::Vec3 AUp;  // 0x24  vector3.
        MapStructure::Primitive::Vec3 APosition;  // 0x30  point3.
        float        BScale;  // 0x3C  float32.
        MapStructure::Primitive::Vec3 BForward;  // 0x40  vector3.
        MapStructure::Primitive::Vec3 BLeft;  // 0x4C  vector3.
        MapStructure::Primitive::Vec3 BUp;  // 0x58  vector3.
        MapStructure::Primitive::Vec3 BPosition;  // 0x64  point3.
        std::int16_t EdgeIndex;  // 0x70  int16.
        std::int16_t Unknown;  // 0x72  int16.
        std::uint8_t  _pad_0x74[0x4];  // undefined.
        float        LimitFriction;  // 0x78  float32.
        MapStructure::Primitive::RangeF LimitAngle;  // 0x7C  ranged.
    };
    static_assert(sizeof(Phmo_LimitedHingeConstraintsEntry) == 0x84, "Phmo_LimitedHingeConstraintsEntry size mismatch");

    // Entry size: 0x78
    struct Phmo_BallAndSocketConstraintsEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        std::int16_t NodeAIndex;  // 0x4  int16.
        std::int16_t NodeBIndex;  // 0x6  int16.
        float        AScale;  // 0x8  float32.
        MapStructure::Primitive::Vec3 AForward;  // 0xC  vector3.
        MapStructure::Primitive::Vec3 ALeft;  // 0x18  vector3.
        MapStructure::Primitive::Vec3 AUp;  // 0x24  vector3.
        MapStructure::Primitive::Vec3 APosition;  // 0x30  point3.
        float        BScale;  // 0x3C  float32.
        MapStructure::Primitive::Vec3 BForward;  // 0x40  vector3.
        MapStructure::Primitive::Vec3 BLeft;  // 0x4C  vector3.
        MapStructure::Primitive::Vec3 BUp;  // 0x58  vector3.
        MapStructure::Primitive::Vec3 BPosition;  // 0x64  point3.
        std::int16_t EdgeIndex;  // 0x70  int16.
        std::int16_t Unknown;  // 0x72  int16.
        std::uint8_t  _pad_0x74[0x4];  // undefined.
    };
    static_assert(sizeof(Phmo_BallAndSocketConstraintsEntry) == 0x78, "Phmo_BallAndSocketConstraintsEntry size mismatch");

    // Entry size: 0x7C
    struct Phmo_StiffSpringConstraintsEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        std::int16_t NodeAIndex;  // 0x4  int16.
        std::int16_t NodeBIndex;  // 0x6  int16.
        float        AScale;  // 0x8  float32.
        MapStructure::Primitive::Vec3 AForward;  // 0xC  vector3.
        MapStructure::Primitive::Vec3 ALeft;  // 0x18  vector3.
        MapStructure::Primitive::Vec3 AUp;  // 0x24  vector3.
        MapStructure::Primitive::Vec3 APosition;  // 0x30  point3.
        float        BScale;  // 0x3C  float32.
        MapStructure::Primitive::Vec3 BForward;  // 0x40  vector3.
        MapStructure::Primitive::Vec3 BLeft;  // 0x4C  vector3.
        MapStructure::Primitive::Vec3 BUp;  // 0x58  vector3.
        MapStructure::Primitive::Vec3 BPosition;  // 0x64  point3.
        std::int16_t EdgeIndex;  // 0x70  int16.
        std::int16_t Unknown;  // 0x72  int16.
        std::uint8_t  _pad_0x74[0x4];  // undefined.
        float        SpringLength;  // 0x78  float32.
    };
    static_assert(sizeof(Phmo_StiffSpringConstraintsEntry) == 0x7C, "Phmo_StiffSpringConstraintsEntry size mismatch");

    // Entry size: 0x84
    struct Phmo_PrismaticConstraintsEntry
    {
        std::uint32_t Name;  // 0x0  stringid.
        std::int16_t NodeAIndex;  // 0x4  int16.
        std::int16_t NodeBIndex;  // 0x6  int16.
        float        AScale;  // 0x8  float32.
        MapStructure::Primitive::Vec3 AForward;  // 0xC  vector3.
        MapStructure::Primitive::Vec3 ALeft;  // 0x18  vector3.
        MapStructure::Primitive::Vec3 AUp;  // 0x24  vector3.
        MapStructure::Primitive::Vec3 APosition;  // 0x30  point3.
        float        BScale;  // 0x3C  float32.
        MapStructure::Primitive::Vec3 BForward;  // 0x40  vector3.
        MapStructure::Primitive::Vec3 BLeft;  // 0x4C  vector3.
        MapStructure::Primitive::Vec3 BUp;  // 0x58  vector3.
        MapStructure::Primitive::Vec3 BPosition;  // 0x64  point3.
        std::int16_t EdgeIndex;  // 0x70  int16.
        std::int16_t Unknown;  // 0x72  int16.
        std::uint8_t  _pad_0x74[0x4];  // undefined.
        MapStructure::Primitive::RangeF LimitAngle;  // 0x78  rangef.
        float        MaximumFrictionForce;  // 0x80  float32.
    };
    static_assert(sizeof(Phmo_PrismaticConstraintsEntry) == 0x84, "Phmo_PrismaticConstraintsEntry size mismatch");

    // Entry size: 0x58
    struct Phmo_PhantomsEntry
    {
        std::uint64_t RuntimeCodePointer;  // 0x0  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::int16_t Size;  // 0x8  int16.
        std::int16_t Count;  // 0xA  int16.
        std::uint8_t  _pad_0xC[0x4];  // undefined.
        std::uint64_t UserData;  // 0x10  uint64. | The offset from the start of the block to the start of this shape (index * block element size). This becomes a pointer to this shape in memory at runtime. don't poke me
        std::int32_t Type;  // 0x18  int32.
        std::uint8_t  _pad_0x1C[0x4];  // undefined.
        std::uint16_t ShapeType;  // 0x20  enum16. [Sphere=0x0, Pill=0x1, Box=0x2, Triangle=0x3, Polyhedron=0x4, Multi Sphere=0x5, Phantom=0x6, Unused 1=0x7, Unused 2=0x8, Unused 3=0x9, Unused 4=0xA, Unused 5=0xB, Unused 6=0xC, Unused 7=0xD, List=0xE, MOPP=0xF] | this and the shape index below becomes a pointer to the given shape in memory at runtime. don't poke me
        std::int16_t ShapeIndex;  // 0x22  int16.
        std::uint32_t RuntimeShapePointerPad;  // 0x24  uint32.
        std::uint64_t RuntimeChildShapeVtablePointer;  // 0x28  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::uint64_t RuntimeSelfPointer;  // 0x30  uint64. | becomes a pointer to the current shape, starting at the next value in memory at runtime. don't poke me
        std::uint64_t RuntimeCodePointer_2;  // 0x38  uint64. | becomes a pointer in memory at runtime. don't poke me
        std::int16_t Size_2;  // 0x40  int16.
        std::int16_t Count_2;  // 0x42  int16.
        std::uint8_t  _pad_0x44[0x4];  // undefined.
        std::uint64_t UserData_2;  // 0x48  uint64. | The offset from the start of the block to the start of this shape (index * block element size). This becomes a pointer to this shape in memory at runtime. don't poke me
        std::int32_t Type_2;  // 0x50  int32.
        std::uint8_t  _pad_0x54[0x4];  // undefined.
    };
    static_assert(sizeof(Phmo_PhantomsEntry) == 0x58, "Phmo_PhantomsEntry size mismatch");

    // Entry size: 0x19C
    struct PhmoData
    {
        std::uint32_t Flags;  // 0x0  flags32. [Bit 0=0, Bit 1=1, Bit 2=2, Bit 3=3, Bit 4=4, Bit 5=5, Bit 6=6, Bit 7=7, Bit 8=8, Bit 9=9, Bit 10=10, Bit 11=11, Bit 12=12, Bit 13=13, Bit 14=14, Bit 15=15, ...(32 total)]
        float        MassScale;  // 0x4  float32. | scales the mass of each rigid body. If you leave this field as 0, then it will be calculated from the total mass below.
        float        Mass;  // 0x8  float32. | override total mass of all rigid bodies. Note that this will NOT be the mass of the object if not all rigid bodies are present (for example if you are using permutations). If you set a mass scale above, this field is unused.
        float        LowFrequencyDeactivationScale;  // 0xC  float32. | 0 is default (1). LESS than 1 deactivates less aggressively. GREATER than 1 is more agressive.
        float        HighFrequencyDeactivationScale;  // 0x10  float32. | 0 is default (1). LESS than 1 deactivates less aggressively. GREATER than 1 is more agressive.
        float        CustomShapeRadius;  // 0x14  float32. | 0 defaults to .016. This field is intentionally hidden because we should only alter this for very special situations. Lower number == lower performance
        float        MaximumPenetrationDepthScale;  // 0x18  float32. | 0 is default (1). for objects that are prone to falling through the world we can reduce this number at the cost of performance
        std::int8_t  ImportVersion;  // 0x1C  int8.
        std::int8_t  Unknown;  // 0x1D  int8.
        std::int16_t Unknown_2;  // 0x1E  int16.
        // -> Phmo_DampedSpringMotorsEntry[]
        MapStructure::Tag::Block   DampedSpringMotors;  // 0x20  tagblock.
        // -> Phmo_PositionMotorsEntry[]
        MapStructure::Tag::Block   PositionMotors;  // 0x2C  tagblock.
        // -> Phmo_PhantomTypesEntry[]
        MapStructure::Tag::Block   PhantomTypes;  // 0x38  tagblock.
        // -> Phmo_PoweredChainsEntry[]
        MapStructure::Tag::Block   PoweredChains;  // 0x44  tagblock.
        // -> Phmo_NodeEdgesEntry[]
        MapStructure::Tag::Block   NodeEdges;  // 0x50  tagblock.
        // -> Phmo_RigidBodiesEntry[]
        MapStructure::Tag::Block   RigidBodies;  // 0x5C  tagblock.
        // -> Phmo_MaterialsEntry[]
        MapStructure::Tag::Block   Materials;  // 0x68  tagblock.
        // -> Phmo_SpheresEntry[]
        MapStructure::Tag::Block   Spheres;  // 0x74  tagblock.
        // -> Phmo_MultiSpheresEntry[]
        MapStructure::Tag::Block   MultiSpheres;  // 0x80  tagblock.
        // -> Phmo_PillsEntry[]
        MapStructure::Tag::Block   Pills;  // 0x8C  tagblock.
        // -> Phmo_BoxesEntry[]
        MapStructure::Tag::Block   Boxes;  // 0x98  tagblock.
        // -> Phmo_TrianglesEntry[]
        MapStructure::Tag::Block   Triangles;  // 0xA4  tagblock.
        // -> Phmo_PolyhedraEntry[]
        MapStructure::Tag::Block   Polyhedra;  // 0xB0  tagblock.
        // -> Phmo_PolyhedronFourVectorsEntry[]
        MapStructure::Tag::Block   PolyhedronFourVectors;  // 0xBC  tagblock.
        // -> Phmo_PolyhedronPlaneEquationsEntry[]
        MapStructure::Tag::Block   PolyhedronPlaneEquations;  // 0xC8  tagblock.
        // -> Phmo_MassDistributionsEntry[]
        MapStructure::Tag::Block   MassDistributions;  // 0xD4  tagblock.
        // -> Phmo_ListsEntry[]
        MapStructure::Tag::Block   Lists;  // 0xE0  tagblock.
        // -> Phmo_ListShapesEntry[]
        MapStructure::Tag::Block   ListShapes;  // 0xEC  tagblock.
        // -> Phmo_MoppsEntry[]
        MapStructure::Tag::Block   Mopps;  // 0xF8  tagblock.
        MapStructure::Data::Reference MoppCodes;  // 0x104  dataref.
        // -> Phmo_HingeConstraintsEntry[]
        MapStructure::Tag::Block   HingeConstraints;  // 0x118  tagblock.
        // -> Phmo_RagdollConstraintsEntry[]
        MapStructure::Tag::Block   RagdollConstraints;  // 0x124  tagblock.
        // -> Phmo_RegionsEntry[]
        MapStructure::Tag::Block   Regions;  // 0x130  tagblock.
        // -> Phmo_NodesEntry[]
        MapStructure::Tag::Block   Nodes;  // 0x13C  tagblock.
        std::uint8_t  _pad_0x148[0x4];  // undefined.
        std::uint8_t  _pad_0x14C[0x4];  // undefined.
        std::uint8_t  _pad_0x150[0x4];  // undefined.
        // -> Phmo_PointToPathCurvesEntry[]
        MapStructure::Tag::Block   PointToPathCurves;  // 0x154  tagblock.
        // -> Phmo_LimitedHingeConstraintsEntry[]
        MapStructure::Tag::Block   LimitedHingeConstraints;  // 0x160  tagblock.
        // -> Phmo_BallAndSocketConstraintsEntry[]
        MapStructure::Tag::Block   BallAndSocketConstraints;  // 0x16C  tagblock.
        // -> Phmo_StiffSpringConstraintsEntry[]
        MapStructure::Tag::Block   StiffSpringConstraints;  // 0x178  tagblock.
        // -> Phmo_PrismaticConstraintsEntry[]
        MapStructure::Tag::Block   PrismaticConstraints;  // 0x184  tagblock.
        // -> Phmo_PhantomsEntry[]
        MapStructure::Tag::Block   Phantoms;  // 0x190  tagblock.
    };
    static_assert(sizeof(PhmoData) == 0x19C, "PhmoData size mismatch");

}

#pragma pack(pop)
