// Auto-generated by TagTranspiler (GenerateTemplate.py)
// Source XML: ctrl.xml
// Component starts at datum offset 0x2C4; field offsets in comments are relative to it.
// Root struct size: 0x8

export module Tables.Template.Type:Ctrl.Structure;

import Map.Reader.Type;
import std;

namespace
{
    namespace MapStructure = Map::Reader::Type::Structure;
}

#pragma pack(push, 1)

export namespace Tables::Template::Type::Ctrl::Structure
{
    // Entry size: 0x8
    struct CtrlData
    {
        std::uint32_t Unknown2c4;  // 0x0  uint32. | R3 W5 src=INT_AND, MULTIEQUAL SHARED W:ctrl_place
        std::uint16_t Unknown2c8;  // 0x4  uint16. | R0 W2 init=0x1 src=[param_2+0x7e] W:ctrl_init,ctrl_place
        std::uint16_t Unknown2ca;  // 0x6  uint16. | R0 W1 src=[param_2+0x80] known=Weapon.CurrentAmmo W:ctrl_place
    };
    static_assert(sizeof(CtrlData) == 0x8, "CtrlData size mismatch");

}

#pragma pack(pop)