// Auto-generated by TagTranspiler (GenerateTemplate.py)
// Source XML: proj.xml
// Component starts at datum offset 0x1A8; field offsets in comments are relative to it.
// Root struct size: 0xb0

export module Template.Object.Type:Proj.Structure;

import Map.Reader.Type;
import std;

namespace
{
    namespace MapStructure = Map::Reader::Type::Structure;
}

#pragma pack(push, 1)

export namespace Template::Object::Type::Proj::Structure
{
    // Entry size: 0xB0
    struct ProjData
    {
        std::uint32_t Unknown1a8;  // 0x0  uint32. | R44 W25 src=INT_OR, MULTIEQUAL known=Projectile.RuntimeFlags W:FUN_1804f2d00,proj_init,FUN_1804f03f0
        std::uint32_t Unknown1ac;  // 0x4  uint32. | R5 W0 R:FUN_1804f03f0,FUN_1804f0218,FUN_1804f19bc
        std::uint16_t Unknown1b0;  // 0x8  uint16. | R0 W1 init=0x0 W:proj_init
        std::uint16_t Unknown1b2;  // 0xA  uint16. | R1 W1 init=0x0 W:proj_init
        std::uint16_t Unknown1b4;  // 0xC  uint16. | R2 W0 R:FUN_1804f2d00
        std::uint16_t Unknown1b6;  // 0xE  uint16. | R1 W2 src=INDIRECT, MULTIEQUAL W:proj_init,FUN_1804f2d00
        std::uint8_t  _gap_0x10[0x4];
        std::uint32_t Unknown1bc;  // 0x14  uint32. | R5 W0 SHARED R:FUN_180781484,FUN_180781920
        std::uint32_t Unknown1c0;  // 0x18  uint32. | R2 W2 src=INDIRECT, [param_2+0x34] W:proj_init,FUN_1804f2d00
        std::uint32_t Unknown1c4;  // 0x1C  uint32. | R3 W1 src=call 180473dc0 known=Projectile.OwnerBipedHandle W:proj_init
        std::uint32_t Unknown1c8;  // 0x20  uint32. | R2 W2 src=[param_2+0x40] W:FUN_1804f2d00
        std::uint16_t Unknown1cc;  // 0x24  uint16. | R4 W1 init=0x0 W:proj_init
        std::uint16_t Unknown1ce;  // 0x26  uint16. | R0 W1 init=0x0 W:proj_init
        std::uint32_t Unknown1d0;  // 0x28  uint32. | R1 W1 upd=0xffffffff W:proj_sd8
        std::uint32_t Unknown1d4;  // 0x2C  uint32. | R10 W1 upd=0xffffffff W:proj_sd8
        std::uint32_t Unknown1d8;  // 0x30  uint32. | R2 W2 upd=0xffffffff src=MULTIEQUAL known=Biped.VerticalInput|Projectile.OwnerWeaponHandle W:proj_init,proj_sd8
        std::uint32_t Unknown1dc;  // 0x34  uint32. | R0 W2 src=[param_2+0x40], [lVar3+0x14] W:FUN_1804f2d00
        std::uint32_t Unknown1e0;  // 0x38  uint32. | R0 W1 src=MULTIEQUAL known=Weapon.TotalHeat W:FUN_1804f2d00
        std::uint64_t Unknown1e4;  // 0x3C  uint64. | R0 W1 src=[param_2+0x8] known=Weapon.TotalEnergy W:FUN_1804f2d00
        std::uint32_t Unknown1ec;  // 0x44  uint32. | R0 W1 src=[param_2+0x10] known=Equipment.TotalEnergy W:FUN_1804f2d00
        float        Unknown1f0;  // 0x48  float32. | R2 W2 upd=0x3f800000 src=FLOAT_ADD W:proj_sf8,FUN_1804f0078
        float        Unknown1f4;  // 0x4C  float32. | R1 W2 src=FLOAT_DIV W:proj_init,FUN_1804f74c0
        float        Unknown1f8;  // 0x50  float32. | R1 W1 src=FLOAT_ADD known=Weapon.IsTracking W:FUN_1804f0078
        float        Unknown1fc;  // 0x54  float32. | R1 W1 src=FLOAT_DIV W:FUN_1804f74c0
        float        Unknown200;  // 0x58  float32. | R5 W2 upd=0x3f800000 src=FLOAT_ADD known=Weapon.TrackedBipedHandle W:proj_sf8,FUN_1804f0078
        float        Unknown204;  // 0x5C  float32. | R3 W1 src=FLOAT_DIV W:proj_init
        float        Unknown208;  // 0x60  float32. | R6 W1 src=FLOAT_ADD W:FUN_1804f03f0
        float        Unknown20c;  // 0x64  float32. | R3 W1 src=FLOAT_ADD W:FUN_1804f03f0
        std::uint32_t Unknown210;  // 0x68  uint32. | R5 W1 src=SUBPIECE W:proj_init
        float        Unknown214;  // 0x6C  float32. | R3 W3 init=0xffffffffx2 src=FLOAT_ADD SHARED W:FUN_18020ec44,FUN_18020eca4,FUN_1800a8dc4
        float        Unknown218;  // 0x70  float32. | R1 W3 init=0xffffffffx2 src=FLOAT_ADD SHARED W:FUN_18020ec44,FUN_18020eca4,FUN_1800a8dc4
        float        Unknown21c;  // 0x74  float32. | R1 W2 src=[lVar1+0x58], FLOAT_ADD SHARED W:FUN_180471f9c,FUN_1800a8dc4
        std::uint32_t Unknown220;  // 0x78  uint32. | R0 W2 init=0x0x2 SHARED W:FUN_18020ec44,FUN_18020eca4
        std::uint32_t Unknown224;  // 0x7C  uint32. | R2 W0 R:FUN_1804f03f0
        std::uint32_t Unknown228;  // 0x80  uint32. | R2 W0 R:FUN_1804f03f0
        std::uint32_t Unknown22c;  // 0x84  uint32. | R3 W1 init=0x3000000 SHARED W:FUN_18020eca4
        float        Unknown230;  // 0x88  float32. | R1 W2 src=MULTIEQUAL, FLOAT_MULT W:proj_init
        float        Unknown234;  // 0x8C  float32. | R1 W2 src=FLOAT_MULT, FLOAT_ADD W:proj_init,FUN_1804f03f0
        float        Unknown238;  // 0x90  float32. | R4 W1 src=FLOAT_ADD W:FUN_1804f03f0
        std::uint64_t Unknown23c;  // 0x94  uint64. | R0 W1 src=[param_2+0x1c] W:proj_init
        std::uint32_t Unknown244;  // 0x9C  uint32. | R0 W1 src=[param_2+0x24] W:proj_init
        std::uint16_t Unknown248;  // 0xA0  uint16. | R4 W1 init=0xffff W:proj_init
        std::uint16_t Unknown24a;  // 0xA2  uint16. | R1 W2 src=INDIRECT, INT_ADD W:proj_init,FUN_1804f0078
        std::uint32_t Unknown24c;  // 0xA4  uint32. | R0 W1 src=SUBPIECE W:proj_init
        std::uint16_t Unknown250;  // 0xA8  uint16. | R0 W2 init=0x0 upd=0x0 W:proj_init,proj_s148
        std::uint8_t  _gap_0xAA[0x2];
        std::uint16_t Unknown254;  // 0xAC  uint16. | R2 W0 R:proj_sa8,FUN_1804f2d00
        std::uint8_t  _tail_0xAE[0x2];  // trailing pad
    };
    static_assert(sizeof(ProjData) == 0xB0, "ProjData size mismatch");

}

#pragma pack(pop)