// Auto-generated by TagTranspiler (GenerateObject.py)
// Source XML: proj.xml

export module Map.Tag.Type:Proj.Object;

import :Proj.Structure;
import std;

namespace
{
    using namespace Map::Tag::Type::Proj::Structure;
}

export namespace Map::Tag::Type::Proj::Object
{
    struct Proj_FunctionsObject : public Proj_FunctionsEntry
    {
        std::vector<Proj_Functions_InterpolationEntry> Interpolation;
    };

    struct Proj_HullSurfacesObject : public Proj_HullSurfacesEntry
    {
        std::vector<Proj_HullSurfaces_DragEntry> Drag;
    };

    struct Proj_ChangeColorsObject : public Proj_ChangeColorsEntry
    {
        std::vector<Proj_ChangeColors_InitialPermutationsEntry> InitialPermutations;
        std::vector<Proj_ChangeColors_FunctionsEntry> Functions;
    };

    struct ProjObject
    {
        std::string  TagName;
        ProjData Data;

        std::vector<Proj_EarlyMoverOrientedBoundingBoxEntry> EarlyMoverOrientedBoundingBox;
        std::vector<Proj_AiPropertiesEntry> AiProperties;
        std::vector<Proj_FunctionsObject> Functions;
        std::vector<Proj_RuntimeInterpolatorFunctionsEntry> RuntimeInterpolatorFunctions;
        std::vector<Proj_AttachmentsEntry> Attachments;
        std::vector<Proj_HullSurfacesObject> HullSurfaces;
        std::vector<Proj_JetwashEntry> Jetwash;
        std::vector<Proj_WidgetsEntry> Widgets;
        std::vector<Proj_ChangeColorsObject> ChangeColors;
        std::vector<Proj_MultiplayerObjectEntry> MultiplayerObject;
        std::vector<Proj_SpawnEffectsEntry> SpawnEffects;
        std::vector<Proj_OldMaterialResponsesEntry> OldMaterialResponses;
        std::vector<Proj_MaterialResponseEntry> MaterialResponse;
        std::vector<Proj_BruteGrenadeEntry> BruteGrenade;
        std::vector<Proj_FireBombGrenadeEntry> FireBombGrenade;
        std::vector<Proj_ConicalSpreadEntry> ConicalSpread;
    };
}
