// Auto-generated by TagTranspiler (GenerateObject.py)
// Source XML: sLdT.xml

export module Map.Tag.Type:Sldt.Object;

import :Sldt.Structure;
import std;

namespace
{
    using namespace Map::Tag::Type::Sldt::Structure;
}

export namespace Map::Tag::Type::Sldt::Object
{
    struct Sldt_UnknownObject_2 : public Sldt_UnknownEntry_2
    {
        std::vector<Sldt_Unknown_2_UnknownEntry> Unknown_9;
    };

    struct SldtObject
    {
        std::string  TagName;
        SldtData Data;

        std::vector<Sldt_LightmapDataReferencesEntry> LightmapDataReferences;
        std::vector<Sldt_AirprobesEntry> Airprobes;
        std::vector<Sldt_UnknownEntry> Unknown_2;
        std::vector<Sldt_UnknownObject_2> Unknown_3;
        std::vector<Sldt_UnknownEntry_3> Unknown_4;
    };
}
