// Auto-generated by TagTranspiler (GenerateStructure.py)
// Source XML: sLdT.xml
// Root struct size: 0x40

export module Map.Tag.Type:Sldt.Structure;

import Map.Reader.Type;
import std;

namespace
{
    namespace MapStructure = Map::Reader::Type::Structure;
}

#pragma pack(push, 1)

export namespace Map::Tag::Type::Sldt::Structure
{
    // Entry size: 0x20
    struct Sldt_LightmapDataReferencesEntry
    {
        MapStructure::Tag::Reference LightmapData;  // 0x0  tagref.
        MapStructure::Tag::Reference WetnessData;  // 0x10  tagref.
    };
    static_assert(sizeof(Sldt_LightmapDataReferencesEntry) == 0x20, "Sldt_LightmapDataReferencesEntry size mismatch");

    // Entry size: 0x38
    struct Sldt_AirprobesEntry
    {
        std::uint8_t  _pad_0x0[0x4];  // undefined.
        std::uint8_t  _pad_0x4[0x4];  // undefined.
        std::uint8_t  _pad_0x8[0x4];  // undefined.
        std::uint32_t Name;  // 0xC  stringid.
        std::uint8_t  _pad_0x10[0x4];  // undefined.
        std::uint8_t  _pad_0x14[0x4];  // undefined.
        std::uint8_t  _pad_0x18[0x4];  // undefined.
        std::uint8_t  _pad_0x1C[0x4];  // undefined.
        std::uint8_t  _pad_0x20[0x4];  // undefined.
        std::uint8_t  _pad_0x24[0x4];  // undefined.
        std::uint8_t  _pad_0x28[0x4];  // undefined.
        std::uint8_t  _pad_0x2C[0x4];  // undefined.
        std::uint8_t  _pad_0x30[0x4];  // undefined.
        std::uint8_t  _pad_0x34[0x4];  // undefined.
    };
    static_assert(sizeof(Sldt_AirprobesEntry) == 0x38, "Sldt_AirprobesEntry size mismatch");

    // Entry size: 0x2C
    struct Sldt_UnknownEntry
    {
        std::uint8_t  _pad_0x0[0x4];  // undefined.
        std::uint8_t  _pad_0x4[0x4];  // undefined.
        std::uint8_t  _pad_0x8[0x4];  // undefined.
        std::uint8_t  _pad_0xC[0x4];  // undefined.
        std::uint8_t  _pad_0x10[0x4];  // undefined.
        std::uint8_t  _pad_0x14[0x4];  // undefined.
        std::uint8_t  _pad_0x18[0x4];  // undefined.
        std::uint8_t  _pad_0x1C[0x4];  // undefined.
        std::uint8_t  _pad_0x20[0x4];  // undefined.
        std::uint8_t  _pad_0x24[0x4];  // undefined.
        std::uint8_t  _pad_0x28[0x4];  // undefined.
    };
    static_assert(sizeof(Sldt_UnknownEntry) == 0x2C, "Sldt_UnknownEntry size mismatch");

    // Entry size: 0x30
    struct Sldt_Unknown_2_UnknownEntry
    {
        std::uint8_t  _pad_0x0[0x4];  // undefined.
        std::uint8_t  _pad_0x4[0x4];  // undefined.
        std::uint8_t  _pad_0x8[0x4];  // undefined.
        std::uint8_t  _pad_0xC[0x4];  // undefined.
        std::uint8_t  _pad_0x10[0x4];  // undefined.
        std::uint8_t  _pad_0x14[0x4];  // undefined.
        std::uint8_t  _pad_0x18[0x4];  // undefined.
        std::uint8_t  _pad_0x1C[0x4];  // undefined.
        std::uint8_t  _pad_0x20[0x4];  // undefined.
        std::uint8_t  _pad_0x24[0x4];  // undefined.
        std::uint8_t  _pad_0x28[0x4];  // undefined.
        std::uint8_t  _pad_0x2C[0x4];  // undefined.
    };
    static_assert(sizeof(Sldt_Unknown_2_UnknownEntry) == 0x30, "Sldt_Unknown_2_UnknownEntry size mismatch");

    // Entry size: 0x2C
    struct Sldt_UnknownEntry_2
    {
        std::uint8_t  _pad_0x0[0x4];  // undefined.
        std::uint8_t  _pad_0x4[0x4];  // undefined.
        std::uint8_t  _pad_0x8[0x4];  // undefined.
        std::uint8_t  _pad_0xC[0x4];  // undefined.
        std::uint8_t  _pad_0x10[0x4];  // undefined.
        std::uint8_t  _pad_0x14[0x4];  // undefined.
        std::uint8_t  _pad_0x18[0x4];  // undefined.
        std::uint8_t  _pad_0x1C[0x4];  // undefined.
        // -> Sldt_Unknown_2_UnknownEntry[]
        MapStructure::Tag::Block   Unknown_9;  // 0x20  tagblock.
    };
    static_assert(sizeof(Sldt_UnknownEntry_2) == 0x2C, "Sldt_UnknownEntry_2 size mismatch");

    // Entry size: 0x10
    struct Sldt_UnknownEntry_3
    {
        std::uint8_t  _pad_0x0[0x4];  // undefined.
        std::uint8_t  _pad_0x4[0x4];  // undefined.
        std::uint8_t  _pad_0x8[0x4];  // undefined.
        std::uint8_t  _pad_0xC[0x4];  // undefined.
    };
    static_assert(sizeof(Sldt_UnknownEntry_3) == 0x10, "Sldt_UnknownEntry_3 size mismatch");

    // Entry size: 0x40
    struct SldtData
    {
        std::uint8_t  _pad_0x0[0x4];  // undefined.
        // -> Sldt_LightmapDataReferencesEntry[]
        MapStructure::Tag::Block   LightmapDataReferences;  // 0x4  tagblock.
        // -> Sldt_AirprobesEntry[]
        MapStructure::Tag::Block   Airprobes;  // 0x10  tagblock.
        // -> Sldt_UnknownEntry[]
        MapStructure::Tag::Block   Unknown_2;  // 0x1C  tagblock.
        // -> Sldt_UnknownEntry_2[]
        MapStructure::Tag::Block   Unknown_3;  // 0x28  tagblock.
        // -> Sldt_UnknownEntry_3[]
        MapStructure::Tag::Block   Unknown_4;  // 0x34  tagblock.
    };
    static_assert(sizeof(SldtData) == 0x40, "SldtData size mismatch");

}

#pragma pack(pop)
