// Auto-generated by TagTranspiler (GenerateObject.py)
// Source XML: zone.xml

export module Map.Tag.Type:Zone.Object;

import :Zone.Structure;
import std;

namespace
{
    using namespace Map::Tag::Type::Zone::Structure;
}

export namespace Map::Tag::Type::Zone::Object
{
    struct Zone_SizesObject : public Zone_SizesEntry
    {
        std::vector<Zone_Sizes_PartsEntry> Parts;
    };

    struct Zone_TagResourcesObject : public Zone_TagResourcesEntry
    {
        std::vector<Zone_TagResources_ResourceFixupsEntry> ResourceFixups;
        std::vector<Zone_TagResources_ResourceDefinitionFixupsEntry> ResourceDefinitionFixups;
    };

    struct Zone_DesignerZonesetsObject : public Zone_DesignerZonesetsEntry
    {
        std::vector<Zone_DesignerZonesets_RequiredRawPoolEntry> RequiredRawPool;
        std::vector<Zone_DesignerZonesets_OptionalRawPoolEntry> OptionalRawPool;
        std::vector<Zone_DesignerZonesets_OptionalRawPool2Entry> OptionalRawPool2;
        std::vector<Zone_DesignerZonesets_ResourceTypesEntry> ResourceTypes;
        std::vector<Zone_DesignerZonesets_RequiredTagPoolEntry> RequiredTagPool;
        std::vector<Zone_DesignerZonesets_OptionalTagPoolEntry> OptionalTagPool;
    };

    struct Zone_GlobalZonesetObject : public Zone_GlobalZonesetEntry
    {
        std::vector<Zone_GlobalZoneset_RequiredRawPoolEntry> RequiredRawPool;
        std::vector<Zone_GlobalZoneset_OptionalRawPoolEntry> OptionalRawPool;
        std::vector<Zone_GlobalZoneset_OptionalRawPool2Entry> OptionalRawPool2;
        std::vector<Zone_GlobalZoneset_ResourceTypesEntry> ResourceTypes;
        std::vector<Zone_GlobalZoneset_RequiredTagPoolEntry> RequiredTagPool;
        std::vector<Zone_GlobalZoneset_OptionalTagPoolEntry> OptionalTagPool;
    };

    struct Zone_UnattachedZonesetObject : public Zone_UnattachedZonesetEntry
    {
        std::vector<Zone_UnattachedZoneset_RequiredRawPoolEntry> RequiredRawPool;
        std::vector<Zone_UnattachedZoneset_OptionalRawPoolEntry> OptionalRawPool;
        std::vector<Zone_UnattachedZoneset_OptionalRawPool2Entry> OptionalRawPool2;
        std::vector<Zone_UnattachedZoneset_ResourceTypesEntry> ResourceTypes;
        std::vector<Zone_UnattachedZoneset_RequiredTagPoolEntry> RequiredTagPool;
        std::vector<Zone_UnattachedZoneset_OptionalTagPoolEntry> OptionalTagPool;
    };

    struct Zone_DiscForbiddenZonesetObject : public Zone_DiscForbiddenZonesetEntry
    {
        std::vector<Zone_DiscForbiddenZoneset_RequiredRawPoolEntry> RequiredRawPool;
        std::vector<Zone_DiscForbiddenZoneset_OptionalRawPoolEntry> OptionalRawPool;
        std::vector<Zone_DiscForbiddenZoneset_OptionalRawPool2Entry> OptionalRawPool2;
        std::vector<Zone_DiscForbiddenZoneset_ResourceTypesEntry> ResourceTypes;
        std::vector<Zone_DiscForbiddenZoneset_RequiredTagPoolEntry> RequiredTagPool;
        std::vector<Zone_DiscForbiddenZoneset_OptionalTagPoolEntry> OptionalTagPool;
    };

    struct Zone_DiscAlwaysStreamingZonesetObject : public Zone_DiscAlwaysStreamingZonesetEntry
    {
        std::vector<Zone_DiscAlwaysStreamingZoneset_RequiredRawPoolEntry> RequiredRawPool;
        std::vector<Zone_DiscAlwaysStreamingZoneset_OptionalRawPoolEntry> OptionalRawPool;
        std::vector<Zone_DiscAlwaysStreamingZoneset_OptionalRawPool2Entry> OptionalRawPool2;
        std::vector<Zone_DiscAlwaysStreamingZoneset_ResourceTypesEntry> ResourceTypes;
        std::vector<Zone_DiscAlwaysStreamingZoneset_RequiredTagPoolEntry> RequiredTagPool;
        std::vector<Zone_DiscAlwaysStreamingZoneset_OptionalTagPoolEntry> OptionalTagPool;
    };

    struct Zone_BspZonesetsObject : public Zone_BspZonesetsEntry
    {
        std::vector<Zone_BspZonesets_RequiredRawPoolEntry> RequiredRawPool;
        std::vector<Zone_BspZonesets_OptionalRawPoolEntry> OptionalRawPool;
        std::vector<Zone_BspZonesets_OptionalRawPool2Entry> OptionalRawPool2;
        std::vector<Zone_BspZonesets_ResourceTypesEntry> ResourceTypes;
        std::vector<Zone_BspZonesets_RequiredTagPoolEntry> RequiredTagPool;
        std::vector<Zone_BspZonesets_OptionalTagPoolEntry> OptionalTagPool;
    };

    struct Zone_BspZonesets2Object : public Zone_BspZonesets2Entry
    {
        std::vector<Zone_BspZonesets2_RequiredRawPoolEntry> RequiredRawPool;
        std::vector<Zone_BspZonesets2_OptionalRawPoolEntry> OptionalRawPool;
        std::vector<Zone_BspZonesets2_OptionalRawPool2Entry> OptionalRawPool2;
        std::vector<Zone_BspZonesets2_ResourceTypesEntry> ResourceTypes;
        std::vector<Zone_BspZonesets2_RequiredTagPoolEntry> RequiredTagPool;
        std::vector<Zone_BspZonesets2_OptionalTagPoolEntry> OptionalTagPool;
    };

    struct Zone_BspZonesets3Object : public Zone_BspZonesets3Entry
    {
        std::vector<Zone_BspZonesets3_RequiredRawPoolEntry> RequiredRawPool;
        std::vector<Zone_BspZonesets3_OptionalRawPoolEntry> OptionalRawPool;
        std::vector<Zone_BspZonesets3_OptionalRawPool2Entry> OptionalRawPool2;
        std::vector<Zone_BspZonesets3_ResourceTypesEntry> ResourceTypes;
        std::vector<Zone_BspZonesets3_RequiredTagPoolEntry> RequiredTagPool;
        std::vector<Zone_BspZonesets3_OptionalTagPoolEntry> OptionalTagPool;
    };

    struct Zone_CinematicZonesetsObject : public Zone_CinematicZonesetsEntry
    {
        std::vector<Zone_CinematicZonesets_RequiredRawPoolEntry> RequiredRawPool;
        std::vector<Zone_CinematicZonesets_OptionalRawPoolEntry> OptionalRawPool;
        std::vector<Zone_CinematicZonesets_OptionalRawPool2Entry> OptionalRawPool2;
        std::vector<Zone_CinematicZonesets_ResourceTypesEntry> ResourceTypes;
        std::vector<Zone_CinematicZonesets_RequiredTagPoolEntry> RequiredTagPool;
        std::vector<Zone_CinematicZonesets_OptionalTagPoolEntry> OptionalTagPool;
    };

    struct Zone_ScenarioZonesetsObject : public Zone_ScenarioZonesetsEntry
    {
        std::vector<Zone_ScenarioZonesets_RequiredRawPoolEntry> RequiredRawPool;
        std::vector<Zone_ScenarioZonesets_OptionalRawPoolEntry> OptionalRawPool;
        std::vector<Zone_ScenarioZonesets_OptionalRawPool2Entry> OptionalRawPool2;
        std::vector<Zone_ScenarioZonesets_ResourceTypesEntry> ResourceTypes;
        std::vector<Zone_ScenarioZonesets_RequiredTagPoolEntry> RequiredTagPool;
        std::vector<Zone_ScenarioZonesets_OptionalTagPoolEntry> OptionalTagPool;
    };

    struct ZoneObject
    {
        std::string  TagName;
        ZoneData Data;

        std::vector<Zone_ResourceTypesEntry> ResourceTypes;
        std::vector<Zone_ResourceStructureTypesEntry> ResourceStructureTypes;
        std::vector<Zone_CompressionCodecsEntry> CompressionCodecs;
        std::vector<Zone_ExternalCacheReferencesEntry> ExternalCacheReferences;
        std::vector<Zone_RawPagesEntry> RawPages;
        std::vector<Zone_SizesObject> Sizes;
        std::vector<Zone_UnknownEntry> Unknown;
        std::vector<Zone_SegmentsEntry> Segments;
        std::vector<Zone_TagResourcesObject> TagResources;
        std::vector<Zone_DesignerZonesetsObject> DesignerZonesets;
        std::vector<Zone_GlobalZonesetObject> GlobalZoneset;
        std::vector<Zone_UnattachedZonesetObject> UnattachedZoneset;
        std::vector<Zone_DiscForbiddenZonesetObject> DiscForbiddenZoneset;
        std::vector<Zone_DiscAlwaysStreamingZonesetObject> DiscAlwaysStreamingZoneset;
        std::vector<Zone_BspZonesetsObject> BspZonesets;
        std::vector<Zone_BspZonesets2Object> BspZonesets2;
        std::vector<Zone_BspZonesets3Object> BspZonesets3;
        std::vector<Zone_CinematicZonesetsObject> CinematicZonesets;
        std::vector<Zone_ScenarioZonesetsObject> ScenarioZonesets;
        std::vector<Zone_ScenarioZonesetGroupsEntry> ScenarioZonesetGroups;
        std::vector<Zone_ScenarioBspsEntry> ScenarioBsps;
        std::vector<Zone_UnknownEntry_2> Unknown_25;
        std::vector<Zone_PredictionAEntry> PredictionA;
        std::vector<Zone_PredictionBEntry> PredictionB;
        std::vector<Zone_PredictionCEntry> PredictionC;
        std::vector<Zone_PredictionDTagsEntry> PredictionDTags;
        std::vector<Zone_PredictionD2TagsEntry> PredictionD2Tags;
    };
}
