// Auto-generated by TagTranspiler (GenerateObject.py)
// Source XML: sbsp.xml

export module Map.Tag.System:Sbsp.Descriptor;

import Map.Tag.Type;
import Map.Reader.System;
import std;

namespace
{
    using namespace Map::Tag::Type::Sbsp::Structure;
    using namespace Map::Tag::Type::Sbsp::Object;
}

export namespace Map::Reader::System
{
    template <>
    struct GroupDescriptor<SbspObject>
    {
        using DataType = SbspData;

        template <typename TReader>
        static void ReadBlocks(
            std::ifstream& file,
            const TReader& reader,
            SbspObject& obj)
        {
            {
                auto disk_StructureSeams_0 = reader.template ReadBlock<Sbsp_StructureSeamsEntry>(file, obj.Data.StructureSeams);
                obj.StructureSeams.reserve(disk_StructureSeams_0.size());
                for (auto& diskEntry_0 : disk_StructureSeams_0)
                {
                    Sbsp_StructureSeamsObject entry_StructureSeams_0{static_cast<Sbsp_StructureSeamsEntry>(diskEntry_0)};
                    entry_StructureSeams_0.Unknown_5 = reader.template ReadBlock<Sbsp_StructureSeams_UnknownEntry>(file, diskEntry_0.Unknown_5);
                    entry_StructureSeams_0.SeamClusters = reader.template ReadBlock<Sbsp_StructureSeams_SeamClustersEntry>(file, diskEntry_0.SeamClusters);
                    obj.StructureSeams.push_back(entry_StructureSeams_0);
                }
            }
            obj.CollisionMaterials = reader.template ReadBlock<Sbsp_CollisionMaterialsEntry>(file, obj.Data.CollisionMaterials);
            obj.Unknown_21 = reader.template ReadBlock<Sbsp_UnknownEntry>(file, obj.Data.Unknown_21);
            obj.Unknown_22 = reader.template ReadBlock<Sbsp_UnknownEntry_2>(file, obj.Data.Unknown_22);
            {
                auto disk_ClusterPortals_0 = reader.template ReadBlock<Sbsp_ClusterPortalsEntry>(file, obj.Data.ClusterPortals);
                obj.ClusterPortals.reserve(disk_ClusterPortals_0.size());
                for (auto& diskEntry_0 : disk_ClusterPortals_0)
                {
                    Sbsp_ClusterPortalsObject entry_ClusterPortals_0{static_cast<Sbsp_ClusterPortalsEntry>(diskEntry_0)};
                    entry_ClusterPortals_0.Vertices = reader.template ReadBlock<Sbsp_ClusterPortals_VerticesEntry>(file, diskEntry_0.Vertices);
                    obj.ClusterPortals.push_back(entry_ClusterPortals_0);
                }
            }
            obj.DetailObjects = reader.template ReadBlock<Sbsp_DetailObjectsEntry>(file, obj.Data.DetailObjects);
            {
                auto disk_Clusters_0 = reader.template ReadBlock<Sbsp_ClustersEntry>(file, obj.Data.Clusters);
                obj.Clusters.reserve(disk_Clusters_0.size());
                for (auto& diskEntry_0 : disk_Clusters_0)
                {
                    Sbsp_ClustersObject entry_Clusters_0{static_cast<Sbsp_ClustersEntry>(diskEntry_0)};
                    entry_Clusters_0.Portals = reader.template ReadBlock<Sbsp_Clusters_PortalsEntry>(file, diskEntry_0.Portals);
                    entry_Clusters_0.Seams = reader.template ReadBlock<Sbsp_Clusters_SeamsEntry>(file, diskEntry_0.Seams);
                    {
                        auto disk_DecoratorGrids_1 = reader.template ReadBlock<Sbsp_Clusters_DecoratorGridsEntry>(file, diskEntry_0.DecoratorGrids);
                        entry_Clusters_0.DecoratorGrids.reserve(disk_DecoratorGrids_1.size());
                        for (auto& diskEntry_1 : disk_DecoratorGrids_1)
                        {
                            Sbsp_Clusters_DecoratorGridsObject entry_DecoratorGrids_1{static_cast<Sbsp_Clusters_DecoratorGridsEntry>(diskEntry_1)};
                            entry_DecoratorGrids_1.Unknown_2 = reader.template ReadBlock<Sbsp_Clusters_DecoratorGrids_UnknownEntry>(file, diskEntry_1.Unknown_2);
                            entry_Clusters_0.DecoratorGrids.push_back(entry_DecoratorGrids_1);
                        }
                    }
                    entry_Clusters_0.Unknown_21 = reader.template ReadBlock<Sbsp_Clusters_UnknownEntry>(file, diskEntry_0.Unknown_21);
                    {
                        auto disk_Unknown_1 = reader.template ReadBlock<Sbsp_Clusters_UnknownEntry_2>(file, diskEntry_0.Unknown_22);
                        entry_Clusters_0.Unknown_22.reserve(disk_Unknown_1.size());
                        for (auto& diskEntry_1 : disk_Unknown_1)
                        {
                            Sbsp_Clusters_UnknownObject_2 entry_Unknown_1{static_cast<Sbsp_Clusters_UnknownEntry_2>(diskEntry_1)};
                            entry_Unknown_1.Unknown_3 = reader.template ReadBlock<Sbsp_Clusters_Unknown_2_UnknownEntry>(file, diskEntry_1.Unknown_3);
                            entry_Clusters_0.Unknown_22.push_back(entry_Unknown_1);
                        }
                    }
                    obj.Clusters.push_back(entry_Clusters_0);
                }
            }
            obj.Materials = reader.template ReadBlock<Sbsp_MaterialsEntry>(file, obj.Data.Materials);
            obj.SkyOwnerCluster = reader.template ReadBlock<Sbsp_SkyOwnerClusterEntry>(file, obj.Data.SkyOwnerCluster);
            obj.BackgroundSoundEnvironmentPalette = reader.template ReadBlock<Sbsp_BackgroundSoundEnvironmentPaletteEntry>(file, obj.Data.BackgroundSoundEnvironmentPalette);
            obj.Markers = reader.template ReadBlock<Sbsp_MarkersEntry>(file, obj.Data.Markers);
            obj.Unknown_74 = reader.template ReadBlock<Sbsp_UnknownEntry_3>(file, obj.Data.Unknown_74);
            obj.RuntimeDecals = reader.template ReadBlock<Sbsp_RuntimeDecalsEntry>(file, obj.Data.RuntimeDecals);
            obj.EnvironmentObjectPalette = reader.template ReadBlock<Sbsp_EnvironmentObjectPaletteEntry>(file, obj.Data.EnvironmentObjectPalette);
            obj.EnvironmentObjects = reader.template ReadBlock<Sbsp_EnvironmentObjectsEntry>(file, obj.Data.EnvironmentObjects);
            {
                auto disk_InstancedGeometryGroups_0 = reader.template ReadBlock<Sbsp_InstancedGeometryGroupsEntry>(file, obj.Data.InstancedGeometryGroups);
                obj.InstancedGeometryGroups.reserve(disk_InstancedGeometryGroups_0.size());
                for (auto& diskEntry_0 : disk_InstancedGeometryGroups_0)
                {
                    Sbsp_InstancedGeometryGroupsObject entry_InstancedGeometryGroups_0{static_cast<Sbsp_InstancedGeometryGroupsEntry>(diskEntry_0)};
                    entry_InstancedGeometryGroups_0.Members = reader.template ReadBlock<Sbsp_InstancedGeometryGroups_MembersEntry>(file, diskEntry_0.Members);
                    obj.InstancedGeometryGroups.push_back(entry_InstancedGeometryGroups_0);
                }
            }
            {
                auto disk_InstancedGeometrySubGroups_0 = reader.template ReadBlock<Sbsp_InstancedGeometrySubGroupsEntry>(file, obj.Data.InstancedGeometrySubGroups);
                obj.InstancedGeometrySubGroups.reserve(disk_InstancedGeometrySubGroups_0.size());
                for (auto& diskEntry_0 : disk_InstancedGeometrySubGroups_0)
                {
                    Sbsp_InstancedGeometrySubGroupsObject entry_InstancedGeometrySubGroups_0{static_cast<Sbsp_InstancedGeometrySubGroupsEntry>(diskEntry_0)};
                    entry_InstancedGeometrySubGroups_0.Members = reader.template ReadBlock<Sbsp_InstancedGeometrySubGroups_MembersEntry>(file, diskEntry_0.Members);
                    obj.InstancedGeometrySubGroups.push_back(entry_InstancedGeometrySubGroups_0);
                }
            }
            obj.InstancedGeometryInstances = reader.template ReadBlock<Sbsp_InstancedGeometryInstancesEntry>(file, obj.Data.InstancedGeometryInstances);
            obj.Decorators = reader.template ReadBlock<Sbsp_DecoratorsEntry>(file, obj.Data.Decorators);
            {
                auto disk_Meshes_0 = reader.template ReadBlock<Sbsp_MeshesEntry>(file, obj.Data.Meshes);
                obj.Meshes.reserve(disk_Meshes_0.size());
                for (auto& diskEntry_0 : disk_Meshes_0)
                {
                    Sbsp_MeshesObject entry_Meshes_0{static_cast<Sbsp_MeshesEntry>(diskEntry_0)};
                    entry_Meshes_0.Parts = reader.template ReadBlock<Sbsp_Meshes_PartsEntry>(file, diskEntry_0.Parts);
                    entry_Meshes_0.Subparts = reader.template ReadBlock<Sbsp_Meshes_SubpartsEntry>(file, diskEntry_0.Subparts);
                    {
                        auto disk_InstanceBuckets_1 = reader.template ReadBlock<Sbsp_Meshes_InstanceBucketsEntry>(file, diskEntry_0.InstanceBuckets);
                        entry_Meshes_0.InstanceBuckets.reserve(disk_InstanceBuckets_1.size());
                        for (auto& diskEntry_1 : disk_InstanceBuckets_1)
                        {
                            Sbsp_Meshes_InstanceBucketsObject entry_InstanceBuckets_1{static_cast<Sbsp_Meshes_InstanceBucketsEntry>(diskEntry_1)};
                            entry_InstanceBuckets_1.Instances = reader.template ReadBlock<Sbsp_Meshes_InstanceBuckets_InstancesEntry>(file, diskEntry_1.Instances);
                            entry_Meshes_0.InstanceBuckets.push_back(entry_InstanceBuckets_1);
                        }
                    }
                    entry_Meshes_0.WaterIndicesStart = reader.template ReadBlock<Sbsp_Meshes_WaterIndicesStartEntry>(file, diskEntry_0.WaterIndicesStart);
                    obj.Meshes.push_back(entry_Meshes_0);
                }
            }
            obj.CompressionInfo = reader.template ReadBlock<Sbsp_CompressionInfoEntry>(file, obj.Data.CompressionInfo);
            obj.PartSortingPosition = reader.template ReadBlock<Sbsp_PartSortingPositionEntry>(file, obj.Data.PartSortingPosition);
            obj.UserData = reader.template ReadBlock<Sbsp_UserDataEntry>(file, obj.Data.UserData);
            {
                auto disk_PerMeshTemporary_0 = reader.template ReadBlock<Sbsp_PerMeshTemporaryEntry>(file, obj.Data.PerMeshTemporary);
                obj.PerMeshTemporary.reserve(disk_PerMeshTemporary_0.size());
                for (auto& diskEntry_0 : disk_PerMeshTemporary_0)
                {
                    Sbsp_PerMeshTemporaryObject entry_PerMeshTemporary_0{static_cast<Sbsp_PerMeshTemporaryEntry>(diskEntry_0)};
                    entry_PerMeshTemporary_0.RawVertices = reader.template ReadBlock<Sbsp_PerMeshTemporary_RawVerticesEntry>(file, diskEntry_0.RawVertices);
                    entry_PerMeshTemporary_0.RawIndices = reader.template ReadBlock<Sbsp_PerMeshTemporary_RawIndicesEntry>(file, diskEntry_0.RawIndices);
                    entry_PerMeshTemporary_0.RawIndices32 = reader.template ReadBlock<Sbsp_PerMeshTemporary_RawIndices32Entry>(file, diskEntry_0.RawIndices32);
                    {
                        auto disk_RawWaterData_1 = reader.template ReadBlock<Sbsp_PerMeshTemporary_RawWaterDataEntry>(file, diskEntry_0.RawWaterData);
                        entry_PerMeshTemporary_0.RawWaterData.reserve(disk_RawWaterData_1.size());
                        for (auto& diskEntry_1 : disk_RawWaterData_1)
                        {
                            Sbsp_PerMeshTemporary_RawWaterDataObject entry_RawWaterData_1{static_cast<Sbsp_PerMeshTemporary_RawWaterDataEntry>(diskEntry_1)};
                            entry_RawWaterData_1.RawWaterIndices = reader.template ReadBlock<Sbsp_PerMeshTemporary_RawWaterData_RawWaterIndicesEntry>(file, diskEntry_1.RawWaterIndices);
                            entry_RawWaterData_1.RawWaterVertices = reader.template ReadBlock<Sbsp_PerMeshTemporary_RawWaterData_RawWaterVerticesEntry>(file, diskEntry_1.RawWaterVertices);
                            entry_PerMeshTemporary_0.RawWaterData.push_back(entry_RawWaterData_1);
                        }
                    }
                    entry_PerMeshTemporary_0.RawImposterData = reader.template ReadBlock<Sbsp_PerMeshTemporary_RawImposterDataEntry>(file, diskEntry_0.RawImposterData);
                    entry_PerMeshTemporary_0.RawInstanceImposterVerts = reader.template ReadBlock<Sbsp_PerMeshTemporary_RawInstanceImposterVertsEntry>(file, diskEntry_0.RawInstanceImposterVerts);
                    obj.PerMeshTemporary.push_back(entry_PerMeshTemporary_0);
                }
            }
            {
                auto disk_PerMeshNodeMap_0 = reader.template ReadBlock<Sbsp_PerMeshNodeMapEntry>(file, obj.Data.PerMeshNodeMap);
                obj.PerMeshNodeMap.reserve(disk_PerMeshNodeMap_0.size());
                for (auto& diskEntry_0 : disk_PerMeshNodeMap_0)
                {
                    Sbsp_PerMeshNodeMapObject entry_PerMeshNodeMap_0{static_cast<Sbsp_PerMeshNodeMapEntry>(diskEntry_0)};
                    entry_PerMeshNodeMap_0.NodeMap = reader.template ReadBlock<Sbsp_PerMeshNodeMap_NodeMapEntry>(file, diskEntry_0.NodeMap);
                    obj.PerMeshNodeMap.push_back(entry_PerMeshNodeMap_0);
                }
            }
            {
                auto disk_PerMeshSubpartVisibility_0 = reader.template ReadBlock<Sbsp_PerMeshSubpartVisibilityEntry>(file, obj.Data.PerMeshSubpartVisibility);
                obj.PerMeshSubpartVisibility.reserve(disk_PerMeshSubpartVisibility_0.size());
                for (auto& diskEntry_0 : disk_PerMeshSubpartVisibility_0)
                {
                    Sbsp_PerMeshSubpartVisibilityObject entry_PerMeshSubpartVisibility_0{static_cast<Sbsp_PerMeshSubpartVisibilityEntry>(diskEntry_0)};
                    entry_PerMeshSubpartVisibility_0.BoundingSphere = reader.template ReadBlock<Sbsp_PerMeshSubpartVisibility_BoundingSphereEntry>(file, diskEntry_0.BoundingSphere);
                    obj.PerMeshSubpartVisibility.push_back(entry_PerMeshSubpartVisibility_0);
                }
            }
            obj.PerInstanceLightmapTexcoords = reader.template ReadBlock<Sbsp_PerInstanceLightmapTexcoordsEntry>(file, obj.Data.PerInstanceLightmapTexcoords);
            obj.WaterBoundingBox = reader.template ReadBlock<Sbsp_WaterBoundingBoxEntry>(file, obj.Data.WaterBoundingBox);
            obj.ConstantBufferInterop = reader.template ReadBlock<Sbsp_ConstantBufferInteropEntry>(file, obj.Data.ConstantBufferInterop);
            obj.Decals = reader.template ReadBlock<Sbsp_DecalsEntry>(file, obj.Data.Decals);
            obj.DecalProperties = reader.template ReadBlock<Sbsp_DecalPropertiesEntry>(file, obj.Data.DecalProperties);
            {
                auto disk_Meshes_0 = reader.template ReadBlock<Sbsp_MeshesEntry_2>(file, obj.Data.Meshes_2);
                obj.Meshes_2.reserve(disk_Meshes_0.size());
                for (auto& diskEntry_0 : disk_Meshes_0)
                {
                    Sbsp_MeshesObject_2 entry_Meshes_0{static_cast<Sbsp_MeshesEntry_2>(diskEntry_0)};
                    entry_Meshes_0.Parts = reader.template ReadBlock<Sbsp_Meshes_2_PartsEntry>(file, diskEntry_0.Parts);
                    entry_Meshes_0.Subparts = reader.template ReadBlock<Sbsp_Meshes_2_SubpartsEntry>(file, diskEntry_0.Subparts);
                    {
                        auto disk_InstanceBuckets_1 = reader.template ReadBlock<Sbsp_Meshes_2_InstanceBucketsEntry>(file, diskEntry_0.InstanceBuckets);
                        entry_Meshes_0.InstanceBuckets.reserve(disk_InstanceBuckets_1.size());
                        for (auto& diskEntry_1 : disk_InstanceBuckets_1)
                        {
                            Sbsp_Meshes_2_InstanceBucketsObject entry_InstanceBuckets_1{static_cast<Sbsp_Meshes_2_InstanceBucketsEntry>(diskEntry_1)};
                            entry_InstanceBuckets_1.Instances = reader.template ReadBlock<Sbsp_Meshes_2_InstanceBuckets_InstancesEntry>(file, diskEntry_1.Instances);
                            entry_Meshes_0.InstanceBuckets.push_back(entry_InstanceBuckets_1);
                        }
                    }
                    entry_Meshes_0.WaterIndicesStart = reader.template ReadBlock<Sbsp_Meshes_2_WaterIndicesStartEntry>(file, diskEntry_0.WaterIndicesStart);
                    obj.Meshes_2.push_back(entry_Meshes_0);
                }
            }
            obj.CompressionInfo_2 = reader.template ReadBlock<Sbsp_CompressionInfoEntry_2>(file, obj.Data.CompressionInfo_2);
            obj.PartSortingPosition_2 = reader.template ReadBlock<Sbsp_PartSortingPositionEntry_2>(file, obj.Data.PartSortingPosition_2);
            obj.UserData_2 = reader.template ReadBlock<Sbsp_UserDataEntry_2>(file, obj.Data.UserData_2);
            {
                auto disk_PerMeshTemporary_0 = reader.template ReadBlock<Sbsp_PerMeshTemporaryEntry_2>(file, obj.Data.PerMeshTemporary_2);
                obj.PerMeshTemporary_2.reserve(disk_PerMeshTemporary_0.size());
                for (auto& diskEntry_0 : disk_PerMeshTemporary_0)
                {
                    Sbsp_PerMeshTemporaryObject_2 entry_PerMeshTemporary_0{static_cast<Sbsp_PerMeshTemporaryEntry_2>(diskEntry_0)};
                    entry_PerMeshTemporary_0.RawVertices = reader.template ReadBlock<Sbsp_PerMeshTemporary_2_RawVerticesEntry>(file, diskEntry_0.RawVertices);
                    entry_PerMeshTemporary_0.RawIndices = reader.template ReadBlock<Sbsp_PerMeshTemporary_2_RawIndicesEntry>(file, diskEntry_0.RawIndices);
                    entry_PerMeshTemporary_0.RawIndices32 = reader.template ReadBlock<Sbsp_PerMeshTemporary_2_RawIndices32Entry>(file, diskEntry_0.RawIndices32);
                    {
                        auto disk_RawWaterData_1 = reader.template ReadBlock<Sbsp_PerMeshTemporary_2_RawWaterDataEntry>(file, diskEntry_0.RawWaterData);
                        entry_PerMeshTemporary_0.RawWaterData.reserve(disk_RawWaterData_1.size());
                        for (auto& diskEntry_1 : disk_RawWaterData_1)
                        {
                            Sbsp_PerMeshTemporary_2_RawWaterDataObject entry_RawWaterData_1{static_cast<Sbsp_PerMeshTemporary_2_RawWaterDataEntry>(diskEntry_1)};
                            entry_RawWaterData_1.RawWaterIndices = reader.template ReadBlock<Sbsp_PerMeshTemporary_2_RawWaterData_RawWaterIndicesEntry>(file, diskEntry_1.RawWaterIndices);
                            entry_RawWaterData_1.RawWaterVertices = reader.template ReadBlock<Sbsp_PerMeshTemporary_2_RawWaterData_RawWaterVerticesEntry>(file, diskEntry_1.RawWaterVertices);
                            entry_PerMeshTemporary_0.RawWaterData.push_back(entry_RawWaterData_1);
                        }
                    }
                    entry_PerMeshTemporary_0.RawImposterData = reader.template ReadBlock<Sbsp_PerMeshTemporary_2_RawImposterDataEntry>(file, diskEntry_0.RawImposterData);
                    entry_PerMeshTemporary_0.RawInstanceImposterVerts = reader.template ReadBlock<Sbsp_PerMeshTemporary_2_RawInstanceImposterVertsEntry>(file, diskEntry_0.RawInstanceImposterVerts);
                    obj.PerMeshTemporary_2.push_back(entry_PerMeshTemporary_0);
                }
            }
            {
                auto disk_PerMeshNodeMap_0 = reader.template ReadBlock<Sbsp_PerMeshNodeMapEntry_2>(file, obj.Data.PerMeshNodeMap_2);
                obj.PerMeshNodeMap_2.reserve(disk_PerMeshNodeMap_0.size());
                for (auto& diskEntry_0 : disk_PerMeshNodeMap_0)
                {
                    Sbsp_PerMeshNodeMapObject_2 entry_PerMeshNodeMap_0{static_cast<Sbsp_PerMeshNodeMapEntry_2>(diskEntry_0)};
                    entry_PerMeshNodeMap_0.NodeMap = reader.template ReadBlock<Sbsp_PerMeshNodeMap_2_NodeMapEntry>(file, diskEntry_0.NodeMap);
                    obj.PerMeshNodeMap_2.push_back(entry_PerMeshNodeMap_0);
                }
            }
            {
                auto disk_PerMeshSubpartVisibility_0 = reader.template ReadBlock<Sbsp_PerMeshSubpartVisibilityEntry_2>(file, obj.Data.PerMeshSubpartVisibility_2);
                obj.PerMeshSubpartVisibility_2.reserve(disk_PerMeshSubpartVisibility_0.size());
                for (auto& diskEntry_0 : disk_PerMeshSubpartVisibility_0)
                {
                    Sbsp_PerMeshSubpartVisibilityObject_2 entry_PerMeshSubpartVisibility_0{static_cast<Sbsp_PerMeshSubpartVisibilityEntry_2>(diskEntry_0)};
                    entry_PerMeshSubpartVisibility_0.BoundingSphere = reader.template ReadBlock<Sbsp_PerMeshSubpartVisibility_2_BoundingSphereEntry>(file, diskEntry_0.BoundingSphere);
                    obj.PerMeshSubpartVisibility_2.push_back(entry_PerMeshSubpartVisibility_0);
                }
            }
            obj.PerInstanceLightmapTexcoords_2 = reader.template ReadBlock<Sbsp_PerInstanceLightmapTexcoordsEntry_2>(file, obj.Data.PerInstanceLightmapTexcoords_2);
            obj.WaterBoundingBox_2 = reader.template ReadBlock<Sbsp_WaterBoundingBoxEntry_2>(file, obj.Data.WaterBoundingBox_2);
            obj.ConstantBufferInterop_2 = reader.template ReadBlock<Sbsp_ConstantBufferInteropEntry_2>(file, obj.Data.ConstantBufferInterop_2);
            {
                auto disk_UnknownSoundClustersA_0 = reader.template ReadBlock<Sbsp_UnknownSoundClustersAEntry>(file, obj.Data.UnknownSoundClustersA);
                obj.UnknownSoundClustersA.reserve(disk_UnknownSoundClustersA_0.size());
                for (auto& diskEntry_0 : disk_UnknownSoundClustersA_0)
                {
                    Sbsp_UnknownSoundClustersAObject entry_UnknownSoundClustersA_0{static_cast<Sbsp_UnknownSoundClustersAEntry>(diskEntry_0)};
                    entry_UnknownSoundClustersA_0.PortalDesignators = reader.template ReadBlock<Sbsp_UnknownSoundClustersA_PortalDesignatorsEntry>(file, diskEntry_0.PortalDesignators);
                    entry_UnknownSoundClustersA_0.InteriorClusterIndices = reader.template ReadBlock<Sbsp_UnknownSoundClustersA_InteriorClusterIndicesEntry>(file, diskEntry_0.InteriorClusterIndices);
                    obj.UnknownSoundClustersA.push_back(entry_UnknownSoundClustersA_0);
                }
            }
            obj.TransparentPlanes = reader.template ReadBlock<Sbsp_TransparentPlanesEntry>(file, obj.Data.TransparentPlanes);
            {
                auto disk_CollisionMoppCodes_0 = reader.template ReadBlock<Sbsp_CollisionMoppCodesEntry>(file, obj.Data.CollisionMoppCodes);
                obj.CollisionMoppCodes.reserve(disk_CollisionMoppCodes_0.size());
                for (auto& diskEntry_0 : disk_CollisionMoppCodes_0)
                {
                    Sbsp_CollisionMoppCodesObject entry_CollisionMoppCodes_0{static_cast<Sbsp_CollisionMoppCodesEntry>(diskEntry_0)};
                    entry_CollisionMoppCodes_0.MoppData = reader.template ReadBlock<Sbsp_CollisionMoppCodes_MoppDataEntry>(file, diskEntry_0.MoppData);
                    obj.CollisionMoppCodes.push_back(entry_CollisionMoppCodes_0);
                }
            }
            {
                auto disk_BreakableSurfaceMoppCodes_0 = reader.template ReadBlock<Sbsp_BreakableSurfaceMoppCodesEntry>(file, obj.Data.BreakableSurfaceMoppCodes);
                obj.BreakableSurfaceMoppCodes.reserve(disk_BreakableSurfaceMoppCodes_0.size());
                for (auto& diskEntry_0 : disk_BreakableSurfaceMoppCodes_0)
                {
                    Sbsp_BreakableSurfaceMoppCodesObject entry_BreakableSurfaceMoppCodes_0{static_cast<Sbsp_BreakableSurfaceMoppCodesEntry>(diskEntry_0)};
                    entry_BreakableSurfaceMoppCodes_0.MoppData = reader.template ReadBlock<Sbsp_BreakableSurfaceMoppCodes_MoppDataEntry>(file, diskEntry_0.MoppData);
                    obj.BreakableSurfaceMoppCodes.push_back(entry_BreakableSurfaceMoppCodes_0);
                }
            }
            obj.BreakableSurfaceKeyTable = reader.template ReadBlock<Sbsp_BreakableSurfaceKeyTableEntry>(file, obj.Data.BreakableSurfaceKeyTable);
            {
                auto disk_Meshes_0 = reader.template ReadBlock<Sbsp_MeshesEntry_3>(file, obj.Data.Meshes_3);
                obj.Meshes_3.reserve(disk_Meshes_0.size());
                for (auto& diskEntry_0 : disk_Meshes_0)
                {
                    Sbsp_MeshesObject_3 entry_Meshes_0{static_cast<Sbsp_MeshesEntry_3>(diskEntry_0)};
                    entry_Meshes_0.Parts = reader.template ReadBlock<Sbsp_Meshes_3_PartsEntry>(file, diskEntry_0.Parts);
                    entry_Meshes_0.Subparts = reader.template ReadBlock<Sbsp_Meshes_3_SubpartsEntry>(file, diskEntry_0.Subparts);
                    {
                        auto disk_InstanceBuckets_1 = reader.template ReadBlock<Sbsp_Meshes_3_InstanceBucketsEntry>(file, diskEntry_0.InstanceBuckets);
                        entry_Meshes_0.InstanceBuckets.reserve(disk_InstanceBuckets_1.size());
                        for (auto& diskEntry_1 : disk_InstanceBuckets_1)
                        {
                            Sbsp_Meshes_3_InstanceBucketsObject entry_InstanceBuckets_1{static_cast<Sbsp_Meshes_3_InstanceBucketsEntry>(diskEntry_1)};
                            entry_InstanceBuckets_1.Instances = reader.template ReadBlock<Sbsp_Meshes_3_InstanceBuckets_InstancesEntry>(file, diskEntry_1.Instances);
                            entry_Meshes_0.InstanceBuckets.push_back(entry_InstanceBuckets_1);
                        }
                    }
                    entry_Meshes_0.WaterIndicesStart = reader.template ReadBlock<Sbsp_Meshes_3_WaterIndicesStartEntry>(file, diskEntry_0.WaterIndicesStart);
                    obj.Meshes_3.push_back(entry_Meshes_0);
                }
            }
            obj.CompressionInfo_3 = reader.template ReadBlock<Sbsp_CompressionInfoEntry_3>(file, obj.Data.CompressionInfo_3);
            obj.PartSortingPosition_3 = reader.template ReadBlock<Sbsp_PartSortingPositionEntry_3>(file, obj.Data.PartSortingPosition_3);
            obj.UserData_3 = reader.template ReadBlock<Sbsp_UserDataEntry_3>(file, obj.Data.UserData_3);
            {
                auto disk_PerMeshTemporary_0 = reader.template ReadBlock<Sbsp_PerMeshTemporaryEntry_3>(file, obj.Data.PerMeshTemporary_3);
                obj.PerMeshTemporary_3.reserve(disk_PerMeshTemporary_0.size());
                for (auto& diskEntry_0 : disk_PerMeshTemporary_0)
                {
                    Sbsp_PerMeshTemporaryObject_3 entry_PerMeshTemporary_0{static_cast<Sbsp_PerMeshTemporaryEntry_3>(diskEntry_0)};
                    entry_PerMeshTemporary_0.RawVertices = reader.template ReadBlock<Sbsp_PerMeshTemporary_3_RawVerticesEntry>(file, diskEntry_0.RawVertices);
                    entry_PerMeshTemporary_0.RawIndices = reader.template ReadBlock<Sbsp_PerMeshTemporary_3_RawIndicesEntry>(file, diskEntry_0.RawIndices);
                    entry_PerMeshTemporary_0.RawIndices32 = reader.template ReadBlock<Sbsp_PerMeshTemporary_3_RawIndices32Entry>(file, diskEntry_0.RawIndices32);
                    {
                        auto disk_RawWaterData_1 = reader.template ReadBlock<Sbsp_PerMeshTemporary_3_RawWaterDataEntry>(file, diskEntry_0.RawWaterData);
                        entry_PerMeshTemporary_0.RawWaterData.reserve(disk_RawWaterData_1.size());
                        for (auto& diskEntry_1 : disk_RawWaterData_1)
                        {
                            Sbsp_PerMeshTemporary_3_RawWaterDataObject entry_RawWaterData_1{static_cast<Sbsp_PerMeshTemporary_3_RawWaterDataEntry>(diskEntry_1)};
                            entry_RawWaterData_1.RawWaterIndices = reader.template ReadBlock<Sbsp_PerMeshTemporary_3_RawWaterData_RawWaterIndicesEntry>(file, diskEntry_1.RawWaterIndices);
                            entry_RawWaterData_1.RawWaterVertices = reader.template ReadBlock<Sbsp_PerMeshTemporary_3_RawWaterData_RawWaterVerticesEntry>(file, diskEntry_1.RawWaterVertices);
                            entry_PerMeshTemporary_0.RawWaterData.push_back(entry_RawWaterData_1);
                        }
                    }
                    entry_PerMeshTemporary_0.RawImposterData = reader.template ReadBlock<Sbsp_PerMeshTemporary_3_RawImposterDataEntry>(file, diskEntry_0.RawImposterData);
                    entry_PerMeshTemporary_0.RawInstanceImposterVerts = reader.template ReadBlock<Sbsp_PerMeshTemporary_3_RawInstanceImposterVertsEntry>(file, diskEntry_0.RawInstanceImposterVerts);
                    obj.PerMeshTemporary_3.push_back(entry_PerMeshTemporary_0);
                }
            }
            {
                auto disk_PerMeshNodeMap_0 = reader.template ReadBlock<Sbsp_PerMeshNodeMapEntry_3>(file, obj.Data.PerMeshNodeMap_3);
                obj.PerMeshNodeMap_3.reserve(disk_PerMeshNodeMap_0.size());
                for (auto& diskEntry_0 : disk_PerMeshNodeMap_0)
                {
                    Sbsp_PerMeshNodeMapObject_3 entry_PerMeshNodeMap_0{static_cast<Sbsp_PerMeshNodeMapEntry_3>(diskEntry_0)};
                    entry_PerMeshNodeMap_0.NodeMap = reader.template ReadBlock<Sbsp_PerMeshNodeMap_3_NodeMapEntry>(file, diskEntry_0.NodeMap);
                    obj.PerMeshNodeMap_3.push_back(entry_PerMeshNodeMap_0);
                }
            }
            {
                auto disk_PerMeshSubpartVisibility_0 = reader.template ReadBlock<Sbsp_PerMeshSubpartVisibilityEntry_3>(file, obj.Data.PerMeshSubpartVisibility_3);
                obj.PerMeshSubpartVisibility_3.reserve(disk_PerMeshSubpartVisibility_0.size());
                for (auto& diskEntry_0 : disk_PerMeshSubpartVisibility_0)
                {
                    Sbsp_PerMeshSubpartVisibilityObject_3 entry_PerMeshSubpartVisibility_0{static_cast<Sbsp_PerMeshSubpartVisibilityEntry_3>(diskEntry_0)};
                    entry_PerMeshSubpartVisibility_0.BoundingSphere = reader.template ReadBlock<Sbsp_PerMeshSubpartVisibility_3_BoundingSphereEntry>(file, diskEntry_0.BoundingSphere);
                    obj.PerMeshSubpartVisibility_3.push_back(entry_PerMeshSubpartVisibility_0);
                }
            }
            obj.PerInstanceLightmapTexcoords_3 = reader.template ReadBlock<Sbsp_PerInstanceLightmapTexcoordsEntry_3>(file, obj.Data.PerInstanceLightmapTexcoords_3);
            obj.WaterBoundingBox_3 = reader.template ReadBlock<Sbsp_WaterBoundingBoxEntry_3>(file, obj.Data.WaterBoundingBox_3);
            obj.ConstantBufferInterop_3 = reader.template ReadBlock<Sbsp_ConstantBufferInteropEntry_3>(file, obj.Data.ConstantBufferInterop_3);
        }
    };
}
