// Auto-generated by TagTranspiler (GenerateOffset.py)
// Source XML: mode.xml
// Base size: 0x264.

export module Map.Tag.Type:Mode.Offset;

import std;

export namespace Map::Tag::Type::Mode::Offset
{
    constexpr std::size_t k_Name                                        = 0x0;  // StringID.
    constexpr std::size_t k_Flags                                       = 0x4;  // flags16. [Bit 0=0, Bit 1=1, Has Node Maps=2, Bit 3=3, Bit 4=4, Has Fur Shader=5, Bit 6=6, Bit 7=7, Bit 8=8, Bit 9=9, Bit 10=10, Bit 11=11, Bit 12=12, Bit 13=13, Bit 14=14, Bit 15=15]
    constexpr std::size_t k_Version                                     = 0x6;  // uint16.
    constexpr std::size_t k_ImportInfoChecksum                          = 0x8;  // int32.
    namespace Regions
    {
        // Array data.
        constexpr std::size_t k_Base      = 0xC;
        constexpr std::size_t k_EntrySize = 0x10;

        constexpr std::size_t k_Name                                        = 0x0;  // StringID.
        namespace Permutations
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x4;
            constexpr std::size_t k_EntrySize = 0x18;

            constexpr std::size_t k_Name                                        = 0x0;  // StringID.
            constexpr std::size_t k_MeshIndex                                   = 0x4;  // int16.
            constexpr std::size_t k_MeshCount                                   = 0x6;  // int16.
            constexpr std::size_t k_InstanceMask1                               = 0x8;  // flags32. [Instance 0=0, Instance 1=1, Instance 2=2, Instance 3=3, Instance 4=4, Instance 5=5, Instance 6=6, Instance 7=7, Instance 8=8, Instance 9=9, Instance 10=10, Instance 11=11, Instance 12=12, Instance 13=13, Instance 14=14, Instance 15=15, Instance 16=16, Instance 17=17, Instance 18=18, Instance 19=19, Instance 20=20, Instance 21=21, Instance 22=22, Instance 23=23, Instance 24=24, Instance 25=25, Instance 26=26, Instance 27=27, Instance 28=28, Instance 29=29, Instance 30=30, Instance 31=31]
            constexpr std::size_t k_InstanceMask2                               = 0xC;  // flags32. [Instance 32=0, Instance 33=1, Instance 34=2, Instance 35=3, Instance 36=4, Instance 37=5, Instance 38=6, Instance 39=7, Instance 40=8, Instance 41=9, Instance 42=10, Instance 43=11, Instance 44=12, Instance 45=13, Instance 46=14, Instance 47=15, Instance 48=16, Instance 49=17, Instance 50=18, Instance 51=19, Instance 52=20, Instance 53=21, Instance 54=22, Instance 55=23, Instance 56=24, Instance 57=25, Instance 58=26, Instance 59=27, Instance 60=28, Instance 61=29, Instance 62=30, Instance 63=31]
            constexpr std::size_t k_InstanceMask3                               = 0x10;  // flags32. [Instance 64=0, Instance 65=1, Instance 66=2, Instance 67=3, Instance 68=4, Instance 69=5, Instance 70=6, Instance 71=7, Instance 72=8, Instance 73=9, Instance 74=10, Instance 75=11, Instance 76=12, Instance 77=13, Instance 78=14, Instance 79=15, Instance 80=16, Instance 81=17, Instance 82=18, Instance 83=19, Instance 84=20, Instance 85=21, Instance 86=22, Instance 87=23, Instance 88=24, Instance 89=25, Instance 90=26, Instance 91=27, Instance 92=28, Instance 93=29, Instance 94=30, Instance 95=31]
            constexpr std::size_t k_InstanceMask4                               = 0x14;  // flags32. [Instance 96=0, Instance 97=1, Instance 98=2, Instance 99=3, Instance 100=4, Instance 101=5, Instance 102=6, Instance 103=7, Instance 104=8, Instance 105=9, Instance 106=10, Instance 107=11, Instance 108=12, Instance 109=13, Instance 110=14, Instance 111=15, Instance 112=16, Instance 113=17, Instance 114=18, Instance 115=19, Instance 116=20, Instance 117=21, Instance 118=22, Instance 119=23, Instance 120=24, Instance 121=25, Instance 122=26, Instance 123=27, Instance 124=28, Instance 125=29, Instance 126=30, Instance 127=31]

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }


        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_L1SectionGroupIndex                         = 0x18;  // int8.
    constexpr std::size_t k_L2SectionGroupIndex                         = 0x19;  // int8.
    constexpr std::size_t k_Unknown                                     = 0x1A;  // int16.
    constexpr std::size_t k_InstanceMeshIndex                           = 0x1C;  // int32.
    namespace InstancePlacements
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x20;
        constexpr std::size_t k_EntrySize = 0x3C;

        constexpr std::size_t k_Name                                        = 0x0;  // StringID.
        constexpr std::size_t k_NodeIndex                                   = 0x4;  // int32.
        constexpr std::size_t k_Scale                                       = 0x8;  // float32.
        constexpr std::size_t k_Forward                                     = 0xC;  // vector3.
        constexpr std::size_t k_Left                                        = 0x18;  // vector3.
        constexpr std::size_t k_Up                                          = 0x24;  // vector3.
        constexpr std::size_t k_Position                                    = 0x30;  // point3.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_NodeListChecksum                            = 0x2C;  // int32.
    namespace Nodes
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x30;
        constexpr std::size_t k_EntrySize = 0x60;

        constexpr std::size_t k_Name                                        = 0x0;  // StringID.
        constexpr std::size_t k_ParentNodeIndex                             = 0x4;  // int16.
        constexpr std::size_t k_FirstChildNodeIndex                         = 0x6;  // int16.
        constexpr std::size_t k_NextSiblingNodeIndex                        = 0x8;  // int16.
        constexpr std::size_t k_Unknown                                     = 0xA;  // int16.
        constexpr std::size_t k_DefaultTranslation                          = 0xC;  // point3.
        constexpr std::size_t k_DefaultRotation                             = 0x18;  // vector4.
        constexpr std::size_t k_InverseScale                                = 0x28;  // float32.
        constexpr std::size_t k_InverseForward                              = 0x2C;  // vector3.
        constexpr std::size_t k_InverseLeft                                 = 0x38;  // vector3.
        constexpr std::size_t k_InverseUp                                   = 0x44;  // vector3.
        constexpr std::size_t k_InversePosition                             = 0x50;  // point3.
        constexpr std::size_t k_DistanceFromParent                          = 0x5C;  // float32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace MarkerGroups
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x3C;
        constexpr std::size_t k_EntrySize = 0x10;

        constexpr std::size_t k_Name                                        = 0x0;  // StringID.
        namespace Markers
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x4;
            constexpr std::size_t k_EntrySize = 0x30;

            constexpr std::size_t k_RegionIndex                                 = 0x0;  // int8.
            constexpr std::size_t k_PermutationIndex                            = 0x1;  // int8.
            constexpr std::size_t k_NodeIndex                                   = 0x2;  // int8.
            constexpr std::size_t k_Flags                                       = 0x3;  // flags8. [Has Node Relative Direction=0]
            constexpr std::size_t k_Translation                                 = 0x4;  // point3.
            constexpr std::size_t k_Rotation                                    = 0x10;  // vector4.
            constexpr std::size_t k_Scale                                       = 0x20;  // float32.
            constexpr std::size_t k_Direction                                   = 0x24;  // vector3.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }


        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace Materials
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x48;
        constexpr std::size_t k_EntrySize = 0x2C;

        constexpr std::size_t k_RenderMethod                                = 0x0;  // TagReference.
        constexpr std::size_t k_ImportedMaterialIndex                       = 0x10;  // int32.
        constexpr std::size_t k_LightmapResolutionScale                     = 0x14;  // float32.
        constexpr std::size_t k_LightmapAdditiveTransparencyColor           = 0x18;  // int32.
        constexpr std::size_t k_LightmapTranslucencyTintColor               = 0x1C;  // int32.
        constexpr std::size_t k_LightmapAnalyticalLightAbsorb               = 0x20;  // float32.
        constexpr std::size_t k_LightmapNormalLightAbsorb                   = 0x24;  // float32.
        constexpr std::size_t k_LightmapFlags                               = 0x28;  // flags8. [Ignore Default Resolution Scale=0, Transparency Override=1, Lighting From Both Sides=2, Version 1=3]
        constexpr std::size_t k_BreakableSurfaceIndex                       = 0x29;  // int8.
        constexpr std::size_t k_LightmapChartGroupIndex                     = 0x2A;  // int16.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_Unknown_2                                   = 0x54;  // undefined.
    constexpr std::size_t k_Unknown_3                                   = 0x58;  // undefined.
    constexpr std::size_t k_Unknown_4                                   = 0x5C;  // undefined.
    constexpr std::size_t k_DontDrawOverCameraCosineAngle               = 0x60;  // float32.
    constexpr std::size_t k_Flags_2                                     = 0x64;  // flags32. [Processed=0, Available=1, Has Valid Budgets (Really)=2, Manual Resource Creation=3, Keep Raw Geometry=4, Don't Use Compressed Vertex Positions=5]
    namespace Meshes
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x68;
        constexpr std::size_t k_EntrySize = 0x5C;

        namespace Parts
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x0;
            constexpr std::size_t k_EntrySize = 0x18;

            constexpr std::size_t k_RenderMaterialIndex                         = 0x0;  // int16.
            constexpr std::size_t k_TransparentSortingIndex                     = 0x2;  // int16.
            constexpr std::size_t k_IndexStart                                  = 0x4;  // uint32.
            constexpr std::size_t k_IndexCount                                  = 0x8;  // uint32.
            constexpr std::size_t k_SubpartStart                                = 0xC;  // int16.
            constexpr std::size_t k_SubpartCount                                = 0xE;  // uint16.
            constexpr std::size_t k_PartType                                    = 0x10;  // int8.
            constexpr std::size_t k_SpecializedRender                           = 0x11;  // enum8. [None=0x0, Fail=0x1, Fur=0x2, Fur Stencil=0x3, Decal=0x4, Shield=0x5, Water=0x6, Lightmap Only=0x7, Hologram=0x8]
            constexpr std::size_t k_PartFlags                                   = 0x12;  // flags16. [Is Water Surface=0, Per Vertex Lightmap Part=1, Debug Flag Instance Part=2, Subparts Has Uberlights Info=3, Draw Cull Distance Medium=4, Draw Cull Distance Close=5, Draw Cull Rendering Shields=6, Cannot Single Pass Render=7, Is Transparent=8, Cannot Two Pass=9, Transparent Should Output Depth For DOF=10, Do Not Include In Static Lightmap=11, Do Not Include In PVS Generation=12, Draw Cull Rendering Active Camo=13]
            constexpr std::size_t k_BudgetVertexCount                           = 0x14;  // uint16.
            constexpr std::size_t k_Tessellation                                = 0x16;  // enum16. [None=0x0, Fixed x4 Faces=0x1, Fixed x9 Faces=0x2, Fixed x36 Faces=0x3]

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace Subparts
        {
            // Array data.
            constexpr std::size_t k_Base      = 0xC;
            constexpr std::size_t k_EntrySize = 0x10;

            constexpr std::size_t k_IndexStart                                  = 0x0;  // uint32.
            constexpr std::size_t k_IndexCount                                  = 0x4;  // uint32.
            constexpr std::size_t k_PartIndex                                   = 0x8;  // int16.
            constexpr std::size_t k_BudgetVertexCount                           = 0xA;  // uint16.
            constexpr std::size_t k_AnalyticalLightIndex                        = 0xC;  // uint32.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        constexpr std::size_t k_VertexBufferIndex1                          = 0x18;  // int16.
        constexpr std::size_t k_VertexBufferIndex2                          = 0x1A;  // int16.
        constexpr std::size_t k_VertexBufferIndex3                          = 0x1C;  // int16.
        constexpr std::size_t k_VertexBufferIndex4                          = 0x1E;  // int16.
        constexpr std::size_t k_VertexBufferIndex5                          = 0x20;  // int16.
        constexpr std::size_t k_VertexBufferIndex6                          = 0x22;  // int16.
        constexpr std::size_t k_VertexBufferIndex7                          = 0x24;  // int16.
        constexpr std::size_t k_VertexBufferIndex8                          = 0x26;  // int16.
        constexpr std::size_t k_IndexBufferIndex                            = 0x28;  // int16.
        constexpr std::size_t k_IndexBufferTessellationIndex                = 0x2A;  // int16.
        constexpr std::size_t k_MeshFlags                                   = 0x2C;  // flags16. [Mesh Has Vertex Color=0, Use Region Index For Sorting=1, Use Vertex Buffers For Indices=2, Mesh Has Per-Instance Lighting (Do Not Modify)=3, Mesh Is Unindexed (Do Not Modify)=4, Subpart Were Merged=5, Mesh Has Fur=6, Mesh Has Decal=7, Mesh Doesn't Use Compressed Position=8, Use Uncompressed Vertex Format=9, Bit 10=10, Bit 11=11, Bit 12=12, Bit 13=13, Bit 14=14, Bit 15=15]
        constexpr std::size_t k_RigidNodeIndex                              = 0x2E;  // int8.
        constexpr std::size_t k_VertexType                                  = 0x2F;  // enum8. [World=0x0, Rigid=0x1, Skinned=0x2, Particle Model=0x3, Flat World=0x4, Flat Rigid=0x5, Flat Skinned=0x6, Screen=0x7, Debug=0x8, Transparent=0x9, Particle=0xA, Contrail=0xB, Light Volume=0xC, Chud Simple=0xD, Chud Fancy=0xE, Decorator=0xF, Tiny Position=0x10, Patchy Fog=0x11, Water=0x12, Ripple=0x13, Implicit=0x14, Beam=0x15, World Tessellated=0x16, Rigid Tessellated=0x17, Skinned Tessellated=0x18, Shader Cache=0x19, Structure Instance Imposter=0x1A, Object Imposter=0x1B, Rigid Compressed=0x1C, Skinned Compressed=0x1D, Light Volume Precompiled=0x1E]
        constexpr std::size_t k_PrtType                                     = 0x30;  // enum8. [None=0x0, Ambient=0x1, Linear=0x2, Quadratic=0x3]
        constexpr std::size_t k_LightingPolicy                              = 0x31;  // enum8. [Vertex Color=0x0, Single Probe=0x1, PRT Ambient=0x2]
        constexpr std::size_t k_IndexBufferType                             = 0x32;  // enum8. [Point List=0x0, Line List=0x1, Line Strip=0x2, Triangle List=0x3, Triangle Fan=0x4, Triangle Strip=0x5]
        constexpr std::size_t k_Unknown                                     = 0x33;  // int8.
        namespace InstanceBuckets
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x34;
            constexpr std::size_t k_EntrySize = 0x10;

            constexpr std::size_t k_MeshIndex                                   = 0x0;  // int16.
            constexpr std::size_t k_DefinitionIndex                             = 0x2;  // int16.
            namespace Instances
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x4;
                constexpr std::size_t k_EntrySize = 0x2;

                constexpr std::size_t k_InstanceIndex                               = 0x0;  // int16.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }


            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace WaterIndicesStart
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x40;
            constexpr std::size_t k_EntrySize = 0x2;

            constexpr std::size_t k_Short                                       = 0x0;  // int16.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        constexpr std::size_t k_BoundingRadius                              = 0x4C;  // float32.
        constexpr std::size_t k_BoundingOffset                              = 0x50;  // point3.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace CompressionInfo
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x74;
        constexpr std::size_t k_EntrySize = 0x34;

        constexpr std::size_t k_CompressionFlags                            = 0x0;  // flags16. [Compressed Position=0, Compressed Texcoord=1, Compression Optimized=2]
        constexpr std::size_t k_Unknown                                     = 0x2;  // int16.
        constexpr std::size_t k_PositionBoundsX                             = 0x4;  // rangef.
        constexpr std::size_t k_PositionBoundsY                             = 0xC;  // rangef.
        constexpr std::size_t k_PositionBoundsZ                             = 0x14;  // rangef.
        constexpr std::size_t k_TexcoordBoundsX                             = 0x1C;  // rangef.
        constexpr std::size_t k_TexcoordBoundsY                             = 0x24;  // rangef.
        constexpr std::size_t k_Unknown_2                                   = 0x2C;  // float32.
        constexpr std::size_t k_Unknown_3                                   = 0x30;  // float32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace PartSortingPosition
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x80;
        constexpr std::size_t k_EntrySize = 0x30;

        constexpr std::size_t k_Plane                                       = 0x0;  // plane3.
        constexpr std::size_t k_Position                                    = 0x10;  // point3.
        constexpr std::size_t k_Radius                                      = 0x1C;  // float32.
        constexpr std::size_t k_NodeIndex1                                  = 0x20;  // int8.
        constexpr std::size_t k_NodeIndex2                                  = 0x21;  // int8.
        constexpr std::size_t k_NodeIndex3                                  = 0x22;  // int8.
        constexpr std::size_t k_NodeIndex4                                  = 0x23;  // int8.
        constexpr std::size_t k_NodeWeight1                                 = 0x24;  // float32.
        constexpr std::size_t k_NodeWeight2                                 = 0x28;  // float32.
        constexpr std::size_t k_NodeWeight3                                 = 0x2C;  // float32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace UserData
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x8C;
        constexpr std::size_t k_EntrySize = 0x18;

        constexpr std::size_t k_DataType                                    = 0x0;  // enum8. [PRT Info=0x0]
        constexpr std::size_t k_DataCount                                   = 0x1;  // int8.
        constexpr std::size_t k_DataSize                                    = 0x2;  // uint16.
        constexpr std::size_t k_UserData                                    = 0x4;  // DataReference.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace PerMeshTemporary
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x98;
        constexpr std::size_t k_EntrySize = 0x54;

        namespace RawVertices
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x0;
            constexpr std::size_t k_EntrySize = 0x60;

            constexpr std::size_t k_Position                                    = 0x0;  // point3.
            constexpr std::size_t k_Texcoord                                    = 0xC;  // point2.
            constexpr std::size_t k_Normal                                      = 0x14;  // point3.
            constexpr std::size_t k_Binormal                                    = 0x20;  // point3.
            constexpr std::size_t k_Tangent                                     = 0x2C;  // point3.
            constexpr std::size_t k_LightmapTexcoord                            = 0x38;  // point2.
            constexpr std::size_t k_NodeIndex1                                  = 0x40;  // uint8.
            constexpr std::size_t k_NodeIndex2                                  = 0x41;  // uint8.
            constexpr std::size_t k_NodeIndex3                                  = 0x42;  // uint8.
            constexpr std::size_t k_NodeIndex4                                  = 0x43;  // uint8.
            constexpr std::size_t k_NodeWeight1                                 = 0x44;  // float32.
            constexpr std::size_t k_NodeWeight2                                 = 0x48;  // float32.
            constexpr std::size_t k_NodeWeight3                                 = 0x4C;  // float32.
            constexpr std::size_t k_NodeWeight4                                 = 0x50;  // float32.
            constexpr std::size_t k_VertexColor                                 = 0x54;  // point3.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace RawIndices
        {
            // Array data.
            constexpr std::size_t k_Base      = 0xC;
            constexpr std::size_t k_EntrySize = 0x2;

            constexpr std::size_t k_Short                                       = 0x0;  // int16.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace RawIndices32
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x18;
            constexpr std::size_t k_EntrySize = 0x4;

            constexpr std::size_t k_Int                                         = 0x0;  // int32.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace RawWaterData
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x24;
            constexpr std::size_t k_EntrySize = 0x18;

            namespace RawWaterIndices
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x0;
                constexpr std::size_t k_EntrySize = 0x2;

                constexpr std::size_t k_Short                                       = 0x0;  // int16.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }

            namespace RawWaterVertices
            {
                // Array data.
                constexpr std::size_t k_Base      = 0xC;
                constexpr std::size_t k_EntrySize = 0x8;

                constexpr std::size_t k_BaseTexcoord                                = 0x0;  // point2.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }


            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace RawImposterData
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x30;
            constexpr std::size_t k_EntrySize = 0x4C;

            constexpr std::size_t k_Diffuse                                     = 0x0;  // colorf.
            constexpr std::size_t k_Ambient                                     = 0xC;  // colorf.
            constexpr std::size_t k_Specular                                    = 0x18;  // colorf.
            constexpr std::size_t k_Shininess                                   = 0x24;  // float32.
            constexpr std::size_t k_Alpha                                       = 0x28;  // float32.
            constexpr std::size_t k_ChangeColorTintOfDiffuse                    = 0x2C;  // colorf.
            constexpr std::size_t k_ChangeColorTintOfSpecular                   = 0x3C;  // colorf.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace RawInstanceImposterVerts
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x3C;
            constexpr std::size_t k_EntrySize = 0x14;

            constexpr std::size_t k_Position                                    = 0x0;  // vector3.
            constexpr std::size_t k_Color                                       = 0xC;  // uint32.
            constexpr std::size_t k_HdrScaler                                   = 0x10;  // float32.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        constexpr std::size_t k_PerVertexLightingVertexSize                 = 0x48;  // int32.
        constexpr std::size_t k_ParameterizedTextureWidth                   = 0x4C;  // int16.
        constexpr std::size_t k_ParameterizedTextureHeight                  = 0x4E;  // int16.
        constexpr std::size_t k_Flags                                       = 0x50;  // flags32. [Indices Are Triangle Strips=0, Indices Are Triangle Lists=1, Indices Are Quad Lists=2]

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_Unknown_5                                   = 0xA4;  // undefined.
    constexpr std::size_t k_Unknown_6                                   = 0xA8;  // undefined.
    constexpr std::size_t k_Unknown_7                                   = 0xAC;  // undefined.
    namespace PerMeshNodeMap
    {
        // Array data.
        constexpr std::size_t k_Base      = 0xB0;
        constexpr std::size_t k_EntrySize = 0xC;

        namespace NodeMap
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x0;
            constexpr std::size_t k_EntrySize = 0x1;

            constexpr std::size_t k_NodeIndex                                   = 0x0;  // int8.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }


        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace PerMeshSubpartVisibility
    {
        // Array data.
        constexpr std::size_t k_Base      = 0xBC;
        constexpr std::size_t k_EntrySize = 0xC;

        namespace BoundingSphere
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x0;
            constexpr std::size_t k_EntrySize = 0x30;

            constexpr std::size_t k_Plane                                       = 0x0;  // plane3.
            constexpr std::size_t k_Position                                    = 0x10;  // point3.
            constexpr std::size_t k_Radius                                      = 0x1C;  // float32.
            constexpr std::size_t k_NodeIndex1                                  = 0x20;  // uint8.
            constexpr std::size_t k_NodeIndex2                                  = 0x21;  // uint8.
            constexpr std::size_t k_NodeIndex3                                  = 0x22;  // uint8.
            constexpr std::size_t k_NodeIndex4                                  = 0x23;  // uint8.
            constexpr std::size_t k_NodeWeight1                                 = 0x24;  // float32.
            constexpr std::size_t k_NodeWeight2                                 = 0x28;  // float32.
            constexpr std::size_t k_NodeWeight3                                 = 0x2C;  // float32.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }


        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_BlockHere1                                  = 0xC8;  // uint32.
    constexpr std::size_t k_BlockHere1_2                                = 0xCC;  // uint32.
    constexpr std::size_t k_BlockHere1_3                                = 0xD0;  // uint32.
    constexpr std::size_t k_BlockHere2                                  = 0xD4;  // uint32.
    constexpr std::size_t k_BlockHere2_2                                = 0xD8;  // uint32.
    constexpr std::size_t k_BlockHere2_3                                = 0xDC;  // uint32.
    namespace PerInstanceLightmapTexcoords
    {
        // Array data.
        constexpr std::size_t k_Base      = 0xE0;
        constexpr std::size_t k_EntrySize = 0x2;

        constexpr std::size_t k_VertexBufferIndex                           = 0x0;  // int16.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace WaterBoundingBox
    {
        // Array data.
        constexpr std::size_t k_Base      = 0xEC;
        constexpr std::size_t k_EntrySize = 0x1C;

        constexpr std::size_t k_MeshIndex                                   = 0x0;  // int16.
        constexpr std::size_t k_PartIndex                                   = 0x2;  // int16.
        constexpr std::size_t k_PositionBounds0                             = 0x4;  // point3.
        constexpr std::size_t k_PositionBounds1                             = 0x10;  // point3.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_ZoneAssetDatum                              = 0xF8;  // datum.
    constexpr std::size_t k_UselessPadding                              = 0xFC;  // int32.
    namespace ConstantBufferInterop
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x100;
        constexpr std::size_t k_EntrySize = 0xC;

        constexpr std::size_t k_InteropPointer                              = 0x0;  // uint32.
        constexpr std::size_t k_Unknown                                     = 0x4;  // undefined.
        constexpr std::size_t k_UselessPadding                              = 0x8;  // int32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace NodeMapMapping
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x10C;
        constexpr std::size_t k_EntrySize = 0x2;

        constexpr std::size_t k_InstanceNodeMapRegionNodeIndex              = 0x0;  // int16.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace SkyLightUnknown
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x118;
        constexpr std::size_t k_EntrySize = 0x1C;

        constexpr std::size_t k_Unknown                                     = 0x0;  // float32.
        constexpr std::size_t k_Unknown_2                                   = 0x4;  // float32.
        constexpr std::size_t k_Unknown_3                                   = 0x8;  // float32.
        constexpr std::size_t k_Unknown_4                                   = 0xC;  // float32.
        constexpr std::size_t k_Unknown_5                                   = 0x10;  // float32.
        constexpr std::size_t k_Unknown_6                                   = 0x14;  // float32.
        constexpr std::size_t k_Unknown_7                                   = 0x18;  // float32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_Ambient                                     = 0x124;  // float32.
    constexpr std::size_t k_Directional                                 = 0x128;  // float32.
    constexpr std::size_t k_Directional_2                               = 0x12C;  // float32.
    constexpr std::size_t k_Directional_3                               = 0x130;  // float32.
    constexpr std::size_t k_Directional_4                               = 0x134;  // float32.
    constexpr std::size_t k_Directional_5                               = 0x138;  // float32.
    constexpr std::size_t k_Directional_6                               = 0x13C;  // float32.
    constexpr std::size_t k_Directional_7                               = 0x140;  // float32.
    constexpr std::size_t k_Directional_8                               = 0x144;  // float32.
    constexpr std::size_t k_Directional_9                               = 0x148;  // float32.
    constexpr std::size_t k_Directional_10                              = 0x14C;  // float32.
    constexpr std::size_t k_Directional_11                              = 0x150;  // float32.
    constexpr std::size_t k_Directional_12                              = 0x154;  // float32.
    constexpr std::size_t k_Directional_13                              = 0x158;  // float32.
    constexpr std::size_t k_Directional_14                              = 0x15C;  // float32.
    constexpr std::size_t k_Directional_15                              = 0x160;  // float32.
    constexpr std::size_t k_Ambient_2                                   = 0x164;  // float32.
    constexpr std::size_t k_Directional_16                              = 0x168;  // float32.
    constexpr std::size_t k_Directional_17                              = 0x16C;  // float32.
    constexpr std::size_t k_Directional_18                              = 0x170;  // float32.
    constexpr std::size_t k_Directional_19                              = 0x174;  // float32.
    constexpr std::size_t k_Directional_20                              = 0x178;  // float32.
    constexpr std::size_t k_Directional_21                              = 0x17C;  // float32.
    constexpr std::size_t k_Directional_22                              = 0x180;  // float32.
    constexpr std::size_t k_Directional_23                              = 0x184;  // float32.
    constexpr std::size_t k_Directional_24                              = 0x188;  // float32.
    constexpr std::size_t k_Directional_25                              = 0x18C;  // float32.
    constexpr std::size_t k_Directional_26                              = 0x190;  // float32.
    constexpr std::size_t k_Directional_27                              = 0x194;  // float32.
    constexpr std::size_t k_Directional_28                              = 0x198;  // float32.
    constexpr std::size_t k_Directional_29                              = 0x19C;  // float32.
    constexpr std::size_t k_Directional_30                              = 0x1A0;  // float32.
    constexpr std::size_t k_Ambient_3                                   = 0x1A4;  // float32.
    constexpr std::size_t k_Directional_31                              = 0x1A8;  // float32.
    constexpr std::size_t k_Directional_32                              = 0x1AC;  // float32.
    constexpr std::size_t k_Directional_33                              = 0x1B0;  // float32.
    constexpr std::size_t k_Directional_34                              = 0x1B4;  // float32.
    constexpr std::size_t k_Directional_35                              = 0x1B8;  // float32.
    constexpr std::size_t k_Directional_36                              = 0x1BC;  // float32.
    constexpr std::size_t k_Directional_37                              = 0x1C0;  // float32.
    constexpr std::size_t k_Directional_38                              = 0x1C4;  // float32.
    constexpr std::size_t k_Directional_39                              = 0x1C8;  // float32.
    constexpr std::size_t k_Directional_40                              = 0x1CC;  // float32.
    constexpr std::size_t k_Directional_41                              = 0x1D0;  // float32.
    constexpr std::size_t k_Directional_42                              = 0x1D4;  // float32.
    constexpr std::size_t k_Directional_43                              = 0x1D8;  // float32.
    constexpr std::size_t k_Directional_44                              = 0x1DC;  // float32.
    constexpr std::size_t k_Directional_45                              = 0x1E0;  // float32.
    constexpr std::size_t k_Unknown_8                                   = 0x1E4;  // undefined.
    constexpr std::size_t k_Unknown_9                                   = 0x1E8;  // undefined.
    constexpr std::size_t k_Unknown_10                                  = 0x1EC;  // undefined.
    constexpr std::size_t k_Unknown_11                                  = 0x1F0;  // undefined.
    constexpr std::size_t k_Unknown_12                                  = 0x1F4;  // undefined.
    constexpr std::size_t k_Unknown_13                                  = 0x1F8;  // undefined.
    constexpr std::size_t k_Unknown_14                                  = 0x1FC;  // undefined.
    constexpr std::size_t k_Unknown_15                                  = 0x200;  // undefined.
    constexpr std::size_t k_Unknown_16                                  = 0x204;  // undefined.
    constexpr std::size_t k_Unknown_17                                  = 0x208;  // undefined.
    constexpr std::size_t k_Unknown_18                                  = 0x20C;  // undefined.
    constexpr std::size_t k_Unknown_19                                  = 0x210;  // undefined.
    constexpr std::size_t k_Unknown_20                                  = 0x214;  // undefined.
    constexpr std::size_t k_Unknown_21                                  = 0x218;  // undefined.
    constexpr std::size_t k_Unknown_22                                  = 0x21C;  // undefined.
    constexpr std::size_t k_Unknown_23                                  = 0x220;  // undefined.
    constexpr std::size_t k_SkyLightLevels                              = 0x224;  // point3.
    constexpr std::size_t k_SkyLightRed                                 = 0x230;  // float32.
    constexpr std::size_t k_SkyLightGreen                               = 0x234;  // float32.
    constexpr std::size_t k_SkyLightBlue                                = 0x238;  // float32.
    constexpr std::size_t k_Unknown_24                                  = 0x23C;  // undefined.
    constexpr std::size_t k_Unknown_25                                  = 0x240;  // undefined.
    constexpr std::size_t k_Unknown_26                                  = 0x244;  // undefined.
    constexpr std::size_t k_Unknown_27                                  = 0x248;  // undefined.
    namespace VolumeSamples
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x24C;
        constexpr std::size_t k_EntrySize = 0x150;

        constexpr std::size_t k_Position                                    = 0x0;  // vector3.
        constexpr std::size_t k_Element                                     = 0xC;  // float32.
        constexpr std::size_t k_Element_2                                   = 0x10;  // float32.
        constexpr std::size_t k_Element_3                                   = 0x14;  // float32.
        constexpr std::size_t k_Element_4                                   = 0x18;  // float32.
        constexpr std::size_t k_Element_5                                   = 0x1C;  // float32.
        constexpr std::size_t k_Element_6                                   = 0x20;  // float32.
        constexpr std::size_t k_Element_7                                   = 0x24;  // float32.
        constexpr std::size_t k_Element_8                                   = 0x28;  // float32.
        constexpr std::size_t k_Element_9                                   = 0x2C;  // float32.
        constexpr std::size_t k_Element_10                                  = 0x30;  // float32.
        constexpr std::size_t k_Element_11                                  = 0x34;  // float32.
        constexpr std::size_t k_Element_12                                  = 0x38;  // float32.
        constexpr std::size_t k_Element_13                                  = 0x3C;  // float32.
        constexpr std::size_t k_Element_14                                  = 0x40;  // float32.
        constexpr std::size_t k_Element_15                                  = 0x44;  // float32.
        constexpr std::size_t k_Element_16                                  = 0x48;  // float32.
        constexpr std::size_t k_Element_17                                  = 0x4C;  // float32.
        constexpr std::size_t k_Element_18                                  = 0x50;  // float32.
        constexpr std::size_t k_Element_19                                  = 0x54;  // float32.
        constexpr std::size_t k_Element_20                                  = 0x58;  // float32.
        constexpr std::size_t k_Element_21                                  = 0x5C;  // float32.
        constexpr std::size_t k_Element_22                                  = 0x60;  // float32.
        constexpr std::size_t k_Element_23                                  = 0x64;  // float32.
        constexpr std::size_t k_Element_24                                  = 0x68;  // float32.
        constexpr std::size_t k_Element_25                                  = 0x6C;  // float32.
        constexpr std::size_t k_Element_26                                  = 0x70;  // float32.
        constexpr std::size_t k_Element_27                                  = 0x74;  // float32.
        constexpr std::size_t k_Element_28                                  = 0x78;  // float32.
        constexpr std::size_t k_Element_29                                  = 0x7C;  // float32.
        constexpr std::size_t k_Element_30                                  = 0x80;  // float32.
        constexpr std::size_t k_Element_31                                  = 0x84;  // float32.
        constexpr std::size_t k_Element_32                                  = 0x88;  // float32.
        constexpr std::size_t k_Element_33                                  = 0x8C;  // float32.
        constexpr std::size_t k_Element_34                                  = 0x90;  // float32.
        constexpr std::size_t k_Element_35                                  = 0x94;  // float32.
        constexpr std::size_t k_Element_36                                  = 0x98;  // float32.
        constexpr std::size_t k_Element_37                                  = 0x9C;  // float32.
        constexpr std::size_t k_Element_38                                  = 0xA0;  // float32.
        constexpr std::size_t k_Element_39                                  = 0xA4;  // float32.
        constexpr std::size_t k_Element_40                                  = 0xA8;  // float32.
        constexpr std::size_t k_Element_41                                  = 0xAC;  // float32.
        constexpr std::size_t k_Element_42                                  = 0xB0;  // float32.
        constexpr std::size_t k_Element_43                                  = 0xB4;  // float32.
        constexpr std::size_t k_Element_44                                  = 0xB8;  // float32.
        constexpr std::size_t k_Element_45                                  = 0xBC;  // float32.
        constexpr std::size_t k_Element_46                                  = 0xC0;  // float32.
        constexpr std::size_t k_Element_47                                  = 0xC4;  // float32.
        constexpr std::size_t k_Element_48                                  = 0xC8;  // float32.
        constexpr std::size_t k_Element_49                                  = 0xCC;  // float32.
        constexpr std::size_t k_Element_50                                  = 0xD0;  // float32.
        constexpr std::size_t k_Element_51                                  = 0xD4;  // float32.
        constexpr std::size_t k_Element_52                                  = 0xD8;  // float32.
        constexpr std::size_t k_Element_53                                  = 0xDC;  // float32.
        constexpr std::size_t k_Element_54                                  = 0xE0;  // float32.
        constexpr std::size_t k_Element_55                                  = 0xE4;  // float32.
        constexpr std::size_t k_Element_56                                  = 0xE8;  // float32.
        constexpr std::size_t k_Element_57                                  = 0xEC;  // float32.
        constexpr std::size_t k_Element_58                                  = 0xF0;  // float32.
        constexpr std::size_t k_Element_59                                  = 0xF4;  // float32.
        constexpr std::size_t k_Element_60                                  = 0xF8;  // float32.
        constexpr std::size_t k_Element_61                                  = 0xFC;  // float32.
        constexpr std::size_t k_Element_62                                  = 0x100;  // float32.
        constexpr std::size_t k_Element_63                                  = 0x104;  // float32.
        constexpr std::size_t k_Element_64                                  = 0x108;  // float32.
        constexpr std::size_t k_Element_65                                  = 0x10C;  // float32.
        constexpr std::size_t k_Element_66                                  = 0x110;  // float32.
        constexpr std::size_t k_Element_67                                  = 0x114;  // float32.
        constexpr std::size_t k_Element_68                                  = 0x118;  // float32.
        constexpr std::size_t k_Element_69                                  = 0x11C;  // float32.
        constexpr std::size_t k_Element_70                                  = 0x120;  // float32.
        constexpr std::size_t k_Element_71                                  = 0x124;  // float32.
        constexpr std::size_t k_Element_72                                  = 0x128;  // float32.
        constexpr std::size_t k_Element_73                                  = 0x12C;  // float32.
        constexpr std::size_t k_Element_74                                  = 0x130;  // float32.
        constexpr std::size_t k_Element_75                                  = 0x134;  // float32.
        constexpr std::size_t k_Element_76                                  = 0x138;  // float32.
        constexpr std::size_t k_Element_77                                  = 0x13C;  // float32.
        constexpr std::size_t k_Element_78                                  = 0x140;  // float32.
        constexpr std::size_t k_Element_79                                  = 0x144;  // float32.
        constexpr std::size_t k_Element_80                                  = 0x148;  // float32.
        constexpr std::size_t k_Element_81                                  = 0x14C;  // float32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace RuntimeNodeOrientations
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x258;
        constexpr std::size_t k_EntrySize = 0x20;

        constexpr std::size_t k_Rotation                                    = 0x0;  // vector4.
        constexpr std::size_t k_Translation                                 = 0x10;  // point3.
        constexpr std::size_t k_Scale                                       = 0x1C;  // float32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

}
