// Auto-generated by TagTranspiler (GenerateObject.py)
// Source XML: mode.xml

export module Map.Tag.System:Mode.Descriptor;

import Map.Tag.Type;
import Map.Reader.Type;
import Map.Reader.System;
import std;

namespace
{
    using namespace Map::Tag::Type::Mode::Structure;
    using namespace Map::Tag::Type::Mode::Object;
    namespace MapMagic = Map::Reader::Type::Magic;
}

export namespace Map::Reader::System
{
    template <>
    struct GroupDescriptor<ModeObject>
    {
        using DataType = ModeData;
        static constexpr std::uint32_t Magic = MapMagic::Tag::k_Mode;

        template <typename TReader>
        static void ReadBlocks(
            std::ifstream& file,
            const TReader& reader,
            ModeObject& obj)
        {
            {
                auto disk_Regions_0 = reader.template ReadBlock<Mode_RegionsEntry>(file, obj.Data.Regions);
                obj.Regions.reserve(disk_Regions_0.size());
                for (auto& diskEntry_0 : disk_Regions_0)
                {
                    Mode_RegionsObject entry_Regions_0{static_cast<Mode_RegionsEntry>(diskEntry_0)};
                    entry_Regions_0.Permutations = reader.template ReadBlock<Mode_Regions_PermutationsEntry>(file, diskEntry_0.Permutations);
                    obj.Regions.push_back(entry_Regions_0);
                }
            }
            obj.InstancePlacements = reader.template ReadBlock<Mode_InstancePlacementsEntry>(file, obj.Data.InstancePlacements);
            obj.Nodes = reader.template ReadBlock<Mode_NodesEntry>(file, obj.Data.Nodes);
            {
                auto disk_MarkerGroups_0 = reader.template ReadBlock<Mode_MarkerGroupsEntry>(file, obj.Data.MarkerGroups);
                obj.MarkerGroups.reserve(disk_MarkerGroups_0.size());
                for (auto& diskEntry_0 : disk_MarkerGroups_0)
                {
                    Mode_MarkerGroupsObject entry_MarkerGroups_0{static_cast<Mode_MarkerGroupsEntry>(diskEntry_0)};
                    entry_MarkerGroups_0.Markers = reader.template ReadBlock<Mode_MarkerGroups_MarkersEntry>(file, diskEntry_0.Markers);
                    obj.MarkerGroups.push_back(entry_MarkerGroups_0);
                }
            }
            obj.Materials = reader.template ReadBlock<Mode_MaterialsEntry>(file, obj.Data.Materials);
            {
                auto disk_Meshes_0 = reader.template ReadBlock<Mode_MeshesEntry>(file, obj.Data.Meshes);
                obj.Meshes.reserve(disk_Meshes_0.size());
                for (auto& diskEntry_0 : disk_Meshes_0)
                {
                    Mode_MeshesObject entry_Meshes_0{static_cast<Mode_MeshesEntry>(diskEntry_0)};
                    entry_Meshes_0.Parts = reader.template ReadBlock<Mode_Meshes_PartsEntry>(file, diskEntry_0.Parts);
                    entry_Meshes_0.Subparts = reader.template ReadBlock<Mode_Meshes_SubpartsEntry>(file, diskEntry_0.Subparts);
                    {
                        auto disk_InstanceBuckets_1 = reader.template ReadBlock<Mode_Meshes_InstanceBucketsEntry>(file, diskEntry_0.InstanceBuckets);
                        entry_Meshes_0.InstanceBuckets.reserve(disk_InstanceBuckets_1.size());
                        for (auto& diskEntry_1 : disk_InstanceBuckets_1)
                        {
                            Mode_Meshes_InstanceBucketsObject entry_InstanceBuckets_1{static_cast<Mode_Meshes_InstanceBucketsEntry>(diskEntry_1)};
                            entry_InstanceBuckets_1.Instances = reader.template ReadBlock<Mode_Meshes_InstanceBuckets_InstancesEntry>(file, diskEntry_1.Instances);
                            entry_Meshes_0.InstanceBuckets.push_back(entry_InstanceBuckets_1);
                        }
                    }
                    entry_Meshes_0.WaterIndicesStart = reader.template ReadBlock<Mode_Meshes_WaterIndicesStartEntry>(file, diskEntry_0.WaterIndicesStart);
                    obj.Meshes.push_back(entry_Meshes_0);
                }
            }
            obj.CompressionInfo = reader.template ReadBlock<Mode_CompressionInfoEntry>(file, obj.Data.CompressionInfo);
            obj.PartSortingPosition = reader.template ReadBlock<Mode_PartSortingPositionEntry>(file, obj.Data.PartSortingPosition);
            obj.UserData = reader.template ReadBlock<Mode_UserDataEntry>(file, obj.Data.UserData);
            {
                auto disk_PerMeshTemporary_0 = reader.template ReadBlock<Mode_PerMeshTemporaryEntry>(file, obj.Data.PerMeshTemporary);
                obj.PerMeshTemporary.reserve(disk_PerMeshTemporary_0.size());
                for (auto& diskEntry_0 : disk_PerMeshTemporary_0)
                {
                    Mode_PerMeshTemporaryObject entry_PerMeshTemporary_0{static_cast<Mode_PerMeshTemporaryEntry>(diskEntry_0)};
                    entry_PerMeshTemporary_0.RawVertices = reader.template ReadBlock<Mode_PerMeshTemporary_RawVerticesEntry>(file, diskEntry_0.RawVertices);
                    entry_PerMeshTemporary_0.RawIndices = reader.template ReadBlock<Mode_PerMeshTemporary_RawIndicesEntry>(file, diskEntry_0.RawIndices);
                    entry_PerMeshTemporary_0.RawIndices32 = reader.template ReadBlock<Mode_PerMeshTemporary_RawIndices32Entry>(file, diskEntry_0.RawIndices32);
                    {
                        auto disk_RawWaterData_1 = reader.template ReadBlock<Mode_PerMeshTemporary_RawWaterDataEntry>(file, diskEntry_0.RawWaterData);
                        entry_PerMeshTemporary_0.RawWaterData.reserve(disk_RawWaterData_1.size());
                        for (auto& diskEntry_1 : disk_RawWaterData_1)
                        {
                            Mode_PerMeshTemporary_RawWaterDataObject entry_RawWaterData_1{static_cast<Mode_PerMeshTemporary_RawWaterDataEntry>(diskEntry_1)};
                            entry_RawWaterData_1.RawWaterIndices = reader.template ReadBlock<Mode_PerMeshTemporary_RawWaterData_RawWaterIndicesEntry>(file, diskEntry_1.RawWaterIndices);
                            entry_RawWaterData_1.RawWaterVertices = reader.template ReadBlock<Mode_PerMeshTemporary_RawWaterData_RawWaterVerticesEntry>(file, diskEntry_1.RawWaterVertices);
                            entry_PerMeshTemporary_0.RawWaterData.push_back(entry_RawWaterData_1);
                        }
                    }
                    entry_PerMeshTemporary_0.RawImposterData = reader.template ReadBlock<Mode_PerMeshTemporary_RawImposterDataEntry>(file, diskEntry_0.RawImposterData);
                    entry_PerMeshTemporary_0.RawInstanceImposterVerts = reader.template ReadBlock<Mode_PerMeshTemporary_RawInstanceImposterVertsEntry>(file, diskEntry_0.RawInstanceImposterVerts);
                    obj.PerMeshTemporary.push_back(entry_PerMeshTemporary_0);
                }
            }
            {
                auto disk_PerMeshNodeMap_0 = reader.template ReadBlock<Mode_PerMeshNodeMapEntry>(file, obj.Data.PerMeshNodeMap);
                obj.PerMeshNodeMap.reserve(disk_PerMeshNodeMap_0.size());
                for (auto& diskEntry_0 : disk_PerMeshNodeMap_0)
                {
                    Mode_PerMeshNodeMapObject entry_PerMeshNodeMap_0{static_cast<Mode_PerMeshNodeMapEntry>(diskEntry_0)};
                    entry_PerMeshNodeMap_0.NodeMap = reader.template ReadBlock<Mode_PerMeshNodeMap_NodeMapEntry>(file, diskEntry_0.NodeMap);
                    obj.PerMeshNodeMap.push_back(entry_PerMeshNodeMap_0);
                }
            }
            {
                auto disk_PerMeshSubpartVisibility_0 = reader.template ReadBlock<Mode_PerMeshSubpartVisibilityEntry>(file, obj.Data.PerMeshSubpartVisibility);
                obj.PerMeshSubpartVisibility.reserve(disk_PerMeshSubpartVisibility_0.size());
                for (auto& diskEntry_0 : disk_PerMeshSubpartVisibility_0)
                {
                    Mode_PerMeshSubpartVisibilityObject entry_PerMeshSubpartVisibility_0{static_cast<Mode_PerMeshSubpartVisibilityEntry>(diskEntry_0)};
                    entry_PerMeshSubpartVisibility_0.BoundingSphere = reader.template ReadBlock<Mode_PerMeshSubpartVisibility_BoundingSphereEntry>(file, diskEntry_0.BoundingSphere);
                    obj.PerMeshSubpartVisibility.push_back(entry_PerMeshSubpartVisibility_0);
                }
            }
            obj.PerInstanceLightmapTexcoords = reader.template ReadBlock<Mode_PerInstanceLightmapTexcoordsEntry>(file, obj.Data.PerInstanceLightmapTexcoords);
            obj.WaterBoundingBox = reader.template ReadBlock<Mode_WaterBoundingBoxEntry>(file, obj.Data.WaterBoundingBox);
            obj.ConstantBufferInterop = reader.template ReadBlock<Mode_ConstantBufferInteropEntry>(file, obj.Data.ConstantBufferInterop);
            obj.NodeMapMapping = reader.template ReadBlock<Mode_NodeMapMappingEntry>(file, obj.Data.NodeMapMapping);
            obj.SkyLightUnknown = reader.template ReadBlock<Mode_SkyLightUnknownEntry>(file, obj.Data.SkyLightUnknown);
            obj.VolumeSamples = reader.template ReadBlock<Mode_VolumeSamplesEntry>(file, obj.Data.VolumeSamples);
            obj.RuntimeNodeOrientations = reader.template ReadBlock<Mode_RuntimeNodeOrientationsEntry>(file, obj.Data.RuntimeNodeOrientations);
        }
    };
}
