"""
GenerateCatalog.py
Regenerates the root of Domain/1_Map/Tag/ from whatever tag folders exist on
disk: the three umbrella modules (Map.Tag.Type.ixx, Map.Tag.System.ixx,
Map.Tag.State.ixx) and Map.TagCatalog.ixx (Map.Tag.State:Catalog).

This is the part of 1_Map/Tag/... that section 6.5 of the handoff flagged as
"la unica parte no 100% automatica": adding tag #20 used to mean hand-editing
four files. This module makes all four fully derived from the set of tag
folders present under Tag/, so GenerateTags.py can call it after every run
(single XML or full directory) and the root always reflects reality --- not
just whatever was processed in that invocation.

A folder under Tag/ counts as a tag if it directly contains a
Map.Tag.Type.<Name>.ixx generated by GenerateTags.py (GenerateTypeAggregate).
That file's existence is exactly the signal that GenerateTags.py finished
generating that tag's Type/State/System, so it's a safe discovery marker ---
no XML re-parsing needed here.
"""
import os


def DiscoverTags(tagsRoot: str) -> list[str]:
    """Returns tag prefixes (folder names) that have been generated under
    tagsRoot, sorted alphabetically -- same order the hand-written files
    used before this was automated."""
    prefixes = []
    if not os.path.isdir(tagsRoot):
        return prefixes

    for entry in os.listdir(tagsRoot):
        entryPath = os.path.join(tagsRoot, entry)
        if not os.path.isdir(entryPath):
            continue
        marker = os.path.join(entryPath, f"Map.Tag.Type.{entry}.ixx")
        if os.path.isfile(marker):
            prefixes.append(entry)

    return sorted(prefixes)


def _WriteIfChanged(outPath: str, content: str) -> bool:
    if os.path.isfile(outPath):
        with open(outPath, "r", encoding="utf-8") as f:
            if f.read() == content:
                return False
    with open(outPath, "w", encoding="utf-8") as f:
        f.write(content)
    return True


def GenerateTypeUmbrella(prefixes: list[str], tagsRoot: str) -> str:
    lines = []
    lines.append(f"// Auto-generated by TagTranspiler (GenerateCatalog.py)")
    lines.append(f"")
    lines.append(f"export module Map.Tag.Type;")
    lines.append(f"")
    for prefix in prefixes:
        lines.append(f"export import :{prefix};")
    content = "\n".join(lines) + "\n"

    outPath = os.path.join(tagsRoot, "Map.Tag.Type.ixx")
    if _WriteIfChanged(outPath, content):
        print(f"  Generated Module:    {outPath}")
    return outPath


def GenerateSystemUmbrella(prefixes: list[str], tagsRoot: str) -> str:
    lines = []
    lines.append(f"// Auto-generated by TagTranspiler (GenerateCatalog.py)")
    lines.append(f"")
    lines.append(f"export module Map.Tag.System;")
    lines.append(f"")
    for prefix in prefixes:
        lines.append(f"export import :{prefix};")
    content = "\n".join(lines) + "\n"

    outPath = os.path.join(tagsRoot, "Map.Tag.System.ixx")
    if _WriteIfChanged(outPath, content):
        print(f"  Generated Module:    {outPath}")
    return outPath


def GenerateStateUmbrella(tagsRoot: str) -> str:
    """
    Since 7.2 (see handoff 6.5), Map.Tag.State has nothing per-tag left to
    export: the per-tag XStore subclasses and their umbrellas are gone, and
    all that remains is the hand-written TagCatalog partition. This is
    still regenerated (not hand-maintained) so the file is never out of
    sync with the fact that it takes no tag list at all -- if that ever
    changes again, this is the one place that needs to change.
    """
    lines = []
    lines.append(f"// Auto-generated by TagTranspiler (GenerateCatalog.py)")
    lines.append(f"")
    lines.append(f"export module Map.Tag.State;")
    lines.append(f"")
    lines.append(f"export import :Catalog;")
    content = "\n".join(lines) + "\n"

    outPath = os.path.join(tagsRoot, "Map.Tag.State.ixx")
    if _WriteIfChanged(outPath, content):
        print(f"  Generated Module:    {outPath}")
    return outPath


def GenerateTagCatalog(prefixes: list[str], tagsRoot: str) -> str:
    lines = []
    lines.append(f"// Auto-generated by TagTranspiler (GenerateCatalog.py)")
    lines.append(f"")
    lines.append(f"export module Map.Tag.State:Catalog;")
    lines.append(f"")
    lines.append(f"import Map.Reader.State;")
    lines.append(f"import Map.Tag.Type;")
    lines.append(f"")
    lines.append(f"export namespace Map::Tag::State")
    lines.append(f"{{")
    lines.append(f"\tstruct TagCatalog")
    lines.append(f"\t{{")
    for prefix in prefixes:
        lines.append(
            f"\t\tMap::Reader::State::TagStore<Map::Tag::Type::{prefix}::Object::{prefix}Object> {prefix};"
        )
    lines.append(f"")
    lines.append(f"\t\ttemplate <typename F>")
    lines.append(f"\t\tauto ForEach(F&& f) -> void")
    lines.append(f"\t\t{{")
    for prefix in prefixes:
        lines.append(f"\t\t\tf({prefix});")
    lines.append(f"\t\t}}")
    lines.append(f"")
    lines.append(f"\t\tauto Freeze() -> void")
    lines.append(f"\t\t{{")
    lines.append(f"\t\t\tForEach([](auto& s) {{")
    lines.append(f"\t\t\t\ts.Freeze();")
    lines.append(f"\t\t\t}});")
    lines.append(f"\t\t}}")
    lines.append(f"")
    lines.append(f"\t\tauto Cleanup() -> void")
    lines.append(f"\t\t{{")
    lines.append(f"\t\t\tForEach([](auto& s) {{")
    lines.append(f"\t\t\t\ts.Cleanup();")
    lines.append(f"\t\t\t}});")
    lines.append(f"\t\t}}")
    lines.append(f"\t}};")
    lines.append(f"}}")
    content = "\n".join(lines) + "\n"

    outPath = os.path.join(tagsRoot, "Map.TagCatalog.ixx")
    if _WriteIfChanged(outPath, content):
        print(f"  Generated Module:    {outPath}")
    return outPath


def GenerateAll(tagsRoot: str) -> list[str]:
    """Regenerates all four root files from whatever tags exist on disk.
    Called by GenerateTags.py after every run; also runnable standalone to
    resync the root without touching any per-tag XML."""
    prefixes = DiscoverTags(tagsRoot)
    print(f"[Catalog] {len(prefixes)} tags found under {tagsRoot}: {', '.join(prefixes)}")
    GenerateTypeUmbrella(prefixes, tagsRoot)
    GenerateSystemUmbrella(prefixes, tagsRoot)
    GenerateStateUmbrella(tagsRoot)
    GenerateTagCatalog(prefixes, tagsRoot)
    return prefixes


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python GenerateCatalog.py <Domain/1_Map/Tag path>")
        sys.exit(1)
    GenerateAll(sys.argv[1])