"""
GenerateTemplate.py
Generates the runtime ("dynamic") object templates as C++23 module partitions of
Template.Object.Type from the public XML files in Templates/.

    python GenerateTemplate.py                 # every Templates/**/*.xml
    python GenerateTemplate.py Templates/Object/unit.xml

Per XML (obje.xml -> prefix Obje) it writes, under
Artemis/Core/Domain/3_Template/Object/Type/:
    Obje/TemplateObjeOffset.ixx     export module Template.Object.Type:Obje.Offset;
    Obje/TemplateObjeStructure.ixx  export module Template.Object.Type:Obje.Structure;
    Template.Object.Type.Obje.ixx   aggregate (partition :Obje)
File names carry the "Template" prefix so they never collide with the Map* files of
layer 1 (same .ixx name twice in one project overwrites the .obj); module partition
names and namespaces are unaffected.

XML specifics (on top of the Assembly format):
  start     first datum byte of the component. Offsets stay ABSOLUTE in the Offset
            partition; the Structure partition is relative to `start` (the struct
            is the component only, so UnitData is 0x820 bytes, not 0x9D8).
  baseSize  END of the component (absolute).
  confidence / exposed / default  documentation attributes (ignored here).
It reuses GenerateOffset.py / GenerateStructure.py and rewrites module + namespace.
"""
import os, sys, glob, shutil, tempfile
import xml.etree.ElementTree as ET

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)
import GenerateOffset, GenerateStructure
from Common import XmlBaseName, ParseHex

REPO = os.path.normpath(os.path.join(SCRIPT_DIR, ".."))
TEMPLATES = os.path.join(REPO, "Templates")
OUT = os.path.join(REPO, "Artemis", "Core", "Domain", "3_Template", "Object", "Type")

def Finish(text: str, xmlName: str) -> str:
    text = text.replace("export module Map.Tag.Type:", "export module Template.Object.Type:")
    text = text.replace("Map::Tag::Type::", "Template::Object::Type::")
    text = text.replace("(GenerateOffset.py)", "(GenerateTemplate.py)")
    text = text.replace("(GenerateStructure.py)", "(GenerateTemplate.py)")
    # rules.txt: CRLF line endings, no final newline.
    return text.rstrip("\r\n").replace("\r\n", "\n").replace("\n", "\r\n")

def Write(path: str, text: str) -> None:
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(text)
    print(f"  Generated: {path}")

def ProcessXml(xmlPath: str) -> None:
    prefix = XmlBaseName(xmlPath)
    xmlName = os.path.basename(xmlPath)
    os.makedirs(OUT, exist_ok=True)
    print(f"[{prefix}] {xmlName}")

    tree = ET.parse(xmlPath)
    root = tree.getroot()
    start = ParseHex(root.get("start", "0x0"))
    end = ParseHex(root.get("baseSize", "0x0"))
    if end <= start:
        raise SystemExit(f"{xmlName}: baseSize must be greater than start")

    tmp = tempfile.mkdtemp(prefix="tpl_")
    try:
        # Offset partition: absolute offsets, as written in the XML.
        tmpOff = os.path.join(tmp, "off.ixx")
        GenerateOffset.Generate(xmlPath, tmpOff)

        # Structure partition: offsets relative to the component start.
        rel = ET.fromstring(ET.tostring(root))
        for el in rel.iter():
            if el is not rel and el.get("offset"):
                el.set("offset", "0x%X" % (ParseHex(el.get("offset")) - start))
        rel.set("baseSize", "0x%X" % (end - start))
        relXml = os.path.join(tmp, xmlName)
        ET.ElementTree(rel).write(relXml, encoding="utf-8")
        tmpStr = os.path.join(tmp, "str.ixx")
        GenerateStructure.Generate(relXml, tmpStr)

        with open(tmpOff, encoding="utf-8") as f:
            off = f.read()
        with open(tmpStr, encoding="utf-8") as f:
            st = f.read()
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    off = off.replace(f"// Base size: 0x{end:X}.", f"// Component range: 0x{start:X}..0x{end:X} (absolute datum offsets).")
    st = st.replace("// Root struct size:", f"// Component starts at datum offset 0x{start:X}; field offsets in comments are relative to it.\n// Root struct size:")
    compDir = os.path.join(OUT, prefix)
    os.makedirs(compDir, exist_ok=True)
    Write(os.path.join(compDir, f"Template{prefix}Offset.ixx"), Finish(off, xmlName))
    Write(os.path.join(compDir, f"Template{prefix}Structure.ixx"), Finish(st, xmlName))

    agg = "\n".join([
        "// Auto-generated by TagTranspiler (GenerateTemplate.py)",
        f"// Source XML: {xmlName}",
        "",
        f"export module Template.Object.Type:{prefix};",
        "",
        f"export import :{prefix}.Offset;",
        f"export import :{prefix}.Structure;",
    ])
    Write(os.path.join(OUT, f"Template.Object.Type.{prefix}.ixx"), Finish(agg, xmlName))

def main() -> None:
    if len(sys.argv) > 1:
        files = sys.argv[1:]
    else:
        files = sorted(glob.glob(os.path.join(TEMPLATES, "**", "*.xml"), recursive=True))
    if not files:
        print("No XML found.")
        sys.exit(1)
    for p in files:
        ProcessXml(p)

if __name__ == "__main__":
    main()
