"""
GenerateOffset.py
Generates the offset header (namespaces) from an Assembly XML plugin.

Usage:
    python GenerateOffset.py input.xml output.h
"""

import xml.etree.ElementTree as ET
import re, sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from Common import ToPascal, ToOffsetIdent, IGNORED_TAGS

TYPE_MAP = {
    "float32": "float32", "float64": "float64",
    "int8": "int8", "int16": "int16", "int32": "int32", "int64": "int64",
    "uint8": "uint8", "uint16": "uint16", "uint32": "uint32", "uint64": "uint64",
    "stringid": "StringID", "asciiz": "ASCIIZ",
    "flags8": "flags8", "flags16": "flags16", "flags32": "flags32", "flags64": "flags64",
    "enum8": "enum8", "enum16": "enum16", "enum32": "enum32",
    "undefined": "undefined", "dataref": "DataReference", "tagref": "TagReference",
    "raw": "raw", "color32": "color32", "color64": "color64",
    "point2": "point2", "point3": "point3",
    "vector2": "vector2", "vector3": "vector3", "vector4": "vector4",
    "degree": "degree", "degree2": "degree2", "degree3": "degree3",
    "quaternion": "quaternion", "matrix": "matrix",
    "range": "range", "rangef": "rangef", "ranged": "ranged",
    "rangedegree": "rangedegree", "colorf": "colorf",
}

COMMENT_ONLY_CHILDREN = {
    "flags8","flags16","flags32","flags64","enum8","enum16","enum32"
}

def FormatOffset(offsetStr: str) -> str:
    try:
        return f"0x{int(offsetStr, 16):X}"
    except Exception:
        return offsetStr or "0x0"

def EmitBlock(element: ET.Element, indent: int, lines: list, nsName: str) -> None:
    offset  = FormatOffset(element.get("offset", "0x0"))
    sizeStr = element.get("elementSize", element.get("size", None))
    pad     = "    " * indent

    lines.append(f"{pad}namespace {nsName}")
    lines.append(f"{pad}{{")
    lines.append(f"{pad}    // Array data.")
    lines.append(f"{pad}    inline constexpr size_t k_Base      = {offset};")
    if sizeStr:
        lines.append(f"{pad}    inline constexpr size_t k_EntrySize = {FormatOffset(sizeStr)};")
    lines.append("")
    EmitChildren(element, indent + 1, lines)
    if sizeStr:
        lines.append("")
        lines.append(f"{pad}    inline constexpr size_t EntryOffset(size_t index)")
        lines.append(f"{pad}    {{")
        lines.append(f"{pad}        return k_Base + (index * k_EntrySize);")
        lines.append(f"{pad}    }}")
    lines.append(f"{pad}}}")
    lines.append("")

def EmitChildren(parent: ET.Element, indent: int, lines: list) -> None:
    pad        = "    " * indent
    identCount: dict[str, int] = {}

    for child in parent:
        tag = child.tag.lower()
        if tag in IGNORED_TAGS:
            continue

        name = child.get("name", "Unknown")

        if tag == "tagblock":
            ns = ToPascal(name)
            identCount[ns] = identCount.get(ns, 0) + 1
            n = identCount[ns]
            EmitBlock(child, indent, lines, ns if n == 1 else f"{ns}_{n}")
            continue

        offset = child.get("offset")
        if offset is None:
            continue

        cppType   = TYPE_MAP.get(tag, tag)
        identBase = ToOffsetIdent(name)
        identCount[identBase] = identCount.get(identBase, 0) + 1
        n     = identCount[identBase]
        ident = identBase if n == 1 else f"{identBase}_{n}"

        if tag in COMMENT_ONLY_CHILDREN:
            opts = []
            for c in child:
                cname = c.get("name", "?")
                cval  = c.get("index") or c.get("value")
                opts.append(f"{cname}={cval}" if cval else cname)
            suffix = f" [{', '.join(opts)}]" if opts else ""
            lines.append(f"{pad}inline constexpr size_t {ident:<45} = {FormatOffset(offset)};  // {cppType}.{suffix}")
        else:
            lines.append(f"{pad}inline constexpr size_t {ident:<45} = {FormatOffset(offset)};  // {cppType}.")

def Generate(xmlPath: str, outPath: str) -> None:
    tree  = ET.parse(xmlPath)
    root  = tree.getroot()
    base  = os.path.splitext(os.path.basename(xmlPath))[0]
    base  = re.sub(r"^ReachMCC_", "", base, flags=re.IGNORECASE)
    ns    = ToPascal(base) + "Offsets"
    bsize = FormatOffset(root.get("baseSize", "0x0"))

    lines = []
    lines.append(f"// Auto-generated by GenerateOffset.py")
    lines.append(f"// Source: {os.path.basename(xmlPath)}")
    lines.append(f"// Base size: {bsize}.")
    lines.append(f"")
    lines.append(f"#pragma once")
    lines.append(f"")
    lines.append(f"namespace {ns}")
    lines.append("{")
    EmitChildren(root, 1, lines)
    lines.append("}")
    lines.append("")

    with open(outPath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"  Generated: {outPath}")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python GenerateOffset.py input.xml output.h")
        sys.exit(1)
    Generate(sys.argv[1], sys.argv[2])