"""
GenerateTags.py
Processes one or more Assembly XML files and generates C++23 Module interfaces (.ixx).

Usage, a single XML:
    python GenerateTags.py phmo.xml

Usage, full directory of plugins:
    python GenerateTags.py ".../Assembly/Plugins/ReachMCC"
"""
import sys, os, re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)
from Common import XmlBaseName
import GenerateOffset
import GenerateStructure
import GenerateObject

_DOMAIN_ROOT = os.path.normpath(os.path.join(SCRIPT_DIR, "..", "Artemis", "Core", "Domain", "1_Map"))

# "Tags" is a purely visual grouping folder: it never appears in a module
# name or a namespace. Each tag then gets its own Type/State/System, exactly
# like the other layers' concept folders (Classifier, Collidable, etc.).
TAGS_ROOT = os.path.join(_DOMAIN_ROOT, "Tag")

def GenerateSystemAggregate(prefix: str, xmlSource: str, tagRoot: str) -> None:
    """
    placeholder
    """
    lines = []
    lines.append(f"// Auto-generated by TagTranspiler (GenerateTags.py)")
    lines.append(f"// Source XML: {xmlSource}")
    lines.append(f"")
    lines.append(f"export module Map.Tag.System:{prefix};")
    lines.append(f"")
    lines.append(f"export import :{prefix}.Descriptor;")
    lines.append(f"")

    outPath = os.path.join(tagRoot, f"Map.Tag.System.{prefix}.ixx")
    with open(outPath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"  Generated Module:    {outPath}")

def GenerateStateAggregate(prefix: str, xmlSource: str, tagRoot: str) -> None:
    """
    placeholder
    """
    lines = []
    lines.append(f"// Auto-generated by TagTranspiler (GenerateTags.py)")
    lines.append(f"// Source XML: {xmlSource}")
    lines.append(f"")
    lines.append(f"export module Map.Tag.State:{prefix};")
    lines.append(f"")
    lines.append(f"export import :{prefix}.Store;")
    lines.append(f"")

    outPath = os.path.join(tagRoot, f"Map.Tag.State.{prefix}.ixx")
    with open(outPath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"  Generated Module:    {outPath}")

def GenerateTypeAggregate(prefix: str, xmlSource: str, tagRoot: str) -> None:
    """
    Map.{prefix}.Type is split into three partitions (Structure, Offset,
    Object) generated separately below. This is the primary module
    interface unit that stitches them together, so anything that needs
    the tag's Type just does `import Map.{prefix}.Type;` once. It lives
    loose at the tag's root, as a sibling of Type/State/System, not inside
    the Type/ folder itself.
    """
    lines = []
    lines.append(f"// Auto-generated by TagTranspiler (GenerateTags.py)")
    lines.append(f"// Source XML: {xmlSource}")
    lines.append(f"")
    lines.append(f"export module Map.Tag.Type:{prefix};")
    lines.append(f"")
    lines.append(f"export import :{prefix}.Structure;")
    lines.append(f"export import :{prefix}.Offset;")
    lines.append(f"export import :{prefix}.Object;")
    lines.append(f"")

    outPath = os.path.join(tagRoot, f"Map.Tag.Type.{prefix}.ixx")
    with open(outPath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"  Generated Module:    {outPath}")

def ProcessXml(xmlPath: str) -> str:
    prefix = XmlBaseName(xmlPath)
    xmlSource = os.path.basename(xmlPath)

    tagRoot   = os.path.join(TAGS_ROOT, prefix)
    typeDir   = os.path.join(tagRoot, "Type")
    stateDir  = os.path.join(tagRoot, "State")   # hand-written (BipdStore, etc.), scaffolded here for consistency
    systemDir = os.path.join(tagRoot, "System")

    for d in (typeDir, stateDir, systemDir):
        os.makedirs(d, exist_ok=True)

    print(f"[{prefix}] {xmlSource}")
    try:
        GenerateOffset.Generate(xmlPath, os.path.join(typeDir, f"{prefix}Offset.ixx"))
        GenerateStructure.Generate(xmlPath, os.path.join(typeDir, f"{prefix}Structure.ixx"))
        GenerateObject.Generate(xmlPath, typeDir, systemDir)
        GenerateTypeAggregate(prefix, xmlSource, tagRoot)
        GenerateStateAggregate(prefix, xmlSource, tagRoot)
        GenerateSystemAggregate(prefix, xmlSource, tagRoot)
        return prefix
    except Exception as e:
        import traceback
        print(f"  [ERROR] {e}")
        traceback.print_exc()
        return None

def ProcessDirectory(xmlDir: str) -> None:
    xmlFiles = sorted([
        os.path.join(xmlDir, f)
        for f in os.listdir(xmlDir)
        if f.lower().endswith(".xml")
    ])
    print(f"Processing {len(xmlFiles)} XML in: {xmlDir}")
    print(f"Output: {TAGS_ROOT}")
    print()

    prefixes = []
    for xmlPath in xmlFiles:
        p = ProcessXml(xmlPath)
        if p:
            prefixes.append(p)

    print(f"\nDone. {len(prefixes)}/{len(xmlFiles)} tag modules generated.")

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    target = sys.argv[1]

    if os.path.isdir(target):
        ProcessDirectory(target)
    elif os.path.isfile(target) and target.lower().endswith(".xml"):
        print(f"Output: {TAGS_ROOT}")
        ProcessXml(target)
    else:
        print(f"Error: '{target}' is not a valid XML file or directory.")
        sys.exit(1)

if __name__ == "__main__":
    main()