"""
GenerateObject.py
Generates {Group}Object.h and {Group}Descriptor.h from an XML plugin.

Usage:
    python GenerateObject.py input.xml output_dir/
"""

import xml.etree.ElementTree as ET
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from Common import XmlBaseName, BuildBlockTree, BlockNode

def GenerateInflatedStructs(nodes: list[BlockNode], lines: list[str]) -> None:
    """Generates in-memory inflated structs (with vectors), children first."""
    for node in nodes:
        if node.HasChildren:
            GenerateInflatedStructs(node.Children, lines)
            lines.append(f"struct {node.ObjectStruct} : public {node.DiskStruct}")
            lines.append("{")
            for child in node.Children:
                lines.append(f"    std::vector<{child.VectorElementType}> {child.FieldName};")
            lines.append("};")
            lines.append("")

def GenerateObjectHeader(prefix: str, rootNodes: list[BlockNode], xmlSource: str) -> str:
    lines = []
    lines.append(f"// Auto-generated by GenerateObject.py")
    lines.append(f"// Source: {xmlSource}")
    lines.append(f"")
    lines.append(f"#pragma once")
    lines.append(f"")
    lines.append(f"#include \"{prefix}Types.h\"")
    lines.append(f"#include <string>")
    lines.append(f"#include <vector>")
    lines.append(f"")
    GenerateInflatedStructs(rootNodes, lines)
    lines.append(f"struct {prefix}Object")
    lines.append("{")
    lines.append(f"    std::string  TagName;")
    lines.append(f"    {prefix}Data Data;")
    lines.append(f"")
    for node in rootNodes:
        lines.append(f"    std::vector<{node.VectorElementType}> {node.FieldName};")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)

def GenerateReadCalls(nodes: list[BlockNode], reader: str, file: str,
                      dataExpr: str, objectExpr: str, indent: str,
                      lines: list[str], depth: int = 0) -> None:
    for node in nodes:
        if not node.HasChildren:
            lines.append(
                f"{indent}{objectExpr}.{node.FieldName} = "
                f"{reader}.ReadBlock<{node.DiskStruct}>"
                f"({file}, {dataExpr}.{node.FieldName});"
            )
        else:
            # Añadimos la profundidad (_depth) a las variables locales para evitar Shadowing
            diskVar  = f"disk_{node.Pascal}_{depth}"
            entryVar = f"entry_{node.Pascal}_{depth}"
            loopVar  = f"diskEntry_{depth}"
            
            lines.append(f"{indent}{{")
            lines.append(
                f"{indent}    auto {diskVar} = "
                f"{reader}.ReadBlock<{node.DiskStruct}>"
                f"({file}, {dataExpr}.{node.FieldName});"
            )
            lines.append(f"{indent}    {objectExpr}.{node.FieldName}.reserve({diskVar}.size());")
            lines.append(f"{indent}    for (auto& {loopVar} : {diskVar})")
            lines.append(f"{indent}    {{")
            lines.append(
                f"{indent}        {node.ObjectStruct} {entryVar}"
                f"{{static_cast<{node.DiskStruct}>({loopVar})}};"
            )
            GenerateReadCalls(
                node.Children, reader, file,
                dataExpr=loopVar, objectExpr=entryVar,
                indent=indent + "        ", lines=lines, depth=depth + 1
            )
            lines.append(f"{indent}        {objectExpr}.{node.FieldName}.push_back({entryVar});")
            lines.append(f"{indent}    }}")
            lines.append(f"{indent}}}")

def GenerateDescriptorHeader(prefix: str, rootNodes: list[BlockNode], xmlSource: str) -> str:
    lines = []
    lines.append(f"// Auto-generated by GenerateObject.py")
    lines.append(f"// Source: {xmlSource}")
    lines.append(f"#pragma once")
    lines.append(f"")
    lines.append(f"#include \"{prefix}Object.h\"")
    lines.append(f"#include \"Core/Systems/Domain/Map/TagGroupReader.h\"")
    lines.append(f"")
    lines.append(f"template <>")
    lines.append(f"struct GroupDescriptor<{prefix}Object>")
    lines.append(f"{{")
    lines.append(f"    using DataType = {prefix}Data;")
    lines.append(f"")
    lines.append(f"    static void ReadBlocks(")
    lines.append(f"        FILE* file,")
    lines.append(f"        const TagGroupReader& reader,")
    lines.append(f"        {prefix}Object& obj)")
    lines.append(f"    {{")
    GenerateReadCalls(
        rootNodes, reader="reader", file="file",
        dataExpr="obj.Data", objectExpr="obj",
        indent="        ", lines=lines, depth=0
    )
    lines.append(f"    }}")
    lines.append(f"}};")
    lines.append(f"")
    return "\n".join(lines)

def Generate(xmlPath: str, outDir: str) -> None:
    tree      = ET.parse(xmlPath)
    root      = tree.getroot()
    prefix    = XmlBaseName(xmlPath)
    xmlSource = os.path.basename(xmlPath)
    rootNodes = BuildBlockTree(root, prefix)

    os.makedirs(outDir, exist_ok=True)
    objectPath     = os.path.join(outDir, f"{prefix}Object.h")
    descriptorPath = os.path.join(outDir, f"{prefix}Descriptor.h")

    with open(objectPath,     "w", encoding="utf-8") as f:
        f.write(GenerateObjectHeader(prefix, rootNodes, xmlSource))
    with open(descriptorPath, "w", encoding="utf-8") as f:
        f.write(GenerateDescriptorHeader(prefix, rootNodes, xmlSource))
    print(f"Generated: {objectPath}")
    print(f"Generated: {descriptorPath}")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python GenerateObject.py input.xml output_dir/")
        sys.exit(1)
    Generate(sys.argv[1], sys.argv[2])