// Auto-generated by TagTranspiler (GenerateTemplate.py)
// Source XML: mach.xml
// Component starts at datum offset 0x2C4; field offsets in comments are relative to it.
// Root struct size: 0x10

export module Tables.Template.Type:Mach.Structure;

import Map.Reader.Type;
import std;

namespace
{
    namespace MapStructure = Map::Reader::Type::Structure;
}

#pragma pack(push, 1)

export namespace Tables::Template::Type::Mach::Structure
{
    // Entry size: 0x10
    struct MachData
    {
        std::uint32_t Unknown2c4;  // 0x0  uint32. | R16 W13 upd=0x0 src=INT_OR, INT_AND SHARED W:mach_place,mach_update,mach_s70
        std::uint32_t Unknown2c8;  // 0x4  uint32. | R1 W1 src=INT_ADD W:mach_update
        std::uint8_t  _gap_0x8[0x2];
        std::uint16_t Unknown2ce;  // 0xA  uint16. | R4 W1 init=0xffff W:mach_init
        std::uint16_t Unknown2d0;  // 0xC  uint16. | R3 W1 init=0x0 W:mach_init
        std::uint16_t Unknown2d2;  // 0xE  uint16. | R3 W1 init=0xffff W:mach_init
    };
    static_assert(sizeof(MachData) == 0x10, "MachData size mismatch");

}

#pragma pack(pop)