// Auto-generated by TagTranspiler (GenerateStructure.py)
// Source XML: Lbsp.xml
// Root struct size: 0x168

export module Map.Tag.Type:Lbsp.Structure;

import Map.Reader.Type;
import std;

namespace
{
    namespace MapStructure = Map::Reader::Type::Structure;
}

#pragma pack(push, 1)

export namespace Map::Tag::Type::Lbsp::Structure
{
    // Entry size: 0x4
    struct Lbsp_UnknownAEntry
    {
        std::int16_t VertexBufferIndex;  // 0x0  int16.
        std::int16_t Unknown;  // 0x2  int16.
    };
    static_assert(sizeof(Lbsp_UnknownAEntry) == 0x4, "Lbsp_UnknownAEntry size mismatch");

    // Entry size: 0x8
    struct Lbsp_UnknownBEntry
    {
        std::int32_t Unknown;  // 0x0  int32.
        std::uint8_t  _pad_0x4[0x4];  // undefined.
    };
    static_assert(sizeof(Lbsp_UnknownBEntry) == 0x8, "Lbsp_UnknownBEntry size mismatch");

    // Entry size: 0xC
    struct Lbsp_InstancedGeometryEntry
    {
        std::int16_t Unknown;  // 0x0  int16.
        std::int16_t UnknownAIndex;  // 0x2  int16.
        std::int16_t ColoringIndex;  // 0x4  int16.
        std::int16_t Unknown_2;  // 0x6  int16.
        std::uint32_t Unknown_3;  // 0x8  uint32.
    };
    static_assert(sizeof(Lbsp_InstancedGeometryEntry) == 0xC, "Lbsp_InstancedGeometryEntry size mismatch");

    // Entry size: 0x24
    struct Lbsp_ColorsEntry
    {
        float        Unknown;  // 0x0  float32.
        float        Unknown_2;  // 0x4  float32.
        float        Red;  // 0x8  float32.
        float        Blue;  // 0xC  float32.
        float        Unknown_3;  // 0x10  float32.
        std::int32_t Unknown_4;  // 0x14  int32.
        float        Unknown_5;  // 0x18  float32.
        float        Unknown_6;  // 0x1C  float32.
        std::uint32_t Unknown_7;  // 0x20  uint32.
    };
    static_assert(sizeof(Lbsp_ColorsEntry) == 0x24, "Lbsp_ColorsEntry size mismatch");

    // Entry size: 0x18
    struct Lbsp_Meshes_PartsEntry
    {
        std::int16_t RenderMaterialIndex;  // 0x0  int16.
        std::int16_t TransparentSortingIndex;  // 0x2  int16.
        std::uint32_t IndexStart;  // 0x4  uint32.
        std::uint32_t IndexCount;  // 0x8  uint32.
        std::int16_t SubpartStart;  // 0xC  int16.
        std::uint16_t SubpartCount;  // 0xE  uint16.
        std::int8_t  PartType;  // 0x10  int8. | 4 uses above transparent sorting index
        std::uint8_t SpecializedRender;  // 0x11  enum8. [None=0x0, Fail=0x1, Fur=0x2, Fur Stencil=0x3, Decal=0x4, Shield=0x5, Water=0x6, Lightmap Only=0x7, Hologram=0x8]
        std::uint16_t PartFlags;  // 0x12  flags16. [Is Water Surface=0, Per Vertex Lightmap Part=1, Debug Flag Instance Part=2, Subparts Has Uberlights Info=3, Draw Cull Distance Medium=4, Draw Cull Distance Close=5, Draw Cull Rendering Shields=6, Cannot Single Pass Render=7, Is Transparent=8, Cannot Two Pass=9, Transparent Should Output Depth For DOF=10, Do Not Include In Static Lightmap=11, Do Not Include In PVS Generation=12, Draw Cull Rendering Active Camo=13]
        std::uint16_t BudgetVertexCount;  // 0x14  uint16.
        std::uint16_t Tessellation;  // 0x16  enum16. [None=0x0, Fixed x4 Faces=0x1, Fixed x9 Faces=0x2, Fixed x36 Faces=0x3]
    };
    static_assert(sizeof(Lbsp_Meshes_PartsEntry) == 0x18, "Lbsp_Meshes_PartsEntry size mismatch");

    // Entry size: 0x10
    struct Lbsp_Meshes_SubpartsEntry
    {
        std::uint32_t IndexStart;  // 0x0  uint32.
        std::uint32_t IndexCount;  // 0x4  uint32.
        std::int16_t PartIndex;  // 0x8  int16.
        std::uint16_t BudgetVertexCount;  // 0xA  uint16.
        std::uint32_t AnalyticalLightIndex;  // 0xC  uint32.
    };
    static_assert(sizeof(Lbsp_Meshes_SubpartsEntry) == 0x10, "Lbsp_Meshes_SubpartsEntry size mismatch");

    // Entry size: 0x2
    struct Lbsp_Meshes_InstanceBuckets_InstancesEntry
    {
        std::int16_t InstanceIndex;  // 0x0  int16.
    };
    static_assert(sizeof(Lbsp_Meshes_InstanceBuckets_InstancesEntry) == 0x2, "Lbsp_Meshes_InstanceBuckets_InstancesEntry size mismatch");

    // Entry size: 0x10
    struct Lbsp_Meshes_InstanceBucketsEntry
    {
        std::int16_t MeshIndex;  // 0x0  int16.
        std::int16_t DefinitionIndex;  // 0x2  int16.
        // -> Lbsp_Meshes_InstanceBuckets_InstancesEntry[]
        MapStructure::Tag::Block   Instances;  // 0x4  tagblock.
    };
    static_assert(sizeof(Lbsp_Meshes_InstanceBucketsEntry) == 0x10, "Lbsp_Meshes_InstanceBucketsEntry size mismatch");

    // Entry size: 0x2
    struct Lbsp_Meshes_WaterIndicesStartEntry
    {
        std::int16_t Short;  // 0x0  int16.
    };
    static_assert(sizeof(Lbsp_Meshes_WaterIndicesStartEntry) == 0x2, "Lbsp_Meshes_WaterIndicesStartEntry size mismatch");

    // Entry size: 0x5C
    struct Lbsp_MeshesEntry
    {
        // -> Lbsp_Meshes_PartsEntry[]
        MapStructure::Tag::Block   Parts;  // 0x0  tagblock.
        // -> Lbsp_Meshes_SubpartsEntry[]
        MapStructure::Tag::Block   Subparts;  // 0xC  tagblock.
        std::int16_t VertexBufferIndex1;  // 0x18  int16.
        std::int16_t VertexBufferIndex2;  // 0x1A  int16.
        std::int16_t VertexBufferIndex3;  // 0x1C  int16.
        std::int16_t VertexBufferIndex4;  // 0x1E  int16.
        std::int16_t VertexBufferIndex5;  // 0x20  int16.
        std::int16_t VertexBufferIndex6;  // 0x22  int16.
        std::int16_t VertexBufferIndex7;  // 0x24  int16.
        std::int16_t VertexBufferIndex8;  // 0x26  int16.
        std::int16_t IndexBufferIndex;  // 0x28  int16.
        std::int16_t IndexBufferTessellationIndex;  // 0x2A  int16.
        std::uint16_t MeshFlags;  // 0x2C  flags16. [Mesh Has Vertex Color=0, Use Region Index For Sorting=1, Use Vertex Buffers For Indices=2, Mesh Has Per-Instance Lighting (Do Not Modify)=3, Mesh Is Unindexed (Do Not Modify)=4, Subpart Were Merged=5, Mesh Has Fur=6, Mesh Has Decal=7, Mesh Doesn't Use Compressed Position=8, Use Uncompressed Vertex Format=9, Bit 10=10, Bit 11=11, Bit 12=12, Bit 13=13, Bit 14=14, Bit 15=15]
        std::int8_t  RigidNodeIndex;  // 0x2E  int8.
        std::uint8_t VertexType;  // 0x2F  enum8. [World=0x0, Rigid=0x1, Skinned=0x2, Particle Model=0x3, Flat World=0x4, Flat Rigid=0x5, Flat Skinned=0x6, Screen=0x7, Debug=0x8, Transparent=0x9, Particle=0xA, Contrail=0xB, Light Volume=0xC, Chud Simple=0xD, Chud Fancy=0xE, Decorator=0xF, ...(31 total)]
        std::uint8_t PrtType;  // 0x30  enum8. [None=0x0, Ambient=0x1, Linear=0x2, Quadratic=0x3]
        std::uint8_t LightingPolicy;  // 0x31  enum8. [Vertex Color=0x0, Single Probe=0x1, PRT Ambient=0x2]
        std::uint8_t IndexBufferType;  // 0x32  enum8. [Point List=0x0, Line List=0x1, Line Strip=0x2, Triangle List=0x3, Triangle Fan=0x4, Triangle Strip=0x5]
        std::int8_t  Unknown;  // 0x33  int8.
        // -> Lbsp_Meshes_InstanceBucketsEntry[]
        MapStructure::Tag::Block   InstanceBuckets;  // 0x34  tagblock.
        // -> Lbsp_Meshes_WaterIndicesStartEntry[]
        MapStructure::Tag::Block   WaterIndicesStart;  // 0x40  tagblock.
        float        BoundingRadius;  // 0x4C  float32.
        MapStructure::Primitive::Vec3 BoundingOffset;  // 0x50  point3.
    };
    static_assert(sizeof(Lbsp_MeshesEntry) == 0x5C, "Lbsp_MeshesEntry size mismatch");

    // Entry size: 0x34
    struct Lbsp_CompressionInfoEntry
    {
        std::uint16_t CompressionFlags;  // 0x0  flags16. [Compressed Position=0, Compressed Texcoord=1, Compression Optimized=2]
        std::int16_t Unknown;  // 0x2  int16.
        MapStructure::Primitive::RangeF PositionBoundsX;  // 0x4  rangef.
        MapStructure::Primitive::RangeF PositionBoundsY;  // 0xC  rangef.
        MapStructure::Primitive::RangeF PositionBoundsZ;  // 0x14  rangef.
        MapStructure::Primitive::RangeF TexcoordBoundsX;  // 0x1C  rangef.
        MapStructure::Primitive::RangeF TexcoordBoundsY;  // 0x24  rangef.
        float        Unknown_2;  // 0x2C  float32.
        float        Unknown_3;  // 0x30  float32.
    };
    static_assert(sizeof(Lbsp_CompressionInfoEntry) == 0x34, "Lbsp_CompressionInfoEntry size mismatch");

    // Entry size: 0x30
    struct Lbsp_PartSortingPositionEntry
    {
        std::uint32_t Plane;  // 0x0  plane3.
        std::uint8_t  _gap_0x4[0xC];
        MapStructure::Primitive::Vec3 Position;  // 0x10  point3.
        float        Radius;  // 0x1C  float32.
        std::int8_t  NodeIndex1;  // 0x20  int8.
        std::int8_t  NodeIndex2;  // 0x21  int8.
        std::int8_t  NodeIndex3;  // 0x22  int8.
        std::int8_t  NodeIndex4;  // 0x23  int8.
        float        NodeWeight1;  // 0x24  float32.
        float        NodeWeight2;  // 0x28  float32.
        float        NodeWeight3;  // 0x2C  float32.
    };
    static_assert(sizeof(Lbsp_PartSortingPositionEntry) == 0x30, "Lbsp_PartSortingPositionEntry size mismatch");

    // Entry size: 0x18
    struct Lbsp_UserDataEntry
    {
        std::uint8_t DataType;  // 0x0  enum8. [PRT Info=0x0]
        std::int8_t  DataCount;  // 0x1  int8.
        std::uint16_t DataSize;  // 0x2  uint16.
        MapStructure::Data::Reference UserData;  // 0x4  dataref.
    };
    static_assert(sizeof(Lbsp_UserDataEntry) == 0x18, "Lbsp_UserDataEntry size mismatch");

    // Entry size: 0x60
    struct Lbsp_PerMeshTemporary_RawVerticesEntry
    {
        MapStructure::Primitive::Vec3 Position;  // 0x0  point3.
        MapStructure::Primitive::Vec2 Texcoord;  // 0xC  point2.
        MapStructure::Primitive::Vec3 Normal;  // 0x14  point3.
        MapStructure::Primitive::Vec3 Binormal;  // 0x20  point3.
        MapStructure::Primitive::Vec3 Tangent;  // 0x2C  point3.
        MapStructure::Primitive::Vec2 LightmapTexcoord;  // 0x38  point2.
        std::uint8_t NodeIndex1;  // 0x40  uint8.
        std::uint8_t NodeIndex2;  // 0x41  uint8.
        std::uint8_t NodeIndex3;  // 0x42  uint8.
        std::uint8_t NodeIndex4;  // 0x43  uint8.
        float        NodeWeight1;  // 0x44  float32.
        float        NodeWeight2;  // 0x48  float32.
        float        NodeWeight3;  // 0x4C  float32.
        float        NodeWeight4;  // 0x50  float32.
        MapStructure::Primitive::Vec3 VertexColor;  // 0x54  point3.
    };
    static_assert(sizeof(Lbsp_PerMeshTemporary_RawVerticesEntry) == 0x60, "Lbsp_PerMeshTemporary_RawVerticesEntry size mismatch");

    // Entry size: 0x2
    struct Lbsp_PerMeshTemporary_RawIndicesEntry
    {
        std::int16_t Short;  // 0x0  int16.
    };
    static_assert(sizeof(Lbsp_PerMeshTemporary_RawIndicesEntry) == 0x2, "Lbsp_PerMeshTemporary_RawIndicesEntry size mismatch");

    // Entry size: 0x4
    struct Lbsp_PerMeshTemporary_RawIndices32Entry
    {
        std::int32_t Int;  // 0x0  int32.
    };
    static_assert(sizeof(Lbsp_PerMeshTemporary_RawIndices32Entry) == 0x4, "Lbsp_PerMeshTemporary_RawIndices32Entry size mismatch");

    // Entry size: 0x2
    struct Lbsp_PerMeshTemporary_RawWaterData_RawWaterIndicesEntry
    {
        std::int16_t Short;  // 0x0  int16.
    };
    static_assert(sizeof(Lbsp_PerMeshTemporary_RawWaterData_RawWaterIndicesEntry) == 0x2, "Lbsp_PerMeshTemporary_RawWaterData_RawWaterIndicesEntry size mismatch");

    // Entry size: 0x8
    struct Lbsp_PerMeshTemporary_RawWaterData_RawWaterVerticesEntry
    {
        MapStructure::Primitive::Vec2 BaseTexcoord;  // 0x0  point2.
    };
    static_assert(sizeof(Lbsp_PerMeshTemporary_RawWaterData_RawWaterVerticesEntry) == 0x8, "Lbsp_PerMeshTemporary_RawWaterData_RawWaterVerticesEntry size mismatch");

    // Entry size: 0x18
    struct Lbsp_PerMeshTemporary_RawWaterDataEntry
    {
        // -> Lbsp_PerMeshTemporary_RawWaterData_RawWaterIndicesEntry[]
        MapStructure::Tag::Block   RawWaterIndices;  // 0x0  tagblock.
        // -> Lbsp_PerMeshTemporary_RawWaterData_RawWaterVerticesEntry[]
        MapStructure::Tag::Block   RawWaterVertices;  // 0xC  tagblock.
    };
    static_assert(sizeof(Lbsp_PerMeshTemporary_RawWaterDataEntry) == 0x18, "Lbsp_PerMeshTemporary_RawWaterDataEntry size mismatch");

    // Entry size: 0x4C
    struct Lbsp_PerMeshTemporary_RawImposterDataEntry
    {
        MapStructure::Primitive::ColorRGB Diffuse;  // 0x0  colorf.
        MapStructure::Primitive::ColorRGB Ambient;  // 0xC  colorf.
        MapStructure::Primitive::ColorRGB Specular;  // 0x18  colorf.
        float        Shininess;  // 0x24  float32.
        float        Alpha;  // 0x28  float32.
        MapStructure::Primitive::ColorRGBA ChangeColorTintOfDiffuse;  // 0x2C  colorf.
        MapStructure::Primitive::ColorRGBA ChangeColorTintOfSpecular;  // 0x3C  colorf.
    };
    static_assert(sizeof(Lbsp_PerMeshTemporary_RawImposterDataEntry) == 0x4C, "Lbsp_PerMeshTemporary_RawImposterDataEntry size mismatch");

    // Entry size: 0x14
    struct Lbsp_PerMeshTemporary_RawInstanceImposterVertsEntry
    {
        MapStructure::Primitive::Vec3 Position;  // 0x0  vector3.
        std::uint32_t Color;  // 0xC  uint32.
        float        HdrScaler;  // 0x10  float32.
    };
    static_assert(sizeof(Lbsp_PerMeshTemporary_RawInstanceImposterVertsEntry) == 0x14, "Lbsp_PerMeshTemporary_RawInstanceImposterVertsEntry size mismatch");

    // Entry size: 0x54
    struct Lbsp_PerMeshTemporaryEntry
    {
        // -> Lbsp_PerMeshTemporary_RawVerticesEntry[]
        MapStructure::Tag::Block   RawVertices;  // 0x0  tagblock.
        // -> Lbsp_PerMeshTemporary_RawIndicesEntry[]
        MapStructure::Tag::Block   RawIndices;  // 0xC  tagblock.
        // -> Lbsp_PerMeshTemporary_RawIndices32Entry[]
        MapStructure::Tag::Block   RawIndices32;  // 0x18  tagblock.
        // -> Lbsp_PerMeshTemporary_RawWaterDataEntry[]
        MapStructure::Tag::Block   RawWaterData;  // 0x24  tagblock.
        // -> Lbsp_PerMeshTemporary_RawImposterDataEntry[]
        MapStructure::Tag::Block   RawImposterData;  // 0x30  tagblock.
        // -> Lbsp_PerMeshTemporary_RawInstanceImposterVertsEntry[]
        MapStructure::Tag::Block   RawInstanceImposterVerts;  // 0x3C  tagblock.
        std::int32_t PerVertexLightingVertexSize;  // 0x48  int32.
        std::int16_t ParameterizedTextureWidth;  // 0x4C  int16.
        std::int16_t ParameterizedTextureHeight;  // 0x4E  int16.
        std::uint32_t Flags;  // 0x50  flags32. [Indices Are Triangle Strips=0, Indices Are Triangle Lists=1, Indices Are Quad Lists=2]
    };
    static_assert(sizeof(Lbsp_PerMeshTemporaryEntry) == 0x54, "Lbsp_PerMeshTemporaryEntry size mismatch");

    // Entry size: 0x1
    struct Lbsp_PerMeshNodeMap_NodeMapEntry
    {
        std::int8_t  NodeIndex;  // 0x0  int8.
    };
    static_assert(sizeof(Lbsp_PerMeshNodeMap_NodeMapEntry) == 0x1, "Lbsp_PerMeshNodeMap_NodeMapEntry size mismatch");

    // Entry size: 0xC
    struct Lbsp_PerMeshNodeMapEntry
    {
        // -> Lbsp_PerMeshNodeMap_NodeMapEntry[]
        MapStructure::Tag::Block   NodeMap;  // 0x0  tagblock.
    };
    static_assert(sizeof(Lbsp_PerMeshNodeMapEntry) == 0xC, "Lbsp_PerMeshNodeMapEntry size mismatch");

    // Entry size: 0x30
    struct Lbsp_PerMeshSubpartVisibility_BoundingSphereEntry
    {
        std::uint32_t Plane;  // 0x0  plane3.
        std::uint8_t  _gap_0x4[0xC];
        MapStructure::Primitive::Vec3 Position;  // 0x10  point3.
        float        Radius;  // 0x1C  float32.
        std::uint8_t NodeIndex1;  // 0x20  uint8.
        std::uint8_t NodeIndex2;  // 0x21  uint8.
        std::uint8_t NodeIndex3;  // 0x22  uint8.
        std::uint8_t NodeIndex4;  // 0x23  uint8.
        float        NodeWeight1;  // 0x24  float32.
        float        NodeWeight2;  // 0x28  float32.
        float        NodeWeight3;  // 0x2C  float32.
    };
    static_assert(sizeof(Lbsp_PerMeshSubpartVisibility_BoundingSphereEntry) == 0x30, "Lbsp_PerMeshSubpartVisibility_BoundingSphereEntry size mismatch");

    // Entry size: 0xC
    struct Lbsp_PerMeshSubpartVisibilityEntry
    {
        // -> Lbsp_PerMeshSubpartVisibility_BoundingSphereEntry[]
        MapStructure::Tag::Block   BoundingSphere;  // 0x0  tagblock.
    };
    static_assert(sizeof(Lbsp_PerMeshSubpartVisibilityEntry) == 0xC, "Lbsp_PerMeshSubpartVisibilityEntry size mismatch");

    // Entry size: 0x2
    struct Lbsp_PerInstanceLightmapTexcoordsEntry
    {
        std::int16_t VertexBufferIndex;  // 0x0  int16.
    };
    static_assert(sizeof(Lbsp_PerInstanceLightmapTexcoordsEntry) == 0x2, "Lbsp_PerInstanceLightmapTexcoordsEntry size mismatch");

    // Entry size: 0x1C
    struct Lbsp_WaterBoundingBoxEntry
    {
        std::int16_t MeshIndex;  // 0x0  int16.
        std::int16_t PartIndex;  // 0x2  int16.
        MapStructure::Primitive::Vec3 PositionBounds0;  // 0x4  point3.
        MapStructure::Primitive::Vec3 PositionBounds1;  // 0x10  point3.
    };
    static_assert(sizeof(Lbsp_WaterBoundingBoxEntry) == 0x1C, "Lbsp_WaterBoundingBoxEntry size mismatch");

    // Entry size: 0xC
    struct Lbsp_ConstantBufferInteropEntry
    {
        std::uint32_t InteropPointer;  // 0x0  uint32.
        std::uint8_t  _pad_0x4[0x4];  // undefined.
        std::int32_t UselessPadding;  // 0x8  int32.
    };
    static_assert(sizeof(Lbsp_ConstantBufferInteropEntry) == 0xC, "Lbsp_ConstantBufferInteropEntry size mismatch");

    // Entry size: 0x4
    struct Lbsp_Unknown_UnknownEntry
    {
        std::uint8_t  _pad_0x0[0x4];  // undefined.
    };
    static_assert(sizeof(Lbsp_Unknown_UnknownEntry) == 0x4, "Lbsp_Unknown_UnknownEntry size mismatch");

    // Entry size: 0xC
    struct Lbsp_UnknownEntry
    {
        // -> Lbsp_Unknown_UnknownEntry[]
        MapStructure::Tag::Block   Unknown;  // 0x0  tagblock.
    };
    static_assert(sizeof(Lbsp_UnknownEntry) == 0xC, "Lbsp_UnknownEntry size mismatch");

    // Entry size: 0x38
    struct Lbsp_AirprobesEntry
    {
        MapStructure::Primitive::Vec3 AirprobePosition;  // 0x0  point3.
        std::uint32_t AirprobeName;  // 0xC  stringid.
        std::uint8_t  _pad_0x10[0x4];  // undefined.
        std::uint8_t  _pad_0x14[0x4];  // undefined.
        std::uint8_t  _pad_0x18[0x4];  // undefined.
        std::uint8_t  _pad_0x1C[0x4];  // undefined.
        std::uint8_t  _pad_0x20[0x4];  // undefined.
        std::uint8_t  _pad_0x24[0x4];  // undefined.
        std::uint8_t  _pad_0x28[0x4];  // undefined.
        std::uint8_t  _pad_0x2C[0x4];  // undefined.
        std::uint8_t  _pad_0x30[0x4];  // undefined.
        std::uint8_t  _pad_0x34[0x4];  // undefined.
    };
    static_assert(sizeof(Lbsp_AirprobesEntry) == 0x38, "Lbsp_AirprobesEntry size mismatch");

    // Entry size: 0x2C
    struct Lbsp_UnknownEntry_2
    {
        std::uint8_t  _pad_0x0[0x4];  // undefined.
        std::uint8_t  _pad_0x4[0x4];  // undefined.
        std::uint8_t  _pad_0x8[0x4];  // undefined.
        std::uint8_t  _pad_0xC[0x4];  // undefined.
        std::uint8_t  _pad_0x10[0x4];  // undefined.
        std::uint8_t  _pad_0x14[0x4];  // undefined.
        std::uint8_t  _pad_0x18[0x4];  // undefined.
        std::uint8_t  _pad_0x1C[0x4];  // undefined.
        std::uint8_t  _pad_0x20[0x4];  // undefined.
        std::uint8_t  _pad_0x24[0x4];  // undefined.
        std::uint8_t  _pad_0x28[0x4];  // undefined.
    };
    static_assert(sizeof(Lbsp_UnknownEntry_2) == 0x2C, "Lbsp_UnknownEntry_2 size mismatch");

    // Entry size: 0x30
    struct Lbsp_Unknown_3_UnknownEntry
    {
        std::uint8_t  _pad_0x0[0x4];  // undefined.
        std::uint8_t  _pad_0x4[0x4];  // undefined.
        std::uint8_t  _pad_0x8[0x4];  // undefined.
        std::uint8_t  _pad_0xC[0x4];  // undefined.
        std::uint8_t  _pad_0x10[0x4];  // undefined.
        std::uint8_t  _pad_0x14[0x4];  // undefined.
        std::uint8_t  _pad_0x18[0x4];  // undefined.
        std::uint8_t  _pad_0x1C[0x4];  // undefined.
        std::uint8_t  _pad_0x20[0x4];  // undefined.
        std::uint8_t  _pad_0x24[0x4];  // undefined.
        std::uint8_t  _pad_0x28[0x4];  // undefined.
        std::uint8_t  _pad_0x2C[0x4];  // undefined.
    };
    static_assert(sizeof(Lbsp_Unknown_3_UnknownEntry) == 0x30, "Lbsp_Unknown_3_UnknownEntry size mismatch");

    // Entry size: 0x2C
    struct Lbsp_UnknownEntry_3
    {
        std::uint8_t  _pad_0x0[0x4];  // undefined.
        std::uint8_t  _pad_0x4[0x4];  // undefined.
        std::uint8_t  _pad_0x8[0x4];  // undefined.
        std::uint8_t  _pad_0xC[0x4];  // undefined.
        std::uint8_t  _pad_0x10[0x4];  // undefined.
        std::uint8_t  _pad_0x14[0x4];  // undefined.
        std::uint8_t  _pad_0x18[0x4];  // undefined.
        std::uint8_t  _pad_0x1C[0x4];  // undefined.
        // -> Lbsp_Unknown_3_UnknownEntry[]
        MapStructure::Tag::Block   Unknown_9;  // 0x20  tagblock.
    };
    static_assert(sizeof(Lbsp_UnknownEntry_3) == 0x2C, "Lbsp_UnknownEntry_3 size mismatch");

    // Entry size: 0x240
    struct Lbsp_SelfTrackEntry
    {
        std::uint32_t Time;  // 0x0  ascii.
        std::uint8_t  _gap_0x4[0x1C];
        std::uint32_t Machine;  // 0x20  ascii.
        std::uint8_t  _gap_0x24[0x1C];
        std::uint32_t Version;  // 0x40  ascii.
        std::uint8_t  _gap_0x44[0xFC];
        std::uint32_t Command;  // 0x140  ascii.
        std::uint8_t  _tail_0x144[0xFC];  // trailing pad
    };
    static_assert(sizeof(Lbsp_SelfTrackEntry) == 0x240, "Lbsp_SelfTrackEntry size mismatch");

    // Entry size: 0x168
    struct LbspData
    {
        std::uint16_t Flags;  // 0x0  flags16. [Compressed=0, Xsynced Geometry=1, Relightmapped=2, Generate Fake Small Lightmaps=3, Generated From Match Data=4, Only A Checker Board=5, Surface To Triangle Mapping Pruned=6, Faked Lightmap Tag For Cache Build=7, Optimized For Less DP All=8, Floating Shadows Enabled=9, Atlas Unrefined Packing=10, Atlas Repacked=11, Using Simplified Irradiance Lighting=12, Disable Shadow Geometry=13, Disable Hybrid Refinement=14]
        std::int16_t BspReferenceIndex;  // 0x2  int16.
        std::int32_t ChecksumFromStructureBsp;  // 0x4  int32.
        MapStructure::Tag::Reference Unknown;  // 0x8  tagref.
        float        Brightness;  // 0x18  float32.
        MapStructure::Tag::Reference PrimaryMap;  // 0x1C  tagref.
        MapStructure::Tag::Reference IntensityMap;  // 0x2C  tagref.
        std::uint8_t  _pad_0x3C[0x4];  // undefined.
        std::uint8_t  _pad_0x40[0x4];  // undefined.
        std::uint8_t  _pad_0x44[0x4];  // undefined.
        // -> Lbsp_UnknownAEntry[]
        MapStructure::Tag::Block   UnknownA;  // 0x48  tagblock.
        // -> Lbsp_UnknownBEntry[]
        MapStructure::Tag::Block   UnknownB;  // 0x54  tagblock.
        // -> Lbsp_InstancedGeometryEntry[]
        MapStructure::Tag::Block   InstancedGeometry;  // 0x60  tagblock.
        // -> Lbsp_ColorsEntry[]
        MapStructure::Tag::Block   Colors;  // 0x6C  tagblock.
        std::uint32_t Flags_2;  // 0x78  flags32. [Processed=0, Available=1, Has Valid Budgets (Really)=2, Manual Resource Creation=3, Keep Raw Geometry=4, Don't Use Compressed Vertex Positions=5]
        // -> Lbsp_MeshesEntry[]
        MapStructure::Tag::Block   Meshes;  // 0x7C  tagblock.
        // -> Lbsp_CompressionInfoEntry[]
        MapStructure::Tag::Block   CompressionInfo;  // 0x88  tagblock.
        // -> Lbsp_PartSortingPositionEntry[]
        MapStructure::Tag::Block   PartSortingPosition;  // 0x94  tagblock.
        // -> Lbsp_UserDataEntry[]
        MapStructure::Tag::Block   UserData;  // 0xA0  tagblock.
        // -> Lbsp_PerMeshTemporaryEntry[]
        MapStructure::Tag::Block   PerMeshTemporary;  // 0xAC  tagblock.
        std::uint8_t  _pad_0xB8[0x4];  // undefined.
        std::uint8_t  _pad_0xBC[0x4];  // undefined.
        std::uint8_t  _pad_0xC0[0x4];  // undefined.
        // -> Lbsp_PerMeshNodeMapEntry[]
        MapStructure::Tag::Block   PerMeshNodeMap;  // 0xC4  tagblock.
        // -> Lbsp_PerMeshSubpartVisibilityEntry[]
        MapStructure::Tag::Block   PerMeshSubpartVisibility;  // 0xD0  tagblock.
        std::uint32_t BlockHere1;  // 0xDC  uint32.
        std::uint32_t BlockHere1_2;  // 0xE0  uint32.
        std::uint32_t BlockHere1_3;  // 0xE4  uint32.
        std::uint32_t BlockHere2;  // 0xE8  uint32.
        std::uint32_t BlockHere2_2;  // 0xEC  uint32.
        std::uint32_t BlockHere2_3;  // 0xF0  uint32.
        // -> Lbsp_PerInstanceLightmapTexcoordsEntry[]
        MapStructure::Tag::Block   PerInstanceLightmapTexcoords;  // 0xF4  tagblock.
        // -> Lbsp_WaterBoundingBoxEntry[]
        MapStructure::Tag::Block   WaterBoundingBox;  // 0x100  tagblock.
        std::uint32_t ZoneAssetDatum;  // 0x10C  datum.
        std::int32_t UselessPadding;  // 0x110  int32.
        // -> Lbsp_ConstantBufferInteropEntry[]
        MapStructure::Tag::Block   ConstantBufferInterop;  // 0x114  tagblock.
        // -> Lbsp_UnknownEntry[]
        MapStructure::Tag::Block   Unknown_8;  // 0x120  tagblock.
        // -> Lbsp_AirprobesEntry[]
        MapStructure::Tag::Block   Airprobes;  // 0x12C  tagblock.
        // -> Lbsp_UnknownEntry_2[]
        MapStructure::Tag::Block   Unknown_9;  // 0x138  tagblock.
        // -> Lbsp_UnknownEntry_3[]
        MapStructure::Tag::Block   Unknown_10;  // 0x144  tagblock.
        std::uint8_t  _pad_0x150[0x4];  // undefined.
        std::uint8_t  _pad_0x154[0x4];  // undefined.
        std::uint8_t  _pad_0x158[0x4];  // undefined.
        // -> Lbsp_SelfTrackEntry[]
        MapStructure::Tag::Block   SelfTrack;  // 0x15C  tagblock.
    };
    static_assert(sizeof(LbspData) == 0x168, "LbspData size mismatch");

}

#pragma pack(pop)
