// Auto-generated by TagTranspiler (GenerateOffset.py)
// Source XML: eqip.xml
// Base size: 0x424.

export module Map.Tag.Type:Eqip.Offset;

import std;

export namespace Map::Tag::Type::Eqip::Offset
{
    constexpr std::size_t k_ObjectType                                  = 0x0;  // enum16. [Biped=0x0, Vehicle=0x1, Weapon=0x2, Equipment=0x3, Terminal=0x4, Projectile=0x5, Scenery=0x6, Machine=0x7, Control=0x8, Sound Scenery=0x9, Crate=0xA, Creature=0xB, Giant=0xC, Effect Scenery=0xD]
    constexpr std::size_t k_SecondaryFlags                              = 0x2;  // flags16. [Does Not Affect Projectile Aiming=0]
    constexpr std::size_t k_Flags                                       = 0x4;  // flags32. [Does Not Cast Shadow=0, Search Cardinal Direction Lightmaps on Failure=1, Preserves Initial Damage Owner=2, Not A Pathfinding Obstacle=3, Extension Of Parent=4, Does Not Cause Collision Damage=5, Early Mover=6, Early Mover Localized Physics=7, Object Scales Attachments=8, Object Is Always On The Ceiling=9, Sample Enviroment Lighting Only Ignore Object Lighting=10, Effects Created By This Object Do Not Spawn Objects In Multiplayer=11, Does Not Collide With Camera=12, Force Collide With Camera=13, Damage Not Blocked By Obstructions=14, Does Not Damage Breakable Surfaces=15, Damage Non-Networked Children On Distributed Client On Object Death=16]
    constexpr std::size_t k_RuntimeFlags                                = 0x8;  // flags32. [Runtime Change Colors Allowed=0, Bit 1=1, Bit 2=2, Bit 3=3, Bit 4=4, Bit 5=5, Bit 6=6, Bit 7=7, Bit 8=8, Bit 9=9, Bit 10=10, Bit 11=11, Bit 12=12, Bit 13=13, Bit 14=14, Bit 15=15, Bit 16=16, Bit 17=17, Bit 18=18, Bit 19=19, Bit 20=20, Bit 21=21, Bit 22=22, Bit 23=23, Bit 24=24, Bit 25=25, Bit 26=26, Bit 27=27, Bit 28=28, Bit 29=29, Bit 30=30, Bit 31=31]
    constexpr std::size_t k_BoundingRadius                              = 0xC;  // float32.
    constexpr std::size_t k_BoundingOffset                              = 0x10;  // point3.
    constexpr std::size_t k_HorizontalAccelerationScale                 = 0x1C;  // float32.
    constexpr std::size_t k_VerticalAccelerationScale                   = 0x20;  // float32.
    constexpr std::size_t k_AngularAccelerationScale                    = 0x24;  // float32.
    constexpr std::size_t k_LightmapShadowMode                          = 0x28;  // enum16. [Default=0x0, Never=0x1, Always=0x2, Blur=0x3]
    constexpr std::size_t k_SweetenerSize                               = 0x2A;  // enum8. [Default=0x0, Small=0x1, Medium=0x2, Large=0x3]
    constexpr std::size_t k_WaterDensity                                = 0x2B;  // enum8. [Default=0x0, Super Floater=0x1, Floater=0x2, Neutral=0x3, Sinker=0x4, Super Sinker=0x5, None=0x6]
    constexpr std::size_t k_DynamicLightSphereRadius                    = 0x2C;  // float32.
    constexpr std::size_t k_DynamicLightSphereOffset                    = 0x30;  // point3.
    constexpr std::size_t k_GenericHudText                              = 0x3C;  // StringID.
    constexpr std::size_t k_GenericNameList                             = 0x40;  // TagReference.
    constexpr std::size_t k_GenericServiceTagList                       = 0x50;  // TagReference.
    constexpr std::size_t k_DefaultModelVariant                         = 0x60;  // StringID.
    constexpr std::size_t k_Model                                       = 0x64;  // TagReference.
    constexpr std::size_t k_CrateObject                                 = 0x74;  // TagReference.
    constexpr std::size_t k_CollisionDamage                             = 0x84;  // TagReference.
    constexpr std::size_t k_BrittleCollisionDamage                      = 0x94;  // TagReference.
    namespace EarlyMoverOrientedBoundingBox
    {
        // Array data.
        constexpr std::size_t k_Base      = 0xA4;
        constexpr std::size_t k_EntrySize = 0x2C;

        constexpr std::size_t k_NodeName                                    = 0x0;  // StringID.
        constexpr std::size_t k_RuntimeNodeIndex                            = 0x4;  // int32.
        constexpr std::size_t k_X                                           = 0x8;  // rangef.
        constexpr std::size_t k_Y                                           = 0x10;  // rangef.
        constexpr std::size_t k_Z                                           = 0x18;  // rangef.
        constexpr std::size_t k_Angles                                      = 0x20;  // degree3.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_CreationEffect                              = 0xB0;  // TagReference.
    constexpr std::size_t k_MaterialEffects                             = 0xC0;  // TagReference.
    constexpr std::size_t k_MeleeSound                                  = 0xD0;  // TagReference.
    namespace AiProperties
    {
        // Array data.
        constexpr std::size_t k_Base      = 0xE0;
        constexpr std::size_t k_EntrySize = 0x10;

        constexpr std::size_t k_Flags                                       = 0x0;  // flags32. [Destroyable Cover=0, Pathfinding Ignore When Dead=1, Dynamic Cover=2, Non Flight-Blocking=3, Dynamic Cover From Centre=4, Has Corner Markers=5, Idle When Flying=6, Consider For Interaction=7]
        constexpr std::size_t k_AiTypeName                                  = 0x4;  // StringID.
        constexpr std::size_t k_InteractionName                             = 0x8;  // StringID.
        constexpr std::size_t k_AiSize                                      = 0xC;  // enum16. [Default=0x0, Tiny=0x1, Small=0x2, Medium=0x3, Large=0x4, Huge=0x5, Immobile=0x6]
        constexpr std::size_t k_LeapJumpSpeed                               = 0xE;  // enum16. [None=0x0, Down=0x1, Step=0x2, Crouch=0x3, Stand=0x4, Storey=0x5, Tower=0x6, Infinite=0x7]

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace Functions
    {
        // Array data.
        constexpr std::size_t k_Base      = 0xEC;
        constexpr std::size_t k_EntrySize = 0x40;

        constexpr std::size_t k_Flags                                       = 0x0;  // flags32. [Invert=0, Mapping Does Not Controls Active=1, Always Active=2, Random Time Offset=3, Always Exports Value=4, Turn Off With Uses Magnitude=5]
        constexpr std::size_t k_ImportName                                  = 0x4;  // StringID.
        constexpr std::size_t k_ExportName                                  = 0x8;  // StringID.
        constexpr std::size_t k_TurnOffWith                                 = 0xC;  // StringID.
        constexpr std::size_t k_RangedInterpolationName                     = 0x10;  // StringID.
        constexpr std::size_t k_MinimumValue                                = 0x14;  // float32.
        constexpr std::size_t k_DefaultFunction                             = 0x18;  // DataReference.
        constexpr std::size_t k_ScaleBy                                     = 0x2C;  // StringID.
        namespace Interpolation
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x30;
            constexpr std::size_t k_EntrySize = 0x18;

            constexpr std::size_t k_InterpolationMode                           = 0x0;  // enum32. [Constant Velocity=0x0, Linear Acceleration=0x1, Damped Spring=0x2, Fractional=0x3]
            constexpr std::size_t k_LinearTravelTime                            = 0x4;  // float32.
            constexpr std::size_t k_Acceleration                                = 0x8;  // float32.
            constexpr std::size_t k_SpringK                                     = 0xC;  // float32.
            constexpr std::size_t k_SpringC                                     = 0x10;  // float32.
            constexpr std::size_t k_Fraction                                    = 0x14;  // float32.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        constexpr std::size_t k_RuntimeInterpolatorIndex                    = 0x3C;  // int32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace RuntimeInterpolatorFunctions
    {
        // Array data.
        constexpr std::size_t k_Base      = 0xF8;
        constexpr std::size_t k_EntrySize = 0x4;

        constexpr std::size_t k_RuntimeInterpolatorToObjectFunctionMapping  = 0x0;  // int32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace Attachments
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x104;
        constexpr std::size_t k_EntrySize = 0x20;

        constexpr std::size_t k_Type                                        = 0x0;  // TagReference.
        constexpr std::size_t k_Marker                                      = 0x10;  // StringID.
        constexpr std::size_t k_ChangeColor                                 = 0x14;  // enum8. [None=0x0, Primary=0x1, Secondary=0x2, Tertiary=0x3, Quaternary=0x4]
        constexpr std::size_t k_Flags                                       = 0x15;  // flags8. [Force Always On=0, Effect Size Scale From Object Scale=1]
        constexpr std::size_t k_Unknown                                     = 0x16;  // int16.
        constexpr std::size_t k_PrimaryScale                                = 0x18;  // StringID.
        constexpr std::size_t k_SecondaryScale                              = 0x1C;  // StringID.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace HullSurfaces
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x110;
        constexpr std::size_t k_EntrySize = 0x18;

        constexpr std::size_t k_Flags                                       = 0x0;  // flags16. [Works On Land=0, Effects Only=1]
        constexpr std::size_t k_Unknown                                     = 0x2;  // int16.
        constexpr std::size_t k_MarkerName                                  = 0x4;  // StringID.
        constexpr std::size_t k_Radius                                      = 0x8;  // float32.
        namespace Drag
        {
            // Array data.
            constexpr std::size_t k_Base      = 0xC;
            constexpr std::size_t k_EntrySize = 0x3C;

            constexpr std::size_t k_Material                                    = 0x0;  // StringID.
            constexpr std::size_t k_VelocityToPressureFunction                  = 0x4;  // DataReference.
            constexpr std::size_t k_MaximumVelocity                             = 0x18;  // float32.
            constexpr std::size_t k_VelocityToPressureFunction_2                = 0x1C;  // DataReference.
            constexpr std::size_t k_MaximumVelocity_2                           = 0x30;  // float32.
            constexpr std::size_t k_LinearDamping                               = 0x34;  // float32.
            constexpr std::size_t k_AngularDamping                              = 0x38;  // float32.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }


        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace Jetwash
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x11C;
        constexpr std::size_t k_EntrySize = 0x24;

        constexpr std::size_t k_MarkerName                                  = 0x0;  // StringID.
        constexpr std::size_t k_Radius                                      = 0x4;  // float32.
        constexpr std::size_t k_MaximumTraces                               = 0x8;  // int32.
        constexpr std::size_t k_MaximumEmissionLength                       = 0xC;  // float32.
        constexpr std::size_t k_TraceYawAngle                               = 0x10;  // ranged.
        constexpr std::size_t k_TracePitchAngle                             = 0x18;  // ranged.
        constexpr std::size_t k_ParticleOffset                              = 0x20;  // float32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace Widgets
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x128;
        constexpr std::size_t k_EntrySize = 0x10;

        constexpr std::size_t k_Type                                        = 0x0;  // TagReference.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace ChangeColors
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x134;
        constexpr std::size_t k_EntrySize = 0x18;

        namespace InitialPermutations
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x0;
            constexpr std::size_t k_EntrySize = 0x20;

            constexpr std::size_t k_Weight                                      = 0x0;  // float32.
            constexpr std::size_t k_ColorLowerBound                             = 0x4;  // colorf.
            constexpr std::size_t k_ColorUpperBound                             = 0x10;  // colorf.
            constexpr std::size_t k_VariantName                                 = 0x1C;  // StringID.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace Functions
        {
            // Array data.
            constexpr std::size_t k_Base      = 0xC;
            constexpr std::size_t k_EntrySize = 0x24;

            constexpr std::size_t k_ScaleFlags                                  = 0x0;  // flags32. [Blend In HSV=0, ...More Colors=1]
            constexpr std::size_t k_ColorLowerBound                             = 0x4;  // colorf.
            constexpr std::size_t k_ColorUpperBound                             = 0x10;  // colorf.
            constexpr std::size_t k_DarkenBy                                    = 0x1C;  // StringID.
            constexpr std::size_t k_ScaleBy                                     = 0x20;  // StringID.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }


        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace MultiplayerObject
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x140;
        constexpr std::size_t k_EntrySize = 0xBC;

        constexpr std::size_t k_GameEngineFlags                             = 0x0;  // flags8. [None=0, Sandbox=1, Megalo=2, Campaign=3, Survival=4]
        constexpr std::size_t k_Type                                        = 0x1;  // enum8. [Ordinary=0x0, Weapon=0x1, Grenade=0x2, Projectile=0x3, Powerup=0x4, Equipment=0x5, Ammo Pack=0x6, Light Land Vehicle=0x7, Heavy Land Vehicle=0x8, Flying Vehicle=0x9, Turret=0xA, Device=0xB, Teleporter 2Way=0xC, Teleporter Sender=0xD, Teleporter Receiver=0xE, Player Spawn Location=0xF, Player Respawn Zone=0x10, Secondary Objective=0x11, Primary Objective=0x12, Named Location Area=0x13, Danger Zone=0x14, Fireteam 1 Respawn Zone=0x15, Fireteam 2 Respawn Zone=0x16, Fireteam 3 Respawn Zone=0x17, Fireteam 4 Respawn Zone=0x18, Safe Volume=0x19, Kill Volume=0x1A, Cinematic Camera Position=0x1B]
        constexpr std::size_t k_TeleporterPassability                       = 0x2;  // flags8. [Disallow Players=0, Allow Light Land Vehicles=1, Allow Heavy Land Vehicles=2, Allow Flying Vehicles=3, Allow Projectiles=4]
        constexpr std::size_t k_Unknown                                     = 0x3;  // int8.
        constexpr std::size_t k_BoundaryWidthRadius                         = 0x4;  // float32.
        constexpr std::size_t k_BoundaryBoxLength                           = 0x8;  // float32.
        constexpr std::size_t k_BoundaryHeight                              = 0xC;  // float32.
        constexpr std::size_t k_BoundaryHeight_2                            = 0x10;  // float32.
        constexpr std::size_t k_BoundaryShape                               = 0x14;  // enum8. [Unused=0x0, Sphere=0x1, Cylinder=0x2, Box=0x3]
        constexpr std::size_t k_SpawnTimerType                              = 0x15;  // enum8. [Starts On Death=0x0, Starts On Disturbance=0x1]
        constexpr std::size_t k_DefaultSpawnTime                            = 0x16;  // int16.
        constexpr std::size_t k_DefaultAbandonmentTime                      = 0x18;  // int16.
        constexpr std::size_t k_Flags                                       = 0x1A;  // flags16. [Only Visible In Editor=0, Phased Physics In Forge=1, Valid Initial Player Spawn=2, Fixed Boundary Orientation=3, Candy Monitor Should Ignore=4, Inherit Owning Team Color=5, Boundary Volume Doesn't Kill Immediately=6]
        constexpr std::size_t k_NormalWeight                                = 0x1C;  // float32.
        constexpr std::size_t k_BoundaryCenterMarker                        = 0x20;  // StringID.
        constexpr std::size_t k_SpawnedObjectMarkerName                     = 0x24;  // StringID.
        constexpr std::size_t k_SpawnedObject                               = 0x28;  // TagReference.
        constexpr std::size_t k_BoundaryMaterialNotYetImplemented           = 0x38;  // StringID.
        constexpr std::size_t k_DefaultBoundaryStandardShader               = 0x3C;  // TagReference.
        constexpr std::size_t k_DefaultBoundaryOpaqueShader                 = 0x4C;  // TagReference.
        constexpr std::size_t k_SphereStandardShader                        = 0x5C;  // TagReference.
        constexpr std::size_t k_SphereOpaqueShader                          = 0x6C;  // TagReference.
        constexpr std::size_t k_CylinderStandardShader                      = 0x7C;  // TagReference.
        constexpr std::size_t k_CylinderOpaqueShader                        = 0x8C;  // TagReference.
        constexpr std::size_t k_BoxStandardShader                           = 0x9C;  // TagReference.
        constexpr std::size_t k_BoxOpaqueShader                             = 0xAC;  // TagReference.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_SimulationInterpolation                     = 0x14C;  // TagReference.
    namespace SpawnEffects
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x15C;
        constexpr std::size_t k_EntrySize = 0x30;

        constexpr std::size_t k_MultiplayerSpawnEffect                      = 0x0;  // TagReference.
        constexpr std::size_t k_SurvivalSpawnEffect                         = 0x10;  // TagReference.
        constexpr std::size_t k_CampaignSpawnEffect                         = 0x20;  // TagReference.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_Flags_2                                     = 0x168;  // flags32. [Always Maintains z Up=0, Destroyed by Explosions=1, Unaffected by Gravity=2, Bit 3=3, Bit 4=4, Bit 5=5, Bit 6=6, Bit 7=7, Bit 8=8, Bit 9=9, Bit 10=10, Bit 11=11, Bit 12=12, Bit 13=13, Bit 14=14, Bit 15=15, Bit 16=16, Bit 17=17, Bit 18=18, Bit 19=19, Bit 20=20, Bit 21=21, Bit 22=22, Bit 23=23, Bit 24=24, Bit 25=25, Bit 26=26, Bit 27=27, Bit 28=28, Bit 29=29, Bit 30=30, Bit 31=31]
    constexpr std::size_t k_PickupMessage                               = 0x16C;  // StringID.
    constexpr std::size_t k_SwapMessage                                 = 0x170;  // StringID.
    constexpr std::size_t k_DualPickupMessage                           = 0x174;  // StringID.
    constexpr std::size_t k_DualSwapMessage                             = 0x178;  // StringID.
    constexpr std::size_t k_PickedUpMessage                             = 0x17C;  // StringID.
    constexpr std::size_t k_SwitchToMessage                             = 0x180;  // StringID.
    constexpr std::size_t k_SwitchToFromAiMessage                       = 0x184;  // StringID.
    constexpr std::size_t k_NotifyEmptyMessage                          = 0x188;  // StringID.
    constexpr std::size_t k_OverheatedMessage                           = 0x18C;  // StringID.
    constexpr std::size_t k_PrivateUseFontIcon                          = 0x190;  // int32.
    constexpr std::size_t k_PrivateUseFontIconDual                      = 0x194;  // int32.
    constexpr std::size_t k_DetonationDamageEffect                      = 0x198;  // TagReference.
    constexpr std::size_t k_DetonationDelay                             = 0x1A8;  // rangef.
    constexpr std::size_t k_DetonatingEffect                            = 0x1B0;  // TagReference.
    constexpr std::size_t k_DetonationEffect                            = 0x1C0;  // TagReference.
    constexpr std::size_t k_GroundScale                                 = 0x1D0;  // float32.
    constexpr std::size_t k_SmallUnitArmedScale                         = 0x1D4;  // float32.
    constexpr std::size_t k_SmallUnitStowedScale                        = 0x1D8;  // float32.
    constexpr std::size_t k_MediumUnitArmedScale                        = 0x1DC;  // float32.
    constexpr std::size_t k_MediumUnitStowedScale                       = 0x1E0;  // float32.
    constexpr std::size_t k_LargeUnitArmedScale                         = 0x1E4;  // float32.
    constexpr std::size_t k_LargeUnitStowedScale                        = 0x1E8;  // float32.
    constexpr std::size_t k_HugeUnitArmedScale                          = 0x1EC;  // float32.
    constexpr std::size_t k_HugeUnitStowedScale                         = 0x1F0;  // float32.
    constexpr std::size_t k_GroundedFrictionSettings                    = 0x1F4;  // TagReference.
    constexpr std::size_t k_WarmupTime                                  = 0x204;  // float32.
    constexpr std::size_t k_Duration                                    = 0x208;  // float32.
    constexpr std::size_t k_CooldownTime                                = 0x20C;  // float32.
    constexpr std::size_t k_PhantomVolumeActivationTime                 = 0x210;  // float32.
    constexpr std::size_t k_EnergyRecoveryTime                          = 0x214;  // float32.
    constexpr std::size_t k_MinimumActivationEnergy                     = 0x218;  // float32.
    constexpr std::size_t k_ActivationEnergyCost                        = 0x21C;  // float32.
    constexpr std::size_t k_DeactivationEnergyCost                      = 0x220;  // float32.
    constexpr std::size_t k_ActiveEnergyRate                            = 0x224;  // float32.
    constexpr std::size_t k_RechargeRate                                = 0x228;  // float32.
    constexpr std::size_t k_MovementSpeedToEnergyRateFunction           = 0x22C;  // DataReference.
    constexpr std::size_t k_MovementSpeedDomain                         = 0x240;  // float32.
    constexpr std::size_t k_Flags_3                                     = 0x244;  // flags32. [Pathfinding Obstacle=0, Equipment Is Dangerous To AI=1, Never Dropped By AI=2, Protects Parent From AOE=3, Third Person Camera While Active=4, Third Person Camera Always=5, Hide Reticule While Active=6, Cannot Be Active While Airborne=7, Cannot Activate While Airborne=8, Cannot Activate While Standing On Biped=9, Cannot Activate In Vehicle=10, Deactivated By Firing Weapon=11, Deactivated By Melee Attacking=12, Deactivated By Throwing Grenade=13, Bit 14=14, Use Forced Primary Change Color=15, Use Forced Secondary Change Color=16, Duck Sound While Active=17, Blocks Tracking While Active=18, Readies Weapon On Deactivation=19, Drops Support/Must Be Readied Weapons On Activation=20, Hides Weapon On Activation=21, Can Not Be Picked Up By Player=22, Bit 23=23, Bit 24=24, Bit 25=25, Bit 26=26, Bit 27=27, Bit 28=28, Bit 29=29, Bit 30=30, Bit 31=31]
    constexpr std::size_t k_Charges                                     = 0x248;  // int16.
    constexpr std::size_t k_ActivationType                              = 0x24A;  // enum8. [Toggle=0x0, Hold=0x1]
    constexpr std::size_t k_ObjectNoiseAdjustment                       = 0x24B;  // int8.
    constexpr std::size_t k_UnitStowMarkerName                          = 0x24C;  // StringID.
    constexpr std::size_t k_ForcedPrimaryChangeColor                    = 0x250;  // colorf.
    constexpr std::size_t k_ForcedSecondaryChangeColor                  = 0x260;  // colorf.
    constexpr std::size_t k_DangerRadius                                = 0x270;  // float32.
    constexpr std::size_t k_MinimumDeploymentDistance                   = 0x274;  // float32.
    constexpr std::size_t k_AwarenessTime                               = 0x278;  // float32.
    constexpr std::size_t k_AiDialogueEquipmentType                     = 0x27C;  // StringID.
    namespace OverrideCamera
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x280;
        constexpr std::size_t k_EntrySize = 0x78;

        constexpr std::size_t k_Flags                                       = 0x0;  // flags16. [Pitch Bounds Absolute Space=0, Only Collides With Environment=1, Hides Player-Unit From Camera=2, Use Aiming Vector Instead Of Marker Forward=3]
        constexpr std::size_t k_Unknown                                     = 0x2;  // int16.
        constexpr std::size_t k_CameraMarkerName                            = 0x4;  // StringID.
        constexpr std::size_t k_PitchAutoLevel                              = 0x8;  // degree.
        constexpr std::size_t k_PitchRange                                  = 0xC;  // ranged.
        namespace CameraTracks
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x14;
            constexpr std::size_t k_EntrySize = 0x20;

            constexpr std::size_t k_Track                                       = 0x0;  // TagReference.
            constexpr std::size_t k_ScreenEffect                                = 0x10;  // TagReference.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        constexpr std::size_t k_PitchMinimumSpring                          = 0x20;  // degree.
        constexpr std::size_t k_PitchMaximumSpring                          = 0x24;  // degree.
        constexpr std::size_t k_SpringVelocity                              = 0x28;  // degree.
        constexpr std::size_t k_LookAcceleration                            = 0x2C;  // degree.
        constexpr std::size_t k_LookDeceleration                            = 0x30;  // degree.
        constexpr std::size_t k_LookAccelerationSmoothingFraction           = 0x34;  // float32.
        constexpr std::size_t k_OverrideFieldOfView                         = 0x38;  // degree.
        constexpr std::size_t k_CylinderFraction                            = 0x3C;  // float32.
        constexpr std::size_t k_ObstructionTestAngle                        = 0x40;  // degree.
        constexpr std::size_t k_ObstructionMaximumInwardAcceleration        = 0x44;  // float32.
        constexpr std::size_t k_ObstructionMaximumOutwardAcceleration       = 0x48;  // float32.
        constexpr std::size_t k_ObstructionMaximumVelocity                  = 0x4C;  // float32.
        constexpr std::size_t k_ObstructionReturnDelay                      = 0x50;  // float32.
        namespace CameraAcceleration
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x54;
            constexpr std::size_t k_EntrySize = 0x70;

            constexpr std::size_t k_MaximumCameraVelocity                       = 0x0;  // float32.
            constexpr std::size_t k_InputVariable                               = 0x4;  // enum8. [Linear Velocity=0x0, Linear Acceleration=0x1, Yaw=0x2, Pitch=0x3, Roll=0x4]
            constexpr std::size_t k_Unknown                                     = 0x5;  // int8.
            constexpr std::size_t k_Unknown_2                                   = 0x6;  // int16.
            constexpr std::size_t k_Function                                    = 0x8;  // DataReference.
            constexpr std::size_t k_MaximumValue                                = 0x1C;  // float32.
            constexpr std::size_t k_CameraScaleAxial                            = 0x20;  // float32.
            constexpr std::size_t k_CameraScalePerpendicular                    = 0x24;  // float32.
            constexpr std::size_t k_InputVariable_2                             = 0x28;  // enum8. [Linear Velocity=0x0, Linear Acceleration=0x1, Yaw=0x2, Pitch=0x3, Roll=0x4]
            constexpr std::size_t k_Unknown_3                                   = 0x29;  // int8.
            constexpr std::size_t k_Unknown_4                                   = 0x2A;  // int16.
            constexpr std::size_t k_Function_2                                  = 0x2C;  // DataReference.
            constexpr std::size_t k_MaximumValue_2                              = 0x40;  // float32.
            constexpr std::size_t k_CameraScaleAxial_2                          = 0x44;  // float32.
            constexpr std::size_t k_CameraScalePerpendicular_2                  = 0x48;  // float32.
            constexpr std::size_t k_InputVariable_3                             = 0x4C;  // enum8. [Linear Velocity=0x0, Linear Acceleration=0x1, Yaw=0x2, Pitch=0x3, Roll=0x4]
            constexpr std::size_t k_Unknown_5                                   = 0x4D;  // int8.
            constexpr std::size_t k_Unknown_6                                   = 0x4E;  // int16.
            constexpr std::size_t k_Function_3                                  = 0x50;  // DataReference.
            constexpr std::size_t k_MaximumValue_3                              = 0x64;  // float32.
            constexpr std::size_t k_CameraScaleAxial_3                          = 0x68;  // float32.
            constexpr std::size_t k_CameraScalePerpendicular_3                  = 0x6C;  // float32.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace MoveStickOverrides
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x60;
            constexpr std::size_t k_EntrySize = 0x28;

            constexpr std::size_t k_InputShape                                  = 0x0;  // enum8. [None=0x0, Unit Circle=0x1, Unit Square=0x2]
            constexpr std::size_t k_Unknown                                     = 0x1;  // int8.
            constexpr std::size_t k_Unknown_2                                   = 0x2;  // int16.
            constexpr std::size_t k_PegThreshold                                = 0x4;  // float32.
            constexpr std::size_t k_PeggedTime                                  = 0x8;  // point2.
            constexpr std::size_t k_PeggedScale                                 = 0x10;  // point2.
            constexpr std::size_t k_PegMaximumAngularVelocity                   = 0x18;  // degree.
            namespace InputMappingFunction
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x1C;
                constexpr std::size_t k_EntrySize = 0x14;

                constexpr std::size_t k_Function                                    = 0x0;  // DataReference.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }


            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace LookStickOverrides
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x6C;
            constexpr std::size_t k_EntrySize = 0x28;

            constexpr std::size_t k_InputShape                                  = 0x0;  // enum8. [None=0x0, Unit Circle=0x1, Unit Square=0x2]
            constexpr std::size_t k_Unknown                                     = 0x1;  // int8.
            constexpr std::size_t k_Unknown_2                                   = 0x2;  // int16.
            constexpr std::size_t k_PegThreshold                                = 0x4;  // float32.
            constexpr std::size_t k_PeggedTime                                  = 0x8;  // point2.
            constexpr std::size_t k_PeggedScale                                 = 0x10;  // point2.
            constexpr std::size_t k_PegMaximumAngularVelocity                   = 0x18;  // degree.
            namespace InputMappingFunction
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x1C;
                constexpr std::size_t k_EntrySize = 0x14;

                constexpr std::size_t k_Function                                    = 0x0;  // DataReference.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }


            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }


        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace MultiplayerPowerup
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x28C;
        constexpr std::size_t k_EntrySize = 0x4;

        constexpr std::size_t k_Flavor                                      = 0x0;  // enum32. [Red Powerup=0x0, Blue Powerup=0x1, Yellow Powerup=0x2]

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace Spawner
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x298;
        constexpr std::size_t k_EntrySize = 0x34;

        constexpr std::size_t k_SpawnedObject                               = 0x0;  // TagReference.
        constexpr std::size_t k_SpawnedEffect                               = 0x10;  // TagReference.
        constexpr std::size_t k_SpawnRadius                                 = 0x20;  // float32.
        constexpr std::size_t k_SpawnZOffset                                = 0x24;  // float32.
        constexpr std::size_t k_SpawnAreaRadius                             = 0x28;  // float32.
        constexpr std::size_t k_SpawnVelocity                               = 0x2C;  // float32.
        constexpr std::size_t k_Type                                        = 0x30;  // enum16. [Along Aiming Vector=0x0, Camera Position z Plane=0x1, Foot Position z Plane=0x2]
        constexpr std::size_t k_Unknown                                     = 0x32;  // int16.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace ProximityMine
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x2A4;
        constexpr std::size_t k_EntrySize = 0x30;

        constexpr std::size_t k_ExplosionEffect                             = 0x0;  // TagReference.
        constexpr std::size_t k_ExplosionDamageEffect                       = 0x10;  // TagReference.
        constexpr std::size_t k_ArmTime                                     = 0x20;  // float32.
        constexpr std::size_t k_SelfDestructTime                            = 0x24;  // float32.
        constexpr std::size_t k_TriggerTime                                 = 0x28;  // float32.
        constexpr std::size_t k_TriggerVelocity                             = 0x2C;  // float32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace MotionTrackerNoise
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x2B0;
        constexpr std::size_t k_EntrySize = 0x10;

        constexpr std::size_t k_ArmTime                                     = 0x0;  // float32.
        constexpr std::size_t k_NoiseRadius                                 = 0x4;  // float32.
        constexpr std::size_t k_NoiseCount                                  = 0x8;  // int32.
        constexpr std::size_t k_FlashRadius                                 = 0xC;  // float32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_Unknown                                     = 0x2BC;  // uint32.
    constexpr std::size_t k_Unknown_2                                   = 0x2C0;  // uint32.
    constexpr std::size_t k_Unknown_3                                   = 0x2C4;  // uint32.
    namespace InvincibilityMode
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x2C8;
        constexpr std::size_t k_EntrySize = 0x80;

        constexpr std::size_t k_InvincibilityGlobalMaterialName             = 0x0;  // StringID.
        constexpr std::size_t k_InvincibilityGlobalMaterialIndex            = 0x4;  // int16.
        constexpr std::size_t k_Unknown                                     = 0x6;  // int16.
        constexpr std::size_t k_ShieldRechargeRate                          = 0x8;  // float32.
        constexpr std::size_t k_ShieldMaximumRechargeLevel                  = 0xC;  // float32.
        constexpr std::size_t k_OverrideCollisionDamage                     = 0x10;  // TagReference.
        constexpr std::size_t k_AiMeleeReflectDamage                        = 0x20;  // TagReference.
        constexpr std::size_t k_PlayerMeleeReflectDamage                    = 0x30;  // TagReference.
        constexpr std::size_t k_LoopInvincibilityShieldName                 = 0x40;  // StringID.
        constexpr std::size_t k_PostInvincibilityShieldName                 = 0x44;  // StringID.
        constexpr std::size_t k_PostInvincibilityTimeToShieldLevelFunction  = 0x48;  // DataReference.
        constexpr std::size_t k_MaximumVerticalVelocity                     = 0x5C;  // float32.
        constexpr std::size_t k_ActiveVerticalVelocityDampingFunction       = 0x60;  // DataReference.
        namespace ThresholdEffects
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x74;
            constexpr std::size_t k_EntrySize = 0x18;

            constexpr std::size_t k_ThresholdEnergyBurned                       = 0x0;  // float32.
            constexpr std::size_t k_EnergyAdjustment                            = 0x4;  // float32.
            constexpr std::size_t k_Effect                                      = 0x8;  // TagReference.

            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }


        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace TreeOfLife
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x2D4;
        constexpr std::size_t k_EntrySize = 0xC;

        constexpr std::size_t k_Flags                                       = 0x0;  // flags32. [Un-Stuns Shields=0, Un-Stuns Body=1]
        constexpr std::size_t k_OriginMarker                                = 0x4;  // StringID.
        constexpr std::size_t k_Radius                                      = 0x8;  // float32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace Shapeshifter
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x2E0;
        constexpr std::size_t k_EntrySize = 0xC;

        constexpr std::size_t k_RegionName                                  = 0x0;  // StringID.
        constexpr std::size_t k_InactivePermutationName                     = 0x4;  // StringID.
        constexpr std::size_t k_ActivePermutationName                       = 0x8;  // StringID.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace PlayerTraitField
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x2EC;
        constexpr std::size_t k_EntrySize = 0x1C;

        constexpr std::size_t k_Unknown                                     = 0x0;  // undefined.
        namespace ActivePlayerTraits
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x4;
            constexpr std::size_t k_EntrySize = 0x3C;

            namespace VitalityTraits
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x0;
                constexpr std::size_t k_EntrySize = 0xC;

                constexpr std::size_t k_DamageResistance                            = 0x0;  // enum8. [Unchanged=0x0, 10%=0x1, 50%=0x2, 90%=0x3, 100%=0x4, 110%=0x5, 150%=0x6, 200%=0x7, 300%=0x8, 500%=0x9, 1000%=0xA, 2000%=0xB, Invulnerable=0xC]
                constexpr std::size_t k_HealthMultiplier                            = 0x1;  // enum8. [Unchanged=0x0, 0%=0x1, 100%=0x2, 150%=0x3, 200%=0x4, 300%=0x5, 400%=0x6]
                constexpr std::size_t k_HealthRechargeRate                          = 0x2;  // enum8. [Unchanged=0x0, -25%=0x1, -10%=0x2, -5%=0x3, 0%=0x4, 10%=0x5, 25%=0x6, 50%=0x7, 75%=0x8, 90%=0x9, 100%=0xA, 110%=0xB, 125%=0xC, 150%=0xD, 200%=0xE]
                constexpr std::size_t k_ShieldMultiplier                            = 0x3;  // enum8. [Unchanged=0x0, No Shields=0x1, Normal Shields=0x2, 1.5x Overshields=0x3, 2x Overshields=0x4, 3x Overshields=0x5, 4x Overshields=0x6]
                constexpr std::size_t k_ShieldRechargeRate                          = 0x4;  // enum8. [Unchanged=0x0, -25%=0x1, -10%=0x2, -5%=0x3, 0%=0x4, 10%=0x5, 25%=0x6, 50%=0x7, 75%=0x8, 90%=0x9, 100%=0xA, 110%=0xB, 125%=0xC, 150%=0xD, 200%=0xE]
                constexpr std::size_t k_ShieldRechargeRate2                         = 0x5;  // enum8. [Unchanged=0x0, -25%=0x1, -10%=0x2, -5%=0x3, 0%=0x4, 10%=0x5, 25%=0x6, 50%=0x7, 75%=0x8, 90%=0x9, 100%=0xA, 110%=0xB, 125%=0xC, 150%=0xD, 200%=0xE]
                constexpr std::size_t k_HeadshotImmunity                            = 0x6;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_ShieldVampirism                             = 0x7;  // enum8. [Unchanged=0x0, Disabled=0x1, 10%=0x2, 25%=0x3, 50%=0x4, 100%=0x5]
                constexpr std::size_t k_AssassinationImmunity                       = 0x8;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_Deathless                                   = 0x9;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_Unknown                                     = 0xA;  // int8.
                constexpr std::size_t k_Unknown_2                                   = 0xB;  // int8.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }

            namespace WeaponTraits
            {
                // Array data.
                constexpr std::size_t k_Base      = 0xC;
                constexpr std::size_t k_EntrySize = 0x18;

                constexpr std::size_t k_DamageModifier                              = 0x0;  // enum8. [Unchanged=0x0, 0%=0x1, 25%=0x2, 50%=0x3, 75%=0x4, 90%=0x5, 100%=0x6, 110%=0x7, 125%=0x8, 150%=0x9, 200%=0xA, 300%=0xB, Instant Kill=0xC]
                constexpr std::size_t k_MeleeDamageModifier                         = 0x1;  // enum8. [Unchanged=0x0, 0%=0x1, 25%=0x2, 50%=0x3, 75%=0x4, 90%=0x5, 100%=0x6, 110%=0x7, 125%=0x8, 150%=0x9, 200%=0xA, 300%=0xB, Instant Kill=0xC]
                constexpr std::size_t k_GrenadeRegeneration                         = 0x2;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_WeaponPickup                                = 0x3;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_GrenadeCount                                = 0x4;  // enum8. [Unchanged=0x0, Map Default=0x1, None=0x2, 1 Frag=0x3, 2 Frags=0x4, 3 Frags=0x5, 4 Frags=0x6, 1 Plasma=0x7, 2 Plasmas=0x8, 3 Plasmas=0x9, 4 Plasmas=0xA, 1x Each=0xB, 2x Each=0xC, 3x Each=0xD, 4x Each=0xE]
                constexpr std::size_t k_InfiniteAmmo                                = 0x5;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2, Bottomless Clip=0x3]
                constexpr std::size_t k_EquipmentUsage                              = 0x6;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2, Unknown=0x3]
                constexpr std::size_t k_EquipmentDrop                               = 0x7;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_InfiniteEquipment                           = 0x8;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_Unknown                                     = 0x9;  // int8.
                constexpr std::size_t k_Unknown_2                                   = 0xA;  // int8.
                constexpr std::size_t k_Unknown_3                                   = 0xB;  // int8.
                constexpr std::size_t k_PrimaryWeapon                               = 0xC;  // StringID.
                constexpr std::size_t k_SecondaryWeapon                             = 0x10;  // StringID.
                constexpr std::size_t k_Equipment                                   = 0x14;  // StringID.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }

            namespace MovementTraits
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x18;
                constexpr std::size_t k_EntrySize = 0x8;

                constexpr std::size_t k_PlayerSpeed                                 = 0x0;  // enum8. [Unchanged=0x0, 0%=0x1, 25%=0x2, 50%=0x3, 75%=0x4, 90%=0x5, 100%=0x6, 110%=0x7, 120%=0x8, 130%=0x9, 140%=0xA, 150%=0xB, 160%=0xC, 170%=0xD, 180%=0xE, 190%=0xF, 200%=0x10, 300%=0x11]
                constexpr std::size_t k_PlayerGravity                               = 0x1;  // enum8. [Unchanged=0x0, 50%=0x1, 75%=0x2, 100%=0x3, 150%=0x4, 200%=0x5, 250%=0x6, 300%=0x7, 350%=0x8, 400%=0x9, 450%=0xA, 500%=0xB, 550%=0xC, 600%=0xD]
                constexpr std::size_t k_VehicleUse                                  = 0x2;  // enum8. [Unchanged=0x0, None=0x1, Passenger Only=0x2, Driver Only=0x3, Gunner Only=0x4, No Passenger=0x5, No Driver=0x6, No Gunner=0x7, Full Use=0x8]
                constexpr std::size_t k_DoubleJump                                  = 0x3;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_JumpHeight                                  = 0x4;  // int32.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }

            namespace AppearanceTraits
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x24;
                constexpr std::size_t k_EntrySize = 0x8;

                constexpr std::size_t k_ActiveCamo                                  = 0x0;  // enum8. [Unchanged=0x0, Disabled=0x1, Bad Camo=0x2, Poor Camo=0x3, Good Camo=0x4, Invisible=0x5]
                constexpr std::size_t k_Waypoint                                    = 0x1;  // enum8. [Unchanged=0x0, None=0x1, Visible To Allies=0x2, Visible To Everyone=0x3]
                constexpr std::size_t k_VisibleName                                 = 0x2;  // enum8. [Unchanged=0x0, None=0x1, Visible To Allies=0x2, Visible To Everyone=0x3]
                constexpr std::size_t k_Aura                                        = 0x3;  // enum8. [Unchanged=0x0, Disabled=0x1, Team=0x2, Black=0x3, White=0x4]
                constexpr std::size_t k_ForcedColor                                 = 0x4;  // enum8. [Unchanged=0x0, Disabled=0x1, Red=0x2, Blue=0x3, Green=0x4, Orange=0x5, Purple=0x6, Gold=0x7, Brown=0x8, Pink=0x9, White=0xA, Black=0xB, Zombie=0xC, Pink (Unused)=0xD]
                constexpr std::size_t k_Unknown                                     = 0x5;  // int8.
                constexpr std::size_t k_Unknown_2                                   = 0x6;  // int8.
                constexpr std::size_t k_Unknown_3                                   = 0x7;  // int8.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }

            namespace SensorTraits
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x30;
                constexpr std::size_t k_EntrySize = 0x4;

                constexpr std::size_t k_MotionTrackerMode                           = 0x0;  // enum8. [Unchanged=0x0, Disabled=0x1, Ally Movement=0x2, Player Movement=0x3, Player Locations=0x4]
                constexpr std::size_t k_MotionTrackerRange                          = 0x1;  // enum8. [Unchanged=0x0, 10m=0x1, 15m=0x2, 25m=0x3, 50m=0x4, 75m=0x5, 100m=0x6, 150m=0x7]
                constexpr std::size_t k_DirectionalDamageIndicator                  = 0x2;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_Unknown                                     = 0x3;  // int8.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }


            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace InactivePlayerTraits
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x10;
            constexpr std::size_t k_EntrySize = 0x3C;

            namespace VitalityTraits
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x0;
                constexpr std::size_t k_EntrySize = 0xC;

                constexpr std::size_t k_DamageResistance                            = 0x0;  // enum8. [Unchanged=0x0, 10%=0x1, 50%=0x2, 90%=0x3, 100%=0x4, 110%=0x5, 150%=0x6, 200%=0x7, 300%=0x8, 500%=0x9, 1000%=0xA, 2000%=0xB, Invulnerable=0xC]
                constexpr std::size_t k_HealthMultiplier                            = 0x1;  // enum8. [Unchanged=0x0, 0%=0x1, 100%=0x2, 150%=0x3, 200%=0x4, 300%=0x5, 400%=0x6]
                constexpr std::size_t k_HealthRechargeRate                          = 0x2;  // enum8. [Unchanged=0x0, -25%=0x1, -10%=0x2, -5%=0x3, 0%=0x4, 10%=0x5, 25%=0x6, 50%=0x7, 75%=0x8, 90%=0x9, 100%=0xA, 110%=0xB, 125%=0xC, 150%=0xD, 200%=0xE]
                constexpr std::size_t k_ShieldMultiplier                            = 0x3;  // enum8. [Unchanged=0x0, No Shields=0x1, Normal Shields=0x2, 1.5x Overshields=0x3, 2x Overshields=0x4, 3x Overshields=0x5, 4x Overshields=0x6]
                constexpr std::size_t k_ShieldRechargeRate                          = 0x4;  // enum8. [Unchanged=0x0, -25%=0x1, -10%=0x2, -5%=0x3, 0%=0x4, 10%=0x5, 25%=0x6, 50%=0x7, 75%=0x8, 90%=0x9, 100%=0xA, 110%=0xB, 125%=0xC, 150%=0xD, 200%=0xE]
                constexpr std::size_t k_ShieldRechargeRate2                         = 0x5;  // enum8. [Unchanged=0x0, -25%=0x1, -10%=0x2, -5%=0x3, 0%=0x4, 10%=0x5, 25%=0x6, 50%=0x7, 75%=0x8, 90%=0x9, 100%=0xA, 110%=0xB, 125%=0xC, 150%=0xD, 200%=0xE]
                constexpr std::size_t k_HeadshotImmunity                            = 0x6;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_ShieldVampirism                             = 0x7;  // enum8. [Unchanged=0x0, Disabled=0x1, 10%=0x2, 25%=0x3, 50%=0x4, 100%=0x5]
                constexpr std::size_t k_AssassinationImmunity                       = 0x8;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_Deathless                                   = 0x9;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_Unknown                                     = 0xA;  // int8.
                constexpr std::size_t k_Unknown_2                                   = 0xB;  // int8.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }

            namespace WeaponTraits
            {
                // Array data.
                constexpr std::size_t k_Base      = 0xC;
                constexpr std::size_t k_EntrySize = 0x18;

                constexpr std::size_t k_DamageModifier                              = 0x0;  // enum8. [Unchanged=0x0, 0%=0x1, 25%=0x2, 50%=0x3, 75%=0x4, 90%=0x5, 100%=0x6, 110%=0x7, 125%=0x8, 150%=0x9, 200%=0xA, 300%=0xB, Instant Kill=0xC]
                constexpr std::size_t k_MeleeDamageModifier                         = 0x1;  // enum8. [Unchanged=0x0, 0%=0x1, 25%=0x2, 50%=0x3, 75%=0x4, 90%=0x5, 100%=0x6, 110%=0x7, 125%=0x8, 150%=0x9, 200%=0xA, 300%=0xB, Instant Kill=0xC]
                constexpr std::size_t k_GrenadeRegeneration                         = 0x2;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_WeaponPickup                                = 0x3;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_GrenadeCount                                = 0x4;  // enum8. [Unchanged=0x0, Map Default=0x1, None=0x2, 1 Frag=0x3, 2 Frags=0x4, 3 Frags=0x5, 4 Frags=0x6, 1 Plasma=0x7, 2 Plasmas=0x8, 3 Plasmas=0x9, 4 Plasmas=0xA, 1x Each=0xB, 2x Each=0xC, 3x Each=0xD, 4x Each=0xE]
                constexpr std::size_t k_InfiniteAmmo                                = 0x5;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2, Bottomless Clip=0x3]
                constexpr std::size_t k_EquipmentUsage                              = 0x6;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2, Unknown=0x3]
                constexpr std::size_t k_EquipmentDrop                               = 0x7;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_InfiniteEquipment                           = 0x8;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_Unknown                                     = 0x9;  // int8.
                constexpr std::size_t k_Unknown_2                                   = 0xA;  // int8.
                constexpr std::size_t k_Unknown_3                                   = 0xB;  // int8.
                constexpr std::size_t k_PrimaryWeapon                               = 0xC;  // StringID.
                constexpr std::size_t k_SecondaryWeapon                             = 0x10;  // StringID.
                constexpr std::size_t k_Equipment                                   = 0x14;  // StringID.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }

            namespace MovementTraits
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x18;
                constexpr std::size_t k_EntrySize = 0x8;

                constexpr std::size_t k_PlayerSpeed                                 = 0x0;  // enum8. [Unchanged=0x0, 0%=0x1, 25%=0x2, 50%=0x3, 75%=0x4, 90%=0x5, 100%=0x6, 110%=0x7, 120%=0x8, 130%=0x9, 140%=0xA, 150%=0xB, 160%=0xC, 170%=0xD, 180%=0xE, 190%=0xF, 200%=0x10, 300%=0x11]
                constexpr std::size_t k_PlayerGravity                               = 0x1;  // enum8. [Unchanged=0x0, 50%=0x1, 75%=0x2, 100%=0x3, 150%=0x4, 200%=0x5, 250%=0x6, 300%=0x7, 350%=0x8, 400%=0x9, 450%=0xA, 500%=0xB, 550%=0xC, 600%=0xD]
                constexpr std::size_t k_VehicleUse                                  = 0x2;  // enum8. [Unchanged=0x0, None=0x1, Passenger Only=0x2, Driver Only=0x3, Gunner Only=0x4, No Passenger=0x5, No Driver=0x6, No Gunner=0x7, Full Use=0x8]
                constexpr std::size_t k_DoubleJump                                  = 0x3;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_JumpHeight                                  = 0x4;  // int32.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }

            namespace AppearanceTraits
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x24;
                constexpr std::size_t k_EntrySize = 0x8;

                constexpr std::size_t k_ActiveCamo                                  = 0x0;  // enum8. [Unchanged=0x0, Disabled=0x1, Bad Camo=0x2, Poor Camo=0x3, Good Camo=0x4, Invisible=0x5]
                constexpr std::size_t k_Waypoint                                    = 0x1;  // enum8. [Unchanged=0x0, None=0x1, Visible To Allies=0x2, Visible To Everyone=0x3]
                constexpr std::size_t k_VisibleName                                 = 0x2;  // enum8. [Unchanged=0x0, None=0x1, Visible To Allies=0x2, Visible To Everyone=0x3]
                constexpr std::size_t k_Aura                                        = 0x3;  // enum8. [Unchanged=0x0, Disabled=0x1, Team=0x2, Black=0x3, White=0x4]
                constexpr std::size_t k_ForcedColor                                 = 0x4;  // enum8. [Unchanged=0x0, Disabled=0x1, Red=0x2, Blue=0x3, Green=0x4, Orange=0x5, Purple=0x6, Gold=0x7, Brown=0x8, Pink=0x9, White=0xA, Black=0xB, Zombie=0xC, Pink (Unused)=0xD]
                constexpr std::size_t k_Unknown                                     = 0x5;  // int8.
                constexpr std::size_t k_Unknown_2                                   = 0x6;  // int8.
                constexpr std::size_t k_Unknown_3                                   = 0x7;  // int8.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }

            namespace SensorTraits
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x30;
                constexpr std::size_t k_EntrySize = 0x4;

                constexpr std::size_t k_MotionTrackerMode                           = 0x0;  // enum8. [Unchanged=0x0, Disabled=0x1, Ally Movement=0x2, Player Movement=0x3, Player Locations=0x4]
                constexpr std::size_t k_MotionTrackerRange                          = 0x1;  // enum8. [Unchanged=0x0, 10m=0x1, 15m=0x2, 25m=0x3, 50m=0x4, 75m=0x5, 100m=0x6, 150m=0x7]
                constexpr std::size_t k_DirectionalDamageIndicator                  = 0x2;  // enum8. [Unchanged=0x0, Disabled=0x1, Enabled=0x2]
                constexpr std::size_t k_Unknown                                     = 0x3;  // int8.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }


            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }


        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace AiTraitField
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x2F8;
        constexpr std::size_t k_EntrySize = 0x18;

        namespace ActiveAiEquipmentTraits
        {
            // Array data.
            constexpr std::size_t k_Base      = 0x0;
            constexpr std::size_t k_EntrySize = 0xC;

            namespace AppearanceTraits
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x0;
                constexpr std::size_t k_EntrySize = 0x4;

                constexpr std::size_t k_ActiveCamoSetting                           = 0x0;  // enum8. [Unchanged=0x0, Off=0x1, Poor=0x2, Good=0x3, Excellent=0x4, Invisible=0x5]
                constexpr std::size_t k_Unknown                                     = 0x1;  // int8.
                constexpr std::size_t k_Unknown_2                                   = 0x2;  // int16.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }


            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }

        namespace InactiveAiEquipmentTraits
        {
            // Array data.
            constexpr std::size_t k_Base      = 0xC;
            constexpr std::size_t k_EntrySize = 0xC;

            namespace AppearanceTraits
            {
                // Array data.
                constexpr std::size_t k_Base      = 0x0;
                constexpr std::size_t k_EntrySize = 0x4;

                constexpr std::size_t k_ActiveCamoSetting                           = 0x0;  // enum8. [Unchanged=0x0, Off=0x1, Poor=0x2, Good=0x3, Excellent=0x4, Invisible=0x5]
                constexpr std::size_t k_Unknown                                     = 0x1;  // int8.
                constexpr std::size_t k_Unknown_2                                   = 0x2;  // int16.

                constexpr std::size_t EntryOffset(std::size_t index)
                {
                    return k_Base + (index * k_EntrySize);
                }
            }


            constexpr std::size_t EntryOffset(std::size_t index)
            {
                return k_Base + (index * k_EntrySize);
            }
        }


        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace RepulsorField
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x304;
        constexpr std::size_t k_EntrySize = 0xC;

        constexpr std::size_t k_Flags                                       = 0x0;  // flags32. [Affects Projectiles=0, Affects Vehicles=1, Affects Bipeds=2]
        constexpr std::size_t k_Radius                                      = 0x4;  // float32.
        constexpr std::size_t k_Power                                       = 0x8;  // float32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace Iwhbydaddy
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x310;
        constexpr std::size_t k_EntrySize = 0x18;

        constexpr std::size_t k_ChildObject                                 = 0x0;  // TagReference.
        constexpr std::size_t k_VisibilityFlags                             = 0x10;  // flags32. [Inactive Unstowed=0, Inactive Stowed=1, Active Unstowed=2, Active Stowed=3]
        constexpr std::size_t k_ShieldDamageToEnergyScale                   = 0x14;  // float32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_Unknown_4                                   = 0x31C;  // uint32.
    constexpr std::size_t k_Unknown_5                                   = 0x320;  // uint32.
    constexpr std::size_t k_Unknown_6                                   = 0x324;  // uint32.
    namespace SuperJump
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x328;
        constexpr std::size_t k_EntrySize = 0x14;

        constexpr std::size_t k_EnergyToJumpFunction                        = 0x0;  // DataReference.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace AmmoPack
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x334;
        constexpr std::size_t k_EntrySize = 0xC;

        constexpr std::size_t k_EnergyChangePerClipAdded                    = 0x0;  // float32.
        constexpr std::size_t k_ExtraFrags                                  = 0x4;  // int32.
        constexpr std::size_t k_ExtraPlasma                                 = 0x8;  // int32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace PowerFist
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x340;
        constexpr std::size_t k_EntrySize = 0x40;

        constexpr std::size_t k_MeleeDamage                                 = 0x0;  // TagReference.
        constexpr std::size_t k_MeleeResponse                               = 0x10;  // TagReference.
        constexpr std::size_t k_ClangDamage                                 = 0x20;  // TagReference.
        constexpr std::size_t k_ClangResponse                               = 0x30;  // TagReference.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace HealthPack
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x34C;
        constexpr std::size_t k_EntrySize = 0x14;

        constexpr std::size_t k_HealthGivenOverEnergyUsedFunction           = 0x0;  // DataReference.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace Jetpack
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x358;
        constexpr std::size_t k_EntrySize = 0x2C;

        constexpr std::size_t k_ThrustToAccelerationFunction                = 0x0;  // DataReference.
        constexpr std::size_t k_ThrustAttackTime                            = 0x14;  // float32.
        constexpr std::size_t k_ThrustDecayTime                             = 0x18;  // float32.
        constexpr std::size_t k_NegativeVelocityAccelerationScale           = 0x1C;  // float32.
        constexpr std::size_t k_AirborneAccelerationScale                   = 0x20;  // float32.
        constexpr std::size_t k_GroundedAccelerationMagnitude               = 0x24;  // float32.
        constexpr std::size_t k_LandingAnticipationTime                     = 0x28;  // float32.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace Hologram
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x364;
        constexpr std::size_t k_EntrySize = 0x60;

        constexpr std::size_t k_HologramDuration                            = 0x0;  // float32.
        constexpr std::size_t k_CollisionGroup                              = 0x4;  // enum32. [No Override=0xFF, Everything=0x0, Environment Default=0x1, Environment Only=0x2, Small Crate=0x3, Crate=0x4, Huge Crate=0x5, Item=0x6, Projectile=0x7, Machine=0x8, Early Mover Machine=0x9, Creature=0xA, Biped=0xB, Dead Biped=0xC, Super Collidable Ragdoll=0xD, Ragdoll=0xE, Vehicle=0xF, Decal=0x10, Forge Dynamic Scenery=0x11, Small Expensive Plant=0x12, Tech Art Custom=0x13, Unknown x14=0x14, Unknown x15=0x15, Unknown x16=0x16, Unknown x17=0x17, Unknown x18=0x18, Unknown x19=0x19, Unknown x1A=0x1A]
        constexpr std::size_t k_CreationEffect                              = 0x8;  // TagReference.
        constexpr std::size_t k_AttachedEffect                              = 0x18;  // TagReference.
        constexpr std::size_t k_AttachedEffectMarker                        = 0x28;  // StringID.
        constexpr std::size_t k_AttachedEffectPrimaryScale                  = 0x2C;  // StringID.
        constexpr std::size_t k_AttachedEffectSecondaryScale                = 0x30;  // StringID.
        constexpr std::size_t k_DestructionEffect                           = 0x34;  // TagReference.
        constexpr std::size_t k_ShimmerDecreaseRate                         = 0x44;  // float32.
        constexpr std::size_t k_ShimmerBulletPing                           = 0x48;  // float32.
        constexpr std::size_t k_ShimmerToCamoFunction                       = 0x4C;  // DataReference.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace SpecialWeapon
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x370;
        constexpr std::size_t k_EntrySize = 0x10;

        constexpr std::size_t k_Weapon                                      = 0x0;  // TagReference.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace SpecialMove
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x37C;
        constexpr std::size_t k_EntrySize = 0x10;

        constexpr std::size_t k_Forward                                     = 0x0;  // StringID.
        constexpr std::size_t k_Left                                        = 0x4;  // StringID.
        constexpr std::size_t k_Backward                                    = 0x8;  // StringID.
        constexpr std::size_t k_Right                                       = 0xC;  // StringID.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace EngineerShields
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x388;
        constexpr std::size_t k_EntrySize = 0xC;

        constexpr std::size_t k_Radius                                      = 0x0;  // float32.
        constexpr std::size_t k_ShieldName                                  = 0x4;  // StringID.
        constexpr std::size_t k_Flags                                       = 0x8;  // flags32. [Gives Shields To Owner=0]

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    namespace Sprint
    {
        // Array data.
        constexpr std::size_t k_Base      = 0x394;
        constexpr std::size_t k_EntrySize = 0x1;

        constexpr std::size_t k_Unknown                                     = 0x0;  // int8.

        constexpr std::size_t EntryOffset(std::size_t index)
        {
            return k_Base + (index * k_EntrySize);
        }
    }

    constexpr std::size_t k_DamageReportingType                         = 0x3A0;  // enum8. [Guardians (Unknown)=0x0, Guardians (Default)=0x1, Guardians (Scripting)=0x2, Suicide=0x3, Magnum=0x4, Assault Rifle=0x5, DMR=0x6, Shotgun=0x7, Sniper Rifle=0x8, Rocket Launcher=0x9, Spartan Laser=0xA, Frag Grenade=0xB, Grenade Launcher=0xC, Plasma Pistol=0xD, Needler=0xE, Plasma Rifle=0xF, Plasma Repeater=0x10, Needle Rifle=0x11, Spiker=0x12, Plasma Launcher=0x13, Gravity Hammer=0x14, Energy Sword=0x15, Plasma Grenade=0x16, Concussion Rifle=0x17, Ghost=0x18, Revenant=0x19, Revenant Gunner=0x1A, Wraith=0x1B, Wraith Turret=0x1C, Banshee=0x1D, Banshee Bomb=0x1E, Seraph=0x1F, Mongoose=0x20, Warthog=0x21, Warthog Chaingun=0x22, Warthog Gauss=0x23, Warthog Rocket=0x24, Scorpion=0x25, Scorpion Turret=0x26, Falcon=0x27, Falcon Gunner=0x28, Falling=0x29, Collision=0x2A, Melee=0x2B, Explosion=0x2C, Birthday Explosion=0x2D, Flag=0x2E, Bomb=0x2F, Bomb Explosion=0x30, Ball=0x31, Teleporter=0x32, Transfer Damage=0x33, Armor Lock=0x34, Target Locator=0x35, Human Turret=0x36, Plasma Cannon=0x37, Plasma Mortar=0x38, Plasma Turret=0x39, Shade Turret=0x3A, Sabre=0x3B, SMG=0x3C, Carbine=0x3D, Battle Rifle=0x3E, Focus Rifle=0x3F, Fuel Rod=0x40, Missile Pod=0x41, Brute Shot=0x42, Flamethrower=0x43, Sentinel Gun=0x44, Spike Grenade=0x45, Firebomb Grenade=0x46, Elephant Turret=0x47, Spectre=0x48, Spectre Gunner=0x49, Tank=0x4A, Chopper=0x4B, Falcon=0x4C, Mantis=0x4D, Prowler=0x4E, Sentinel Beam=0x4F, Sentinel RPG=0x50, Tripmine=0x51]
    constexpr std::size_t k_Unknown_7                                   = 0x3A1;  // int8.
    constexpr std::size_t k_Unknown_8                                   = 0x3A2;  // int8.
    constexpr std::size_t k_Unknown_9                                   = 0x3A3;  // int8.
    constexpr std::size_t k_HudInterface                                = 0x3A4;  // TagReference.
    constexpr std::size_t k_PickupSound                                 = 0x3B4;  // TagReference.
    constexpr std::size_t k_ActivationWhileDisabledByPlayerTraitsSound  = 0x3C4;  // TagReference.
    constexpr std::size_t k_ActivateEffect                              = 0x3D4;  // TagReference.
    constexpr std::size_t k_LoopingEffect                               = 0x3E4;  // TagReference.
    constexpr std::size_t k_DeactivationEffect                          = 0x3F4;  // TagReference.
    constexpr std::size_t k_EnergyChargedEffect                         = 0x404;  // TagReference.
    constexpr std::size_t k_ActivationAnimation                         = 0x414;  // StringID.
    constexpr std::size_t k_ActiveAnimation                             = 0x418;  // StringID.
    constexpr std::size_t k_DeactivateAnimation                         = 0x41C;  // StringID.
    constexpr std::size_t k_ActiveAnimationStance                       = 0x420;  // StringID.
}
