// Auto-generated by TagTranspiler (GenerateObject.py)
// Source XML: eqip.xml

export module Map.Tag.System:Eqip.Descriptor;

import Map.Tag.Type;
import Map.Reader.Type;
import Map.Reader.System;
import std;

namespace
{
    using namespace Map::Tag::Type::Eqip::Structure;
    using namespace Map::Tag::Type::Eqip::Object;
    namespace MapMagic = Map::Reader::Type::Magic;
}

export namespace Map::Reader::System
{
    template <>
    struct GroupDescriptor<EqipObject>
    {
        using DataType = EqipData;
        static constexpr std::uint32_t Magic = MapMagic::Tag::k_Eqip;

        template <typename TReader>
        static void ReadBlocks(
            std::ifstream& file,
            const TReader& reader,
            EqipObject& obj)
        {
            obj.EarlyMoverOrientedBoundingBox = reader.template ReadBlock<Eqip_EarlyMoverOrientedBoundingBoxEntry>(file, obj.Data.EarlyMoverOrientedBoundingBox);
            obj.AiProperties = reader.template ReadBlock<Eqip_AiPropertiesEntry>(file, obj.Data.AiProperties);
            {
                auto disk_Functions_0 = reader.template ReadBlock<Eqip_FunctionsEntry>(file, obj.Data.Functions);
                obj.Functions.reserve(disk_Functions_0.size());
                for (auto& diskEntry_0 : disk_Functions_0)
                {
                    Eqip_FunctionsObject entry_Functions_0{static_cast<Eqip_FunctionsEntry>(diskEntry_0)};
                    entry_Functions_0.Interpolation = reader.template ReadBlock<Eqip_Functions_InterpolationEntry>(file, diskEntry_0.Interpolation);
                    obj.Functions.push_back(entry_Functions_0);
                }
            }
            obj.RuntimeInterpolatorFunctions = reader.template ReadBlock<Eqip_RuntimeInterpolatorFunctionsEntry>(file, obj.Data.RuntimeInterpolatorFunctions);
            obj.Attachments = reader.template ReadBlock<Eqip_AttachmentsEntry>(file, obj.Data.Attachments);
            {
                auto disk_HullSurfaces_0 = reader.template ReadBlock<Eqip_HullSurfacesEntry>(file, obj.Data.HullSurfaces);
                obj.HullSurfaces.reserve(disk_HullSurfaces_0.size());
                for (auto& diskEntry_0 : disk_HullSurfaces_0)
                {
                    Eqip_HullSurfacesObject entry_HullSurfaces_0{static_cast<Eqip_HullSurfacesEntry>(diskEntry_0)};
                    entry_HullSurfaces_0.Drag = reader.template ReadBlock<Eqip_HullSurfaces_DragEntry>(file, diskEntry_0.Drag);
                    obj.HullSurfaces.push_back(entry_HullSurfaces_0);
                }
            }
            obj.Jetwash = reader.template ReadBlock<Eqip_JetwashEntry>(file, obj.Data.Jetwash);
            obj.Widgets = reader.template ReadBlock<Eqip_WidgetsEntry>(file, obj.Data.Widgets);
            {
                auto disk_ChangeColors_0 = reader.template ReadBlock<Eqip_ChangeColorsEntry>(file, obj.Data.ChangeColors);
                obj.ChangeColors.reserve(disk_ChangeColors_0.size());
                for (auto& diskEntry_0 : disk_ChangeColors_0)
                {
                    Eqip_ChangeColorsObject entry_ChangeColors_0{static_cast<Eqip_ChangeColorsEntry>(diskEntry_0)};
                    entry_ChangeColors_0.InitialPermutations = reader.template ReadBlock<Eqip_ChangeColors_InitialPermutationsEntry>(file, diskEntry_0.InitialPermutations);
                    entry_ChangeColors_0.Functions = reader.template ReadBlock<Eqip_ChangeColors_FunctionsEntry>(file, diskEntry_0.Functions);
                    obj.ChangeColors.push_back(entry_ChangeColors_0);
                }
            }
            obj.MultiplayerObject = reader.template ReadBlock<Eqip_MultiplayerObjectEntry>(file, obj.Data.MultiplayerObject);
            obj.SpawnEffects = reader.template ReadBlock<Eqip_SpawnEffectsEntry>(file, obj.Data.SpawnEffects);
            {
                auto disk_OverrideCamera_0 = reader.template ReadBlock<Eqip_OverrideCameraEntry>(file, obj.Data.OverrideCamera);
                obj.OverrideCamera.reserve(disk_OverrideCamera_0.size());
                for (auto& diskEntry_0 : disk_OverrideCamera_0)
                {
                    Eqip_OverrideCameraObject entry_OverrideCamera_0{static_cast<Eqip_OverrideCameraEntry>(diskEntry_0)};
                    entry_OverrideCamera_0.CameraTracks = reader.template ReadBlock<Eqip_OverrideCamera_CameraTracksEntry>(file, diskEntry_0.CameraTracks);
                    entry_OverrideCamera_0.CameraAcceleration = reader.template ReadBlock<Eqip_OverrideCamera_CameraAccelerationEntry>(file, diskEntry_0.CameraAcceleration);
                    {
                        auto disk_MoveStickOverrides_1 = reader.template ReadBlock<Eqip_OverrideCamera_MoveStickOverridesEntry>(file, diskEntry_0.MoveStickOverrides);
                        entry_OverrideCamera_0.MoveStickOverrides.reserve(disk_MoveStickOverrides_1.size());
                        for (auto& diskEntry_1 : disk_MoveStickOverrides_1)
                        {
                            Eqip_OverrideCamera_MoveStickOverridesObject entry_MoveStickOverrides_1{static_cast<Eqip_OverrideCamera_MoveStickOverridesEntry>(diskEntry_1)};
                            entry_MoveStickOverrides_1.InputMappingFunction = reader.template ReadBlock<Eqip_OverrideCamera_MoveStickOverrides_InputMappingFunctionEntry>(file, diskEntry_1.InputMappingFunction);
                            entry_OverrideCamera_0.MoveStickOverrides.push_back(entry_MoveStickOverrides_1);
                        }
                    }
                    {
                        auto disk_LookStickOverrides_1 = reader.template ReadBlock<Eqip_OverrideCamera_LookStickOverridesEntry>(file, diskEntry_0.LookStickOverrides);
                        entry_OverrideCamera_0.LookStickOverrides.reserve(disk_LookStickOverrides_1.size());
                        for (auto& diskEntry_1 : disk_LookStickOverrides_1)
                        {
                            Eqip_OverrideCamera_LookStickOverridesObject entry_LookStickOverrides_1{static_cast<Eqip_OverrideCamera_LookStickOverridesEntry>(diskEntry_1)};
                            entry_LookStickOverrides_1.InputMappingFunction = reader.template ReadBlock<Eqip_OverrideCamera_LookStickOverrides_InputMappingFunctionEntry>(file, diskEntry_1.InputMappingFunction);
                            entry_OverrideCamera_0.LookStickOverrides.push_back(entry_LookStickOverrides_1);
                        }
                    }
                    obj.OverrideCamera.push_back(entry_OverrideCamera_0);
                }
            }
            obj.MultiplayerPowerup = reader.template ReadBlock<Eqip_MultiplayerPowerupEntry>(file, obj.Data.MultiplayerPowerup);
            obj.Spawner = reader.template ReadBlock<Eqip_SpawnerEntry>(file, obj.Data.Spawner);
            obj.ProximityMine = reader.template ReadBlock<Eqip_ProximityMineEntry>(file, obj.Data.ProximityMine);
            obj.MotionTrackerNoise = reader.template ReadBlock<Eqip_MotionTrackerNoiseEntry>(file, obj.Data.MotionTrackerNoise);
            {
                auto disk_InvincibilityMode_0 = reader.template ReadBlock<Eqip_InvincibilityModeEntry>(file, obj.Data.InvincibilityMode);
                obj.InvincibilityMode.reserve(disk_InvincibilityMode_0.size());
                for (auto& diskEntry_0 : disk_InvincibilityMode_0)
                {
                    Eqip_InvincibilityModeObject entry_InvincibilityMode_0{static_cast<Eqip_InvincibilityModeEntry>(diskEntry_0)};
                    entry_InvincibilityMode_0.ThresholdEffects = reader.template ReadBlock<Eqip_InvincibilityMode_ThresholdEffectsEntry>(file, diskEntry_0.ThresholdEffects);
                    obj.InvincibilityMode.push_back(entry_InvincibilityMode_0);
                }
            }
            obj.TreeOfLife = reader.template ReadBlock<Eqip_TreeOfLifeEntry>(file, obj.Data.TreeOfLife);
            obj.Shapeshifter = reader.template ReadBlock<Eqip_ShapeshifterEntry>(file, obj.Data.Shapeshifter);
            {
                auto disk_PlayerTraitField_0 = reader.template ReadBlock<Eqip_PlayerTraitFieldEntry>(file, obj.Data.PlayerTraitField);
                obj.PlayerTraitField.reserve(disk_PlayerTraitField_0.size());
                for (auto& diskEntry_0 : disk_PlayerTraitField_0)
                {
                    Eqip_PlayerTraitFieldObject entry_PlayerTraitField_0{static_cast<Eqip_PlayerTraitFieldEntry>(diskEntry_0)};
                    {
                        auto disk_ActivePlayerTraits_1 = reader.template ReadBlock<Eqip_PlayerTraitField_ActivePlayerTraitsEntry>(file, diskEntry_0.ActivePlayerTraits);
                        entry_PlayerTraitField_0.ActivePlayerTraits.reserve(disk_ActivePlayerTraits_1.size());
                        for (auto& diskEntry_1 : disk_ActivePlayerTraits_1)
                        {
                            Eqip_PlayerTraitField_ActivePlayerTraitsObject entry_ActivePlayerTraits_1{static_cast<Eqip_PlayerTraitField_ActivePlayerTraitsEntry>(diskEntry_1)};
                            entry_ActivePlayerTraits_1.VitalityTraits = reader.template ReadBlock<Eqip_PlayerTraitField_ActivePlayerTraits_VitalityTraitsEntry>(file, diskEntry_1.VitalityTraits);
                            entry_ActivePlayerTraits_1.WeaponTraits = reader.template ReadBlock<Eqip_PlayerTraitField_ActivePlayerTraits_WeaponTraitsEntry>(file, diskEntry_1.WeaponTraits);
                            entry_ActivePlayerTraits_1.MovementTraits = reader.template ReadBlock<Eqip_PlayerTraitField_ActivePlayerTraits_MovementTraitsEntry>(file, diskEntry_1.MovementTraits);
                            entry_ActivePlayerTraits_1.AppearanceTraits = reader.template ReadBlock<Eqip_PlayerTraitField_ActivePlayerTraits_AppearanceTraitsEntry>(file, diskEntry_1.AppearanceTraits);
                            entry_ActivePlayerTraits_1.SensorTraits = reader.template ReadBlock<Eqip_PlayerTraitField_ActivePlayerTraits_SensorTraitsEntry>(file, diskEntry_1.SensorTraits);
                            entry_PlayerTraitField_0.ActivePlayerTraits.push_back(entry_ActivePlayerTraits_1);
                        }
                    }
                    {
                        auto disk_InactivePlayerTraits_1 = reader.template ReadBlock<Eqip_PlayerTraitField_InactivePlayerTraitsEntry>(file, diskEntry_0.InactivePlayerTraits);
                        entry_PlayerTraitField_0.InactivePlayerTraits.reserve(disk_InactivePlayerTraits_1.size());
                        for (auto& diskEntry_1 : disk_InactivePlayerTraits_1)
                        {
                            Eqip_PlayerTraitField_InactivePlayerTraitsObject entry_InactivePlayerTraits_1{static_cast<Eqip_PlayerTraitField_InactivePlayerTraitsEntry>(diskEntry_1)};
                            entry_InactivePlayerTraits_1.VitalityTraits = reader.template ReadBlock<Eqip_PlayerTraitField_InactivePlayerTraits_VitalityTraitsEntry>(file, diskEntry_1.VitalityTraits);
                            entry_InactivePlayerTraits_1.WeaponTraits = reader.template ReadBlock<Eqip_PlayerTraitField_InactivePlayerTraits_WeaponTraitsEntry>(file, diskEntry_1.WeaponTraits);
                            entry_InactivePlayerTraits_1.MovementTraits = reader.template ReadBlock<Eqip_PlayerTraitField_InactivePlayerTraits_MovementTraitsEntry>(file, diskEntry_1.MovementTraits);
                            entry_InactivePlayerTraits_1.AppearanceTraits = reader.template ReadBlock<Eqip_PlayerTraitField_InactivePlayerTraits_AppearanceTraitsEntry>(file, diskEntry_1.AppearanceTraits);
                            entry_InactivePlayerTraits_1.SensorTraits = reader.template ReadBlock<Eqip_PlayerTraitField_InactivePlayerTraits_SensorTraitsEntry>(file, diskEntry_1.SensorTraits);
                            entry_PlayerTraitField_0.InactivePlayerTraits.push_back(entry_InactivePlayerTraits_1);
                        }
                    }
                    obj.PlayerTraitField.push_back(entry_PlayerTraitField_0);
                }
            }
            {
                auto disk_AiTraitField_0 = reader.template ReadBlock<Eqip_AiTraitFieldEntry>(file, obj.Data.AiTraitField);
                obj.AiTraitField.reserve(disk_AiTraitField_0.size());
                for (auto& diskEntry_0 : disk_AiTraitField_0)
                {
                    Eqip_AiTraitFieldObject entry_AiTraitField_0{static_cast<Eqip_AiTraitFieldEntry>(diskEntry_0)};
                    {
                        auto disk_ActiveAiEquipmentTraits_1 = reader.template ReadBlock<Eqip_AiTraitField_ActiveAiEquipmentTraitsEntry>(file, diskEntry_0.ActiveAiEquipmentTraits);
                        entry_AiTraitField_0.ActiveAiEquipmentTraits.reserve(disk_ActiveAiEquipmentTraits_1.size());
                        for (auto& diskEntry_1 : disk_ActiveAiEquipmentTraits_1)
                        {
                            Eqip_AiTraitField_ActiveAiEquipmentTraitsObject entry_ActiveAiEquipmentTraits_1{static_cast<Eqip_AiTraitField_ActiveAiEquipmentTraitsEntry>(diskEntry_1)};
                            entry_ActiveAiEquipmentTraits_1.AppearanceTraits = reader.template ReadBlock<Eqip_AiTraitField_ActiveAiEquipmentTraits_AppearanceTraitsEntry>(file, diskEntry_1.AppearanceTraits);
                            entry_AiTraitField_0.ActiveAiEquipmentTraits.push_back(entry_ActiveAiEquipmentTraits_1);
                        }
                    }
                    {
                        auto disk_InactiveAiEquipmentTraits_1 = reader.template ReadBlock<Eqip_AiTraitField_InactiveAiEquipmentTraitsEntry>(file, diskEntry_0.InactiveAiEquipmentTraits);
                        entry_AiTraitField_0.InactiveAiEquipmentTraits.reserve(disk_InactiveAiEquipmentTraits_1.size());
                        for (auto& diskEntry_1 : disk_InactiveAiEquipmentTraits_1)
                        {
                            Eqip_AiTraitField_InactiveAiEquipmentTraitsObject entry_InactiveAiEquipmentTraits_1{static_cast<Eqip_AiTraitField_InactiveAiEquipmentTraitsEntry>(diskEntry_1)};
                            entry_InactiveAiEquipmentTraits_1.AppearanceTraits = reader.template ReadBlock<Eqip_AiTraitField_InactiveAiEquipmentTraits_AppearanceTraitsEntry>(file, diskEntry_1.AppearanceTraits);
                            entry_AiTraitField_0.InactiveAiEquipmentTraits.push_back(entry_InactiveAiEquipmentTraits_1);
                        }
                    }
                    obj.AiTraitField.push_back(entry_AiTraitField_0);
                }
            }
            obj.RepulsorField = reader.template ReadBlock<Eqip_RepulsorFieldEntry>(file, obj.Data.RepulsorField);
            obj.Iwhbydaddy = reader.template ReadBlock<Eqip_IwhbydaddyEntry>(file, obj.Data.Iwhbydaddy);
            obj.SuperJump = reader.template ReadBlock<Eqip_SuperJumpEntry>(file, obj.Data.SuperJump);
            obj.AmmoPack = reader.template ReadBlock<Eqip_AmmoPackEntry>(file, obj.Data.AmmoPack);
            obj.PowerFist = reader.template ReadBlock<Eqip_PowerFistEntry>(file, obj.Data.PowerFist);
            obj.HealthPack = reader.template ReadBlock<Eqip_HealthPackEntry>(file, obj.Data.HealthPack);
            obj.Jetpack = reader.template ReadBlock<Eqip_JetpackEntry>(file, obj.Data.Jetpack);
            obj.Hologram = reader.template ReadBlock<Eqip_HologramEntry>(file, obj.Data.Hologram);
            obj.SpecialWeapon = reader.template ReadBlock<Eqip_SpecialWeaponEntry>(file, obj.Data.SpecialWeapon);
            obj.SpecialMove = reader.template ReadBlock<Eqip_SpecialMoveEntry>(file, obj.Data.SpecialMove);
            obj.EngineerShields = reader.template ReadBlock<Eqip_EngineerShieldsEntry>(file, obj.Data.EngineerShields);
            obj.Sprint = reader.template ReadBlock<Eqip_SprintEntry>(file, obj.Data.Sprint);
        }
    };
}
