// Auto-generated by TagTranspiler (GenerateObject.py)
// Source XML: jpt!.xml

export module Map.Tag.System:Jpt.Descriptor;

import Map.Tag.Type;
import Map.Reader.Type;
import Map.Reader.System;
import std;

namespace
{
    using namespace Map::Tag::Type::Jpt::Structure;
    using namespace Map::Tag::Type::Jpt::Object;
    namespace MapMagic = Map::Reader::Type::Magic;
}

export namespace Map::Reader::System
{
    template <>
    struct GroupDescriptor<JptObject>
    {
        using DataType = JptData;
        static constexpr std::uint32_t Magic = MapMagic::Tag::k_Jpt;

        template <typename TReader>
        static void ReadBlocks(
            std::ifstream& file,
            const TReader& reader,
            JptObject& obj)
        {
            obj.CustomResponseLabels = reader.template ReadBlock<Jpt_CustomResponseLabelsEntry>(file, obj.Data.CustomResponseLabels);
            obj.DamageSounds = reader.template ReadBlock<Jpt_DamageSoundsEntry>(file, obj.Data.DamageSounds);
        }
    };
}
